-- Run after 001. Read-only checks; also works after first-admin setup.
DO $verify$ DECLARE name text;r record;BEGIN
 FOREACH name IN ARRAY ARRAY['accounting_archive_audit126','accounting_archive_preview127','accounting_archive_staff_parents128','accounting_workspace_allowed123','admin_save_access14281','admin_save_access1441','approve_entry_submission','approve_fund_adjustment_v49','approve_report1443','approved_report1443','assigned_ledger14281','audit_month1434','audit_snapshot14232','backup_export113','begin_book_session136','book_sessions_list136','branch_home14229','budget_capabilities14316','cancel_scheduled_posting93','close_year14317','correct_scheduled_date92','current_access14228','delete_budget14316','delete_one_audit1437','delete_record108','delete_scheduled_journal92','employee_photo113','finish_book_session136','finish_book_session14317','fund_balances136','installation_status14320','is_admin','journal_receipt14228','link_recorded_workspace_handover','mark_journal_entry_under_review','opening_status14234','operational_data_backup142','operational_data_reset142','password_change_status14257','period_pending14317','post_journal_batch14228','post_manual_journal14228','post_opening_balances14234','post_scheduled_one92','post_workspace_review_v3','preview_journal_number14257','preview_staff_workspace_entry_no','reject_entry_submission','reminder_load14229','reminder_save14229','reopen_staff_journal','report_history14229','resolve_audit_review136','review_collection_report','review_directory14229','review_inbox14229','review_scheduled_occurrence91','revise_open_journal_entry','save_audit_review136','save_installation14320','save_staff_editor1437','save_staff_workspace_entry_v3','scoped_reset14232','scoped_reset_backup14232','set_accounting_period_status','set_period_status14317','set_scheduled_status91','staff_report1434','stage_book_operation136','submit_fund_adjustment_v49','submit_report14253','submit_staff_journal','team_funds113','void_journal_entry','void_staff_editor1437','void_staff_workspace_entry','voucher_config14299','voucher_issue14299','voucher_link14299','voucher_update14299','voucher_void14299','workspace_context138','workspace_live_activity_v49','year_preflight136'] LOOP
  IF NOT EXISTS(SELECT 1 FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname='public' AND p.proname=name AND p.prokind='f') THEN RAISE EXCEPTION 'Required client function missing: %',name;END IF;
 END LOOP;
 FOR r IN SELECT c.oid,c.relname,c.relrowsecurity FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname='public' AND c.relkind IN ('r','p') LOOP
  IF has_table_privilege('anon',r.oid,'SELECT,INSERT,UPDATE,DELETE,TRUNCATE') THEN RAISE EXCEPTION 'Unexpected anonymous table access: %',r.relname;END IF;
  IF NOT r.relrowsecurity AND has_table_privilege('authenticated',r.oid,'SELECT,INSERT,UPDATE,DELETE') THEN RAISE EXCEPTION 'Authenticated table access without RLS: %',r.relname;END IF;
 END LOOP;
 IF NOT has_table_privilege('service_role','public.profiles','SELECT') THEN RAISE EXCEPTION 'Backend administrator verification lacks profile access';END IF;
 IF has_function_privilege('authenticated','private.remove_backed_up_records14322(text,date,date,text)','EXECUTE') THEN RAISE EXCEPTION 'Owner-only maintenance was exposed';END IF;
 IF NOT EXISTS(SELECT 1 FROM public.installation14320 WHERE id) OR NOT EXISTS(SELECT 1 FROM public.business_settings WHERE id) THEN RAISE EXCEPTION 'Required installation defaults missing';END IF;
END $verify$;
SELECT 'Backend structure and access checks passed' AS result,
 (SELECT count(*) FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','private') AND c.relkind='r') AS application_tables,
 (SELECT count(*) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','private') AND p.prokind='f') AS application_functions;
SELECT id,public FROM storage.buckets ORDER BY id;
