/* Company access matrix. Server policies remain authoritative. */
(function(){'use strict';
const actions=['view','edit','export','approve','post','void'];
const labels={view:'View',edit:'Edit',export:'Export / Print',approve:'Approve',post:'Post',void:'Void'};
const adminOnly=new Set(['settings-users','settings-system','settings-backup113','settings-recovery113','settings-appearance113']);
const esc=v=>window.shell113.esc(v);let editing={};
function permission(){return typeof livePermission==='undefined'?null:livePermission}
function can(target,action='view'){if(typeof liveProfile==='undefined'||!liveProfile||liveProfile.status&&liveProfile.status!=='active')return false;if(liveProfile.role==='admin')return true;if(target==='document-editor105')return ['view','edit','export'].includes(action);if(adminOnly.has(target))return false;if(target==='pos118')return window.pos118?.state.sample===true||window.pos118?.state.config?.cashiers?.includes(liveProfile.id);const p=permission();if(p&&Object.hasOwn(p,'module_actions113')&&p.module_actions113!==null){const row=p.module_actions113?.[target];if(!Array.isArray(row))return false;return row.includes('view')&&(action==='view'||row.includes(action))}if(action==='view')return legacy(target);return legacy(target)&&Boolean(({edit:p?.can_manage_data,export:p?.can_export,approve:p?.can_approve,post:p?.can_post_directly,void:p?.can_void})[action])}
const legacy=window.canAccessAppTarget;
function eligible(target){if(adminOnly.has(target))return[];if(target==='sub-users-summary113')return['view'];const a=['view','edit','export'];if(/journal|review|payroll-entries|period-review/.test(target))a.push('approve','post','void');if(target==='sub-users-workspace')a.push('post','void');return a}
function categoryActions(parent){return actions.filter(a=>parent.children.some(([id])=>eligible(id).includes(a)))}
function grid(){const host=document.getElementById('userPermissionGrid');if(!host)return;host.className='permission-matrix113 permission-matrix1427';host.innerHTML='<p>Choose access within each module. All access selects every available permission in that category.</p>'+APP_PERMISSION_TREE.map(p=>{const available=categoryActions(p);return `<details open><summary><span>${esc(p.label)}</span><label class="permission-all1427"><input type="checkbox" data-all1427="${esc(p.id)}" aria-label="All access for ${esc(p.label)}">All access</label></summary><div class="permission-grid113" style="--permission-count:${available.length}"><strong>Module</strong>${available.map(a=>`<label><input type="checkbox" data-parent113="${esc(p.id)}" data-action113="${a}" aria-label="${esc(p.label)}: ${labels[a]}">${labels[a]}</label>`).join('')}${p.children.map(([id,label])=>`<span>${esc(label)}${adminOnly.has(id)?' · Admin only':''}</span>${available.map(a=>`<label><input type="checkbox" data-target113="${esc(id)}" data-action113="${a}" ${eligible(id).includes(a)?'':'disabled'} ${(editing[id]||[]).includes(a)?'checked':''} aria-label="${esc(label)}: ${labels[a]}"></label>`).join('')}`).join('')}</div></details>`}).join('');host.querySelectorAll('.permission-all1427').forEach(n=>n.onclick=e=>e.stopPropagation());host.onchange=e=>{const b=e.target;if(b.dataset.all1427){const parent=APP_PERMISSION_TREE.find(p=>p.id===b.dataset.all1427);for(const [id] of parent.children)editing[id]=b.checked?eligible(id):[]}else{const a=b.dataset.action113;if(!a)return;const targets=b.dataset.parent113?APP_PERMISSION_TREE.find(p=>p.id===b.dataset.parent113).children.map(x=>x[0]):[b.dataset.target113];for(const id of targets){if(!eligible(id).includes(a))continue;let row=new Set(editing[id]||[]);if(b.checked){row.add(a);row.add('view')}else if(a==='view')row.clear();else row.delete(a);editing[id]=[...row]}}syncChecks(host);updateUserAccessSummaries()};syncChecks(host)}
function syncChecks(host){host.querySelectorAll('[data-target113]').forEach(b=>b.checked=(editing[b.dataset.target113]||[]).includes(b.dataset.action113));for(const parent of APP_PERMISSION_TREE){const permissions=parent.children.flatMap(([id])=>eligible(id).map(a=>[id,a])),selected=permissions.filter(([id,a])=>(editing[id]||[]).includes(a)).length,all=host.querySelector(`[data-all1427="${parent.id}"]`);all.disabled=!permissions.length;all.checked=permissions.length>0&&selected===permissions.length;all.indeterminate=selected>0&&selected<permissions.length;for(const a of categoryActions(parent)){const ids=parent.children.map(x=>x[0]).filter(id=>eligible(id).includes(a)),count=ids.filter(id=>(editing[id]||[]).includes(a)).length,b=host.querySelector(`[data-parent113="${parent.id}"][data-action113="${a}"]`);b.disabled=!ids.length;b.checked=count>0&&count===ids.length;b.indeterminate=count>0&&count<ids.length}}}
function editorValue(){return Object.fromEntries(Object.entries(editing).map(([id,row])=>[id,row.filter(a=>eligible(id).includes(a))]))}
function editorModules(){return APP_PERMISSION_TREE.flatMap(p=>p.children.filter(([id])=>(editing[id]||[]).includes('view')).map(([id])=>p.id+':'+id))}
function currentTarget(){const root=document.querySelector('.tab-content.active');if(root?.id==='accounts-modular-container')return [...root.querySelectorAll('[id^=sec-]')].find(n=>!n.hidden&&getComputedStyle(n).display!=='none')?.id||root.id;return root?.id||''}
function actionFor(b){if(b.dataset.permissionAction1440)return b.dataset.permissionAction1440;if(b.closest('#jeLinesBody')&&b.matches('.je-btn-del,.tx74-remove,[onclick*=removeJournalLineRow]')||b.matches('[data-remove1430]'))return 'edit';if(b.dataset.personalTab||b.dataset.historyPage)return '';if(b.id==='btnPostJournal'&&window.personalJournal1437?.active)return 'edit';if(b.classList.contains('header-icon112'))return ''; // Hidden icon editing checks administrator access itself.
const data=[b.getAttribute('onclick'),b.dataset.action,b.dataset.imAction,b.title,b.textContent].filter(Boolean).join(' ').toLowerCase();if(/export|download|print|csv|pdf/.test(data))return'export';if(/void|delete|remove/.test(data))return'void';if(/approve/.test(data))return'approve';if(/post|finali[sz]e/.test(data)&&!/post single entry/.test(data))return'post';if(/save|edit|add |create|update|submit|adjust|upload|import|close period|reopen|change icon/.test(data)||b.type==='submit')return'edit';return''}
function enforce(){if(typeof liveProfile==='undefined'||!liveProfile)return;const root=document.querySelector('.tab-content.active');if(!root)return;const target=currentTarget();root.querySelectorAll('button,a,[onclick]').forEach(b=>{const a=actionFor(b);if(!a)return;const denied=!can(target,a);if(denied){if(!b.dataset.accessDisabled113){b.dataset.accessDisabled113=String(!!b.disabled);b.dataset.accessTitle113=b.title||''}b.disabled=true;b.setAttribute('aria-disabled','true');b.title=labels[a]+' permission required'}else if(b.dataset.accessDisabled113!==undefined){b.disabled=b.dataset.accessDisabled113==='true';b.title=b.dataset.accessTitle113;delete b.dataset.accessDisabled113;delete b.dataset.accessTitle113;b.removeAttribute('aria-disabled')}})}
let recipes=[],recipeOwner='',recipeError='',recipeBusy=false;
async function loadRecipe(force=false){if(recipeBusy||!liveProfile||recipeOwner===liveProfile.id&&!force)return;if(!can('menu-recipe')&&!can('menu-details'))return;recipeBusy=true;recipeError='';try{const r=await ojmDb.rpc('recipe_view113');if(r.error)throw r.error;recipes=r.data||[];recipeOwner=liveProfile.id}catch(e){recipeError=e.message}finally{recipeBusy=false;const active=document.querySelector('.tab-content.active');if(active?.id.startsWith('menu-'))renderRecipe(active)}}
function renderRecipe(active){if(!['menu-recipe','menu-details'].includes(active.id)){active.innerHTML='<section class="panel113"><h3>Module access</h3><p>This section is not available for your current role. Contact your administrator. You can view assigned recipes in Menus and Recipes.</p></section>';return}active.innerHTML=`<section class="panel113 recipe-read113"><header><h2>Menus and Recipes</h2><span>View only</span></header>${recipeError?`<p role="alert">${esc(recipeError)}</p>`:recipeBusy?'<p>Loading recipes…</p>':recipes.map(r=>`<details><summary>${esc(r.code)} · ${esc(r.name)}</summary>${/^data:image\/(png|jpeg|webp);base64,/.test(r.photoData||'')?`<img src="${esc(r.photoData)}" alt="${esc(r.name)}">`:''}<p>${esc(r.description||'')}</p><table><thead><tr><th>Ingredient</th><th>Quantity per serving</th></tr></thead><tbody>${(r.recipe||[]).map(x=>`<tr><td>${esc(x.name)}</td><td>${esc(x.quantity)} ${esc(x.unit)}</td></tr>`).join('')}</tbody></table></details>`).join('')||'<p>No recipes available.</p>'}</section>`;shell113.sync()}
function ready(){const sub=APP_PERMISSION_TREE.find(p=>p.id==='sub-users');if(sub&&!sub.children.some(x=>x[0]==='sub-users-summary113'))sub.children.push(['sub-users-summary113','Team fund summary (no account details)']);const oldOpen=window.openWorkspaceUser;window.openWorkspaceUser=function(id){if(liveProfile?.role!=='admin'&&id!==liveProfile?.id&&!((liveProfiles.find(u=>u.id===id)?.user_permissions?.manager_id===liveProfile.id)&&can('user-entry-review'))){showCenterStatus('This account is not assigned to you.',true);return}return oldOpen(id)};const old=window.openUserAccessEditor;window.openUserAccessEditor=function(id=''){old(id);const p=liveProfiles.find(x=>x.id===id)?.user_permissions||{};editing=structuredClone(p.module_actions113||{});if(!p.module_actions113){const modules=p.modules||[];for(const parent of APP_PERMISSION_TREE)for(const [target] of parent.children)if(modules.includes(parent.id)||modules.includes('all:'+parent.id)||modules.includes(parent.id+':'+target))editing[target]=['view']}grid();const security=document.getElementById('userSecurityAccessPanel');if(security){security.hidden=true;security.closest('.user-access-section')?.classList.add('old-security113')}document.querySelectorAll('[onclick*="userSecurityAccessPanel"]').forEach(x=>x.hidden=true)};
window.canAccessAppTarget=function(target){if(typeof liveProfile==='undefined'||!liveProfile)return false;if(target==='accounts-modular-container')return APP_PERMISSION_TREE.find(p=>p.id==='accounts').children.some(([id])=>can(id));return can(target)};
const oldSave=window.saveUserAccess;window.saveUserAccess=async function(event){const map={permissionApprove:'approve',permissionDirectPost:'post',permissionVoid:'void',permissionExport:'export',permissionManageData:'edit'};Object.entries(map).forEach(([id,a])=>{const b=document.getElementById(id);if(b)b.checked=Object.values(editing).some(row=>row.includes(a))});return oldSave(event)};
const oldSummary=window.updateUserAccessSummaries;window.updateUserAccessSummaries=function(){oldSummary();const n=document.getElementById('userModuleAccessSummary');if(n)n.textContent=Object.values(editing).filter(a=>a.includes('view')).length+' modules · actions within each module'};
document.addEventListener('click',e=>{const b=e.target.closest('button,a,[onclick]');if(!b||!b.closest('.tab-content.active'))return;const a=actionFor(b);if(a&&!can(currentTarget(),a)){e.preventDefault();e.stopImmediatePropagation();showCenterStatus(labels[a]+' is not included in your access.',true)}},true);
document.addEventListener('submit',e=>{if(e.target.closest('.tab-content.active')&&!can(currentTarget(),'edit')){e.preventDefault();e.stopImmediatePropagation();showCenterStatus('This module is read-only.',true)}},true);
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;enforce()})}).observe(document.querySelector('.workspace-scroll')||document.body,{childList:true,subtree:true});window.addEventListener('page113',enforce);enforce();}
window.access113={can,currentTarget,actionFor,loadRecipe,renderRecipe,editorValue,editorModules,editorCan:(id,a)=>(editing[id]||[]).includes(a),enforce};document.addEventListener('DOMContentLoaded',ready,{once:true});
})();
