(()=>{'use strict';
const $=id=>document.getElementById(id);
const sections={
 Dashboard:['journal_entries','staff_journals','payroll_runs','tax_sso_records'],
 Transactions:['operational_reports','journal_entries','journal_lines','vouchers14299','voucher_versions14299','entry_submissions','scheduled_journal_occurrences','scheduled_journals','accounting_periods','period_findings','recurring_transactions','recurring_reminders','audit_log','record_deletions108'],
 Accounts:['accounts','sub_accounts','journal_entries','journal_lines','currencies'],
 'Sub-users':['staff_journals','staff_journal_lines','fund_adjustment_requests','fund_adjustment_lines','workspace_notifications','user_fund_assignments','profiles','user_permissions'],
 Payroll:['payroll_runs','payroll_lines','payroll_employees'],
 HR:['payroll_employees','payroll_leave_records','employees','legal_documents'],
 'Tax & SSO':['tax_sso_records','journal_entries','journal_lines'],
 Reports:['operational_reports','journal_entries','journal_lines','payroll_runs','accounting_periods'],
 Settings:['business_settings','accounting_id_settings','currencies','print_settings','presentation_settings113','profiles','user_permissions','entry_prefix_reservations','staff_entry_sequences'],
 'All records':[]
};
let pack=null,section='Dashboard',shown=50,current=[],selected=null;
const all=(name)=>pack?.tables?.[name]??pack?.auditTrail?.[name]??[];
const money=v=>v==null?'':String(v);
const display=v=>v==null?'—':typeof v==='object'?JSON.stringify(v):String(v);
const name=(table,row)=>{
 if(table==='vouchers14299')return [row.number,row.status,row.data?.journal?.entry_no].filter(Boolean).join(' · ');
 if(table==='voucher_versions14299')return `Version ${row.version} · ${row.reason||''}`;
 if(table==='journal_entries')return [row.entry_no,row.memo].filter(Boolean).join(' · ')||'Journal entry';
 if(table==='journal_lines')return `Line ${row.line_no||''} · ${account(row.account_id)} · ${money(row.debit||row.credit)} ${row.currency_code||''}`;
 if(table==='accounts'||table==='sub_accounts')return [row.code,row.name].filter(Boolean).join(' · ');
 if(table==='staff_journals')return `${person(row.owner_id)} · ${row.period_start||''} to ${row.period_end||''}`;
 if(table==='staff_journal_lines')return `${row.transaction_date||''} · ${row.memo||row.entry_kind||'Staff entry'} · ${money(row.amount)} ${row.currency_code||''}`;
 if(table==='payroll_employees'||table==='payroll_leave_records'||table==='operational_reports'||table==='company_documents105')return row.data?.name||row.data?.title||row.data?.purpose||row.data?.reference||row.data?.month||row.data?.from||row.data?.code||row.id||table;
 if(table==='payroll_runs')return `${row.period_start||row.data?.month||'Payroll'} · ${row.status||row.data?.status||''}`;
 if(table==='profiles')return row.full_name||row.email||row.id;
 if(table==='tax_sso_records')return `${row.record_type||'Tax / SSO'} · ${row.period_start||''} · ${money(row.amount)}`;
 return row.name||row.title||row.code||row.request_no||row.reference||row.entry_no||row.transaction_date||row.created_at?.slice(0,10)||row.id||table;
};
const account=id=>all('accounts').find(x=>x.id===id)?.name||all('sub_accounts').find(x=>x.id===id)?.name||id||'Unknown account';
const person=id=>all('profiles').find(x=>x.id===id)?.full_name||all('payroll_employees').find(x=>x.data?.userId===id)?.data?.name||id||'Unknown user';
const dateOf=(t,r)=>r.voucher_date||r.transaction_date||r.period_start||r.occurrence_date||r.line_date||r.data?.date||r.data?.month||r.data?.from||r.created_at?.slice(0,10)||'';
function openPack(data){window.backupValidation1441.validate(data);if(data?.format!=='oonjai-data-113'||!data.tables||typeof data.tables!=='object'||!Array.isArray(data.tables.journal_entries)||!Array.isArray(data.tables.accounts))throw Error('Choose an Oon Jai Application data archive JSON file.');pack=data;section='Dashboard';selected=null;const total=Object.values(data.tables).reduce((n,v)=>n+(Array.isArray(v)?v.length:0),0);$('status').classList.remove('error');const parentIds=new Set((data.tables.staff_journals||[]).map(r=>String(r.id)));const missing=(data.tables.staff_journal_lines||[]).filter(r=>r.staff_journal_id&&!parentIds.has(String(r.staff_journal_id))).length;$('status').textContent=`${data.from&&data.to?data.from+' through '+data.to:'All time'} · ${total} application rows across ${Object.keys(data.tables).length} tables · ${data.auditTrail?.audit_log?.length||0} audit rows. This is a read-only snapshot; nothing here connects to Supabase.${missing?' WARNING: '+missing+' sub-user lines have missing parent journals. Re-export with v128 before relying on this archive.':''}`;$('status').classList.toggle('error',!!missing);$('overview').hidden=false;$('controls').hidden=false;renderNav();render()}
function renderNav(){const host=$('navigation');host.replaceChildren();for(const key of Object.keys(sections)){const b=document.createElement('button');b.type='button';b.textContent=key;b.className=key===section?'active':'';b.onclick=()=>{section=key;shown=50;selected=null;$('search').value='';$('detail').hidden=true;document.querySelector('.sidebar').classList.remove('open');$('view').value='';renderNav();render()};host.append(b)}}
function card(label,value,hint){const el=document.createElement('div');el.className='stat';const small=document.createElement('small'),strong=document.createElement('strong'),sub=document.createElement('small');small.textContent=label;strong.textContent=String(value);sub.textContent=hint;el.append(small,strong,sub);return el}
function overview(){const host=$('overview');host.replaceChildren();const category=pack.archiveSelection?.categories||{};const cards=section==='Dashboard'?[['Selected period rows',pack.archiveSelection?.total??'—','The dated archive selection'],['Journal entries',all('journal_entries').length,'Includes linked supporting rows'],['Accounts',all('accounts').length,'Account list at export time'],['Sub-user lines',all('staff_journal_lines').length,'Archived activity'],['Payroll runs',all('payroll_runs').length,'Saved runs'],['Audit records',all('audit_log').length,'Separate audit history']]:Object.entries(category).map(([k,v])=>[k,v,'Selected rows in this dated archive']);for(const args of cards)host.append(card(...args))}
function tableNames(){if(section==='Accounts')return ['__trial','__ledger',...sections.Accounts];if(section==='Reports')return ['__income','__trial',...sections.Reports];if(section==='All records')return [...new Set([...Object.keys(pack.tables),...Object.keys(pack.auditTrail||{})])].sort();return sections[section].filter((n,i,a)=>a.indexOf(n)===i&&(n in pack.tables||n in (pack.auditTrail||{})))}
function render(){if(!pack)return;$('heading').textContent=section+' · Archive';overview();const selector=$('view'),previous=selector.value,valid=tableNames();selector.replaceChildren();for(const t of valid){const opt=document.createElement('option');opt.value=t;opt.textContent=t==='__trial'?'Trial balance · archived journals':t==='__ledger'?'General ledger · archived journals':t==='__income'?'Income & expense summary · archived journals':`${t.replaceAll('_',' ')} (${all(t).length})`;selector.append(opt)}selector.value=valid.includes(previous)?previous:valid[0]||'';renderRows()}
function renderRows(){if(!pack)return;const table=$('view').value;if(table.startsWith('__')){renderComputed(table);return}const q=$('search').value.trim().toLowerCase(),rows=all(table);current=q?rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q)):rows;$('rowCount').textContent=`${current.length} of ${rows.length} records`;const target=$('results');target.replaceChildren();if(section==='Dashboard'){const p=document.createElement('div');p.className='panel';const h=document.createElement('h2');h.textContent='Audit this archive';const note=document.createElement('p');note.textContent='Choose a section, search its records, and open a record for every saved field and its linked entries. Counts describe this downloaded file. A dated archive can also contain reference records from outside its selected dates.';p.append(h,note);target.append(p)}if(!current.length){const p=document.createElement('div');p.className='panel';p.textContent='No records in this view.';target.append(p)}for(const row of current.slice(0,shown)){const b=document.createElement('button');b.type='button';b.className='record';const title=document.createElement('strong'),meta=document.createElement('small'),tag=document.createElement('span');title.textContent=display(name(table,row));meta.textContent=[dateOf(table,row),row.status,row.currency_code,row.id].filter(Boolean).join(' · ');tag.className='tag';tag.textContent=table.replaceAll('_',' ');b.append(tag,title,meta);b.onclick=()=>detail(table,row);target.append(b)}$('more').hidden=current.length<=shown}

function totals(){const posted=new Set(all('journal_entries').filter(r=>r.status==='posted').map(r=>r.id)),accounts=new Map(all('accounts').map(r=>[r.id,r]));const map=new Map();for(const line of all('journal_lines')){if(!posted.has(line.journal_entry_id))continue;const a=accounts.get(line.account_id);if(!a)continue;const currency=line.currency_code||a.currency_code||'LAK',key=a.id+'|'+currency;let v=map.get(key);if(!v){v={account:a,currency,debit:0,credit:0,lines:0};map.set(key,v)}v.debit+=Number(line.debit)||0;v.credit+=Number(line.credit)||0;v.lines++}return [...map.values()].sort((a,b)=>String(a.account.code).localeCompare(String(b.account.code))||a.currency.localeCompare(b.currency))}
function renderComputed(mode){const target=$('results');target.replaceChildren();const q=$('search').value.trim().toLowerCase();let values=totals();if(mode==='__income')values=values.filter(x=>['REVENUE','EXPENSE'].includes(x.account.account_type));if(q)values=values.filter(x=>(x.account.code+' '+x.account.name+' '+x.currency+' '+x.account.account_type).toLowerCase().includes(q));$('rowCount').textContent=`${values.length} account/currency balances`;const note=document.createElement('div');note.className='panel';const title=document.createElement('h2');title.textContent=mode==='__income'?'Archived income and expenses':mode==='__trial'?'Archived trial balance':'Archived general ledger';const p=document.createElement('p');p.textContent='Calculated from posted journal lines contained in this file. Amounts stay in their original currencies; no exchange-rate conversion or opening-balance reconstruction is applied. This is an audit aid, not an official finalized report.';note.append(title,p);target.append(note);for(const v of values){const b=document.createElement('button');b.type='button';b.className='record';const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent=`${v.account.code} · ${v.account.name} · ${v.currency}`;small.textContent=`${v.account.account_type} · Debit ${v.debit.toLocaleString()} · Credit ${v.credit.toLocaleString()} · ${mode==='__trial'?'Balance '+Math.abs(v.debit-v.credit).toLocaleString()+' '+(v.debit>=v.credit?'debit':'credit'):'Net '+(v.debit-v.credit).toLocaleString()} · ${v.lines} lines`;b.append(strong,small);b.onclick=()=>detail('accounts',v.account);target.append(b)}$('more').hidden=true}
function field(dl,key,val){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key.replaceAll('_',' ');if(val&&typeof val==='object'){const pre=document.createElement('pre');pre.textContent=JSON.stringify(val,null,2);dd.append(pre)}else dd.textContent=display(val);dl.append(dt,dd)}
function related(body,label,items,kind){if(!items.length)return;const h=document.createElement('h3');h.textContent=`${label} (${items.length})`;body.append(h);for(const r of items){const b=document.createElement('button');b.type='button';b.className='record related';b.textContent=display(name(kind,r));b.onclick=()=>detail(kind,r);body.append(b)}}
function detail(table,row){selected={table,row};$('detailTitle').textContent=display(name(table,row));const body=$('detailBody');body.replaceChildren();const p=document.createElement('p');p.className='muted';p.textContent=`${table} · ${row.id||'record'} · All fields preserved below`;body.append(p);const dl=document.createElement('dl');for(const [k,v] of Object.entries(row))field(dl,k,v);body.append(dl);
 if(table==='operational_reports'&&row.data?.kind==='finance'){related(body,'Original budget request',all('operational_reports').filter(x=>x.id===row.data.requestId14316),'operational_reports');related(body,'Linked fund allocations',all('operational_reports').filter(x=>x.data?.requestId14316===row.id),'operational_reports')}
 if(table==='vouchers14299'){related(body,'Versions',all('voucher_versions14299').filter(x=>x.voucher_id===row.id),'voucher_versions14299');related(body,'Linked journal',all('journal_entries').filter(x=>x.id===row.journal_entry_id),'journal_entries')}
 if(table==='journal_entries'){related(body,'Vouchers',all('vouchers14299').filter(x=>x.journal_entry_id===row.id),'vouchers14299');related(body,'Journal lines',all('journal_lines').filter(x=>x.journal_entry_id===row.id),'journal_lines');related(body,'Sub-user source lines',all('staff_journal_lines').filter(x=>x.journal_entry_id===row.id),'staff_journal_lines')}
 if(table==='staff_journals')related(body,'Sub-user entries',all('staff_journal_lines').filter(x=>x.staff_journal_id===row.id),'staff_journal_lines');
 if(table==='payroll_runs')related(body,'Payroll lines',all('payroll_lines').filter(x=>x.payroll_run_id===row.id),'payroll_lines');
 if(table==='fund_adjustment_requests')related(body,'Requested adjustments',all('fund_adjustment_lines').filter(x=>x.request_id===row.id),'fund_adjustment_lines');
 if(table==='accounts'||table==='sub_accounts'){related(body,'Journal lines',all('journal_lines').filter(x=>x.account_id===row.id||x.sub_account_id===row.id),'journal_lines');if(table==='accounts')related(body,'Sub-accounts',all('sub_accounts').filter(x=>x.parent_account_id===row.id),'sub_accounts')}
 if(table==='journal_lines'){const parent=all('journal_entries').find(x=>x.id===row.journal_entry_id);if(parent)related(body,'Journal entry',[parent],'journal_entries');const acc=all('accounts').find(x=>x.id===row.account_id);if(acc)related(body,'Account',[acc],'accounts')}
 if(table==='staff_journal_lines'){const parent=all('staff_journals').find(x=>x.id===row.staff_journal_id);if(parent)related(body,'Sub-user journal',[parent],'staff_journals');const entry=all('journal_entries').find(x=>x.id===row.journal_entry_id);if(entry)related(body,'Posted journal entry',[entry],'journal_entries')}
 $('detail').hidden=false;$('detail').scrollTop=0}
$('archiveFile').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>50*1024*1024)throw Error('Choose an archive under 50 MB.');openPack(JSON.parse(await file.text()))}catch(err){pack=null;$('overview').hidden=true;$('controls').hidden=true;$('detail').hidden=true;$('navigation').replaceChildren();$('results').replaceChildren();$('status').textContent='Could not open archive: '+err.message;$('status').classList.add('error')}};
$('view').onchange=()=>{shown=50;renderRows()};$('search').oninput=()=>{shown=50;renderRows()};$('more').onclick=()=>{shown+=50;renderRows()};$('closeDetail').onclick=()=>$('detail').hidden=true;$('menu').onclick=()=>document.querySelector('.sidebar').classList.toggle('open');
window.addEventListener('message',e=>{if(e.source!==window.opener||e.origin!==location.origin||e.data?.type!=='archive-open128')return;try{openPack(e.data.pack)}catch(err){$('status').textContent=err.message;$('status').classList.add('error')}});if(window.opener&&location.protocol!=='file:')window.opener.postMessage({type:'archive-ready128'},location.origin);
})();
