/* Budget templates, shared settings, Gmail sending and copyable summaries. */
(()=>{'use strict';
const esc=v=>escapeHtml(String(v??'')),state={owner:'',templates:[],settings:null,loaded:false,job:null};
const defaults={categories:['Salaries','Rent','Utilities','Supplies','Transport','Legal papers','Other'],currency:'LAK',emails:'',whatsappMode:'group',whatsappNumber:'',groupName:'Administrators',sendingAccount:'',gmailClientId:''};
const admin=()=>!!liveProfile?.id&&liveProfile.role==='admin'&&!!window.access113?.can('transactions-budget14313');
function guard(actor=liveProfile?.id){if(!admin()||liveProfile.id!==actor)throw Error('Administrator access changed. Reopen Budget Request.');return actor}
function config(){return {...defaults,...(state.owner===liveProfile?.id?state.settings?.data:{})}}
function capture(){if(document.getElementById('financeForm82'))readFinance82();return Finance82}
function error(e){return ['42P01','PGRST205'].includes(e?.code)?Error('Install INSTALL-BUDGET-TEMPLATES-v143.13.sql in Supabase to save budget templates and settings.'):e}
async function load(force=false){const actor=guard();if(state.owner!==actor){state.owner=actor;state.loaded=false;state.templates=[];state.settings=null;state.job=null}if(state.loaded&&!force)return;if(state.job)return state.job;state.job=(async()=>{const [t,s]=await Promise.all([ojmDb.from('budget_templates14313').select('*').order('updated_at',{ascending:false}),ojmDb.from('budget_settings14313').select('*').eq('id',true).maybeSingle()]);guard(actor);if(t.error||s.error)throw error(t.error||s.error);state.templates=t.data||[];state.settings=s.data;state.loaded=true;const f=document.getElementById('financeLine82');if(f&&!f.dataset.userEdited14313){const category=f.elements.category;category.innerHTML=categoryOptions().map(([v,l])=>'<option value="'+esc(v)+'">'+esc(l)+'</option>').join('');f.elements.currency.value=config().currency}})().finally(()=>{if(state.owner===actor)state.job=null});return state.job}
async function save(table,data,record,id){const actor=guard();const payload={data,version:record?record.version+1:1,updated_at:new Date().toISOString(),updated_by:actor,...(id!==undefined?{id}:{})};const q=record?ojmDb.from(table).update(payload).eq('id',record.id).eq('version',record.version):ojmDb.from(table).insert(payload);const result=await q.select('*');guard(actor);if(result.error)throw error(result.error);if(!result.data?.length)throw Error('Changed on another device. Close, reopen, and try again.');return result.data[0]}
function categoryOptions(){return [...new Set([...config().categories,...Finance82.lines.map(l=>l.category)])].filter(Boolean).map(c=>[c,c])}
function reportView(){const rows=Work82.reports.filter(r=>r.data.kind==='finance');mount82('report-financing82','Budget & Financing Reports','Saved requests and financing breakdowns. Create and send budget requests under Transactions.',table82(['Date','Purpose','Recipient','Action'],rows.map(r=>[esc(r.data.date),esc(r.data.purpose||'Budget request'),esc(r.data.recipient),'<button type="button" onclick="budget14313.viewReport(\''+esc(r.id)+'\')">View report</button>'])))}
function viewReport(id){guard();const r=Work82.reports.find(r=>r.id===id&&r.data.kind==='finance');if(!r)return;const {root}=dialog('Budget & Financing Report',financeHtml82(r.data)+'<button type="button" data-print-budget14313>Print / PDF</button>',[{label:'Close',value:false}]);root.querySelector('[data-print-budget14313]').onclick=()=>{root.resolve108(false);print82('Budget & Financing Report',financeHtml82(r.data),r.data.date)}}
function savedReportsHtml(){return Work82.reports.filter(r=>r.data.kind==='finance').map(r=>financeHtml82(structuredClone(r.data))).join('')||'<p>No saved budget or financing reports.</p>'}
const printDraft=window.printFinance82;window.printFinance82=function(...args){if(document.querySelector('#report-financing82.active'))return print82('Budget & Financing Reports',savedReportsHtml(),'Saved reports');return printDraft(...args)};
window.renderFinance82=reportView;
function tools(){return '<button type="button" onclick="budget14313.choose()">Templates</button><button type="button" onclick="budget14313.add()">Add Template</button>'}
function settingsButton(){return '<button type="button" class="budget-settings14313" aria-label="Budget request settings" title="Budget request settings" onclick="budget14313.settings()"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6"/></svg></button>'}
function dialog(title,html,buttons=[{label:'Cancel',value:false},{label:'Save',value:true,primary:true}]){const pending=ui108.modal(title,html,buttons);const root=document.querySelector('.ui-overlay108:last-child');root.querySelector('.ui-dialog108').classList.add('budget-dialog14313');return{pending,root}}
async function add(){try{guard();const d=capture();if(!d.lines.length)throw Error('Add at least one budget item before saving a template.');const actor=liveProfile.id,snapshot=structuredClone(d);const {pending,root}=dialog('Add budget template','<label>Template name<input name="templateName" maxlength="120" required></label><p>Save the items, categories, amounts and currencies for reuse. Receipts, allocations and currency conversions are not copied.</p>');const input=root.querySelector('input');input.focus();root.addEventListener('click',e=>{if(e.target.textContent==='Save'&&!input.value.trim()){e.stopImmediatePropagation();e.preventDefault();input.reportValidity()}},true);if(!await pending)return;guard(actor);const row=await save('budget_templates14313',{name:input.value.trim(),purpose:snapshot.purpose||'',recipient:snapshot.recipient||'',reviewer:snapshot.reviewer||'',notes:snapshot.notes||'',lines:snapshot.lines.map(l=>({category:l.category,description:l.description,amount:Number(l.amount),currency:l.currency}))});state.templates.unshift(row);showCenterStatus('Budget template saved.')}catch(e){showCenterStatus(e.message,true)}}
async function choose(){try{capture();await load(true);const actor=guard(),{root}=dialog('Budget templates','<div class="budget-template-list14313">'+(state.templates.length?state.templates.map(t=>'<div><strong>'+esc(t.data.name)+'</strong><span>'+esc(t.data.lines.length)+' items</span><button type="button" data-use-template14313="'+esc(t.id)+'">Use template</button></div>').join(''):'<p>No templates yet. Add items, then choose Add Template.</p>')+'</div>',[{label:'Close',value:false}]);root.querySelectorAll('[data-use-template14313]').forEach(b=>b.onclick=async()=>{try{guard(actor);const t=state.templates.find(r=>r.id===b.dataset.useTemplate14313);if(!t)return;root.resolve108(false);if((Finance82.lines.length||Finance82.movements.length)&&!await ui117.confirm('Start a new budget request from this template? Save your current request first if needed.'))return;guard(actor);Object.assign(Finance82,{reference:'',date:today82(),mode:'request',purpose:t.data.purpose||'',recipient:t.data.recipient||'',reviewer:t.data.reviewer||'',notes:t.data.notes||'',lines:t.data.lines.map(l=>({...structuredClone(l),key117:crypto.randomUUID()})),movements:[],conversions:[]});Work82.reportRecord=null;Work82.report=null;renderWork82();showCenterStatus('Template loaded into a new budget request.')}catch(e){showCenterStatus(e.message,true)}})}catch(e){showCenterStatus(e.message,true)}}
async function settings(){
 try{
  capture();await load(true);const actor=guard(),record=state.settings,c=config(),currencies=[...new Set(['LAK',...accountDataCurrencies79(),c.currency])].filter(Boolean);
  const {pending,root}=dialog('Budget request settings','<form id="budgetSettings14313"><label>Categories · one per line<textarea name="categories" rows="5" required>'+esc(c.categories.join('\n'))+'</textarea></label><label>Default currency<select name="currency">'+currencies.map(v=>'<option value="'+esc(v)+'" '+(v===c.currency?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label><label>Email recipients · separate with commas<textarea name="emails" rows="2">'+esc(c.emails)+'</textarea></label><div><p>Gmail sender: <strong data-gmail-sender14314>Not connected</strong></p><button type="button" data-gmail-connect14314>Connect Gmail</button> <button type="button" data-gmail-disconnect14314 hidden>Disconnect</button><p data-gmail-status14314 role="status">Connect your Gmail separately from your accounting login. Emails are sent from the Google account you choose.</p></div><details '+(!c.gmailClientId?'open':'')+'><summary>Gmail connection setup</summary><label>Google OAuth client ID<input name="gmailClientId" value="'+esc(c.gmailClientId)+'" placeholder="…apps.googleusercontent.com" autocomplete="off"></label><p>Save the client ID before connecting Gmail. <a href="docs/GMAIL-SETUP-v143.14.md" target="_blank" rel="noopener">Setup instructions</a></p><p>Authorized website origin: <code>'+esc(location.origin)+'</code></p></details><label>WhatsApp / Messenger group name<input name="groupName" value="'+esc(c.groupName)+'"></label><p>Copy the category summary and paste it into your existing group chat.</p><label>Account handover note<input name="sendingAccount" value="'+esc(c.sendingAccount)+'"></label><p>Full breakdown links require an authorized accounting sign-in.</p><p role="alert"></p></form>');
  const f=root.querySelector('form'),connect=root.querySelector('[data-gmail-connect14314]'),disconnect=root.querySelector('[data-gmail-disconnect14314]'),gmailStatus=root.querySelector('[data-gmail-status14314]');let values,busy=false;
  function refresh(){const g=budgetGmail14314.status(c.gmailClientId);root.querySelector('[data-gmail-sender14314]').textContent=g.email||'Not connected';disconnect.hidden=!g.connected;connect.textContent=g.connected?'Change Gmail':'Connect Gmail';connect.disabled=busy||!budgetGmail14314.validClientId(c.gmailClientId);disconnect.disabled=busy;}
  refresh();if(budgetGmail14314.validClientId(c.gmailClientId)){connect.disabled=true;budgetGmail14314.load().then(()=>{if(root.isConnected)refresh()}).catch(e=>{gmailStatus.textContent=e.message;refresh()})}
  connect.onclick=()=>{try{guard(actor);if(f.elements.gmailClientId.value.trim()!==c.gmailClientId)throw Error('Save the Gmail setup first, then reopen Settings to connect.');busy=true;refresh();gmailStatus.textContent='Choose your Gmail in the Google connection window.';budgetGmail14314.connect(c.gmailClientId).then(()=>{guard(actor);gmailStatus.textContent='Gmail connected. You can now send budget requests from this website.'}).catch(e=>{gmailStatus.textContent=e.message}).finally(()=>{busy=false;if(root.isConnected)refresh()})}catch(e){busy=false;gmailStatus.textContent=e.message;refresh()}};
  disconnect.onclick=()=>{guard(actor);budgetGmail14314.disconnect();refresh();gmailStatus.textContent='Gmail disconnected from this page.'};
  root.addEventListener('click',e=>{if(e.target.textContent!=='Save')return;try{
   if(busy)throw Error('Finish or cancel the Gmail connection first.');
   values={...c,...Object.fromEntries(new FormData(f))};values.categories=[...new Set(values.categories.split('\n').map(x=>x.trim()).filter(Boolean))];if(!values.categories.length)throw Error('Add at least one category.');
   if(values.emails.trim())values.emails=budgetGmail14314.recipients(values.emails).join(', ');
   values.gmailClientId=values.gmailClientId.trim();if(values.gmailClientId&&!budgetGmail14314.validClientId(values.gmailClientId))throw Error('Enter a Google Web application OAuth client ID.');
  }catch(err){e.preventDefault();e.stopImmediatePropagation();f.querySelector('[role=alert]').textContent=err.message}},true);
  if(!await pending)return;guard(actor);state.settings=await save('budget_settings14313',values,record,true);if(c.gmailClientId!==values.gmailClientId)budgetGmail14314.disconnect();renderWork82();showCenterStatus('Budget settings saved for the company.');
 }catch(e){showCenterStatus(e.message,true)}
}
function texts(d,link){return budgetMessages14314.texts(d,link)}
async function send(channel){try{await budgetMessages14314.prepare(channel,{guard,load,config,dialog})}catch(e){showCenterStatus(e.message,true)}}
let opening=false,opened='';async function openLink(){const id=new URL(location.href).searchParams.get('budget');if(!id||!admin()||opening||opened===id+':'+liveProfile.id)return;if(!/^[\da-f-]{36}$/i.test(id))return;opening=true;const actor=liveProfile.id;try{const r=await ojmDb.from('operational_reports').select('*').eq('id',id).single();guard(actor);if(r.error||r.data?.data?.kind!=='finance')throw Error('This budget breakdown is unavailable or your account cannot access it.');opened=id+':'+actor;const d=r.data.data;dialog('Budget request breakdown · '+d.date,financeHtml82(d),[{label:'Close',value:false}])}catch(e){showCenterStatus(e.message,true);opened=id+':'+actor}finally{opening=false}}
window.budget14313={viewReport,savedReportsHtml,config,categoryOptions,tools,settingsButton,add,choose,settings,send,texts,load};
document.addEventListener('input',e=>{const f=e.target.closest?.('#financeLine82');if(f)f.dataset.userEdited14313='1'});
window.addEventListener('page113',()=>{if(document.querySelector('#transactions-budget14313.active')&&admin())load().catch(()=>{});openLink()});window.addEventListener('presentation-ready113',openLink);
})();
