/* Budget templates, shared settings, Gmail sending and copyable summaries. */
(()=>{'use strict';
const esc=v=>escapeHtml(String(v??'')),state={owner:'',templates:[],settings:null,loaded:false,job:null};
const defaults={categories:[],currency:'LAK',emails:'',whatsappMode:'group',whatsappNumber:'',groupName:'Administrators',sendingAccount:'',gmailClientId:'',emailSender:'',chatgptAccountEmail:'',trialEmailTo:'',trialTemplateId14319:''};
const admin=()=>!!liveProfile?.id&&liveProfile.role==='admin'&&!!window.access113?.can('transactions-budget14313');
function guard(actor=liveProfile?.id){if(!admin()||liveProfile.id!==actor)throw Error('Administrator access changed. Reopen Budget Request.');return actor}
function config(){return {...defaults,...(state.owner===liveProfile?.id?state.settings?.data:{})}}
function capture(){if(document.getElementById('financeForm82'))readFinance82();return Finance82}
function error(e){return ['42P01','PGRST205'].includes(e?.code)?Error('Install INSTALL-BUDGET-TEMPLATES-v143.13.sql in Supabase to save budget templates and settings.'):e}
async function load(force=false){const actor=guard();if(state.owner!==actor){state.owner=actor;state.loaded=false;state.templates=[];state.settings=null;state.job=null}if(state.loaded&&!force)return;if(state.job)return state.job;state.job=(async()=>{const [t,s]=await Promise.all([ojmDb.from('budget_templates14313').select('*').order('updated_at',{ascending:false}),ojmDb.from('budget_settings14313').select('*').eq('id',true).maybeSingle()]);guard(actor);if(t.error||s.error)throw error(t.error||s.error);state.templates=(t.data||[]).filter(r=>r.data.kind!=='allocation14316');state.settings=s.data;state.loaded=true;const f=document.getElementById('financeLine82');if(f&&!f.dataset.userEdited14313){const suggestions=f.querySelector('#budgetCategories14321');if(suggestions)suggestions.innerHTML=categorySuggestions();f.elements.currency.value=config().currency}})().finally(()=>{if(state.owner===actor)state.job=null});return state.job}
async function save(table,data,record,id){const actor=guard();const payload={data,version:record?record.version+1:1,updated_at:new Date().toISOString(),updated_by:actor,...(id!==undefined?{id}:{})};const q=record?ojmDb.from(table).update(payload).eq('id',record.id).eq('version',record.version):ojmDb.from(table).insert(payload);const result=await q.select('*');guard(actor);if(result.error)throw error(result.error);if(!result.data?.length)throw Error('Changed on another device. Close, reopen, and try again.');return result.data[0]}
function categoryOptions(){return [...new Set([...(Array.isArray(config().categories)?config().categories:[]),...Finance82.lines.map(l=>l.category)].map(c=>String(c??'').trim()).filter(Boolean))].map(c=>[c,c])}
function categorySuggestions(){return categoryOptions().map(([v])=>'<option value="'+esc(v)+'"></option>').join('')}
function categoryField(){return '<label>Category<input name="category" type="text" data-plain14285 list="budgetCategories14321" value="" required autocomplete="off" placeholder="Enter a budget category"><datalist id="budgetCategories14321">'+categorySuggestions()+'</datalist></label>'}
function currencyOptions(lines=Finance82.lines){return [...new Set([config().currency,...(CurrencyStore.currencies||[]).map(c=>c.code),...lines.map(l=>l.currency)].filter(Boolean))].map(c=>[c,c])}
function reportView(){const rows=Work82.reports.filter(r=>r.data.kind==='finance');mount82('report-financing82','Budget & Financing Reports','Saved requests and financing breakdowns. Create and send budget requests under Transactions.',table82(['Date','Purpose','Recipient','Action'],rows.map(r=>[esc(r.data.date),esc(r.data.purpose||'Budget request'),esc(r.data.recipient),'<button type="button" onclick="budget14313.viewReport(\''+esc(r.id)+'\')">View report</button>'])))}
function viewReport(id){guard();const r=Work82.reports.find(r=>r.id===id&&r.data.kind==='finance');if(!r)return;const {root}=dialog('Budget & Financing Report',financeHtml82(r.data)+'<button type="button" data-print-budget14313>Print / PDF</button>',[{label:'Close',value:false}]);root.querySelector('[data-print-budget14313]').onclick=()=>{root.resolve108(false);print82('Budget & Financing Report',financeHtml82(r.data),r.data.date)}}
function savedReportsHtml(){return Work82.reports.filter(r=>r.data.kind==='finance').map(r=>financeHtml82(structuredClone(r.data))).join('')||'<p>No saved budget or financing reports.</p>'}
const printDraft=window.printFinance82;window.printFinance82=function(...args){if(document.querySelector('#report-financing82.active'))return print82('Budget & Financing Reports',savedReportsHtml(),'Saved reports');return printDraft(...args)};
window.renderFinance82=reportView;
function tools(){return '<button type="button" onclick="budget14313.choose()">Templates</button><button type="button" onclick="budget14313.add()">Add Template</button>'}
function settingsButton(){return '<button type="button" class="budget-settings14313" aria-label="Budget request settings" title="Budget request settings" onclick="budget14313.settings()"><svg width="17" height="17" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" aria-hidden="true"><path d="M4 6h16M4 12h16M4 18h16M8 3v6M16 9v6M10 15v6"/></svg></button>'}
function dialog(title,html,buttons=[{label:'Cancel',value:false},{label:'Save',value:true,primary:true}]){const pending=ui108.modal(title,html,buttons);const root=document.querySelector('.ui-overlay108:last-child');root.querySelector('.ui-dialog108').classList.add('budget-dialog14313');return{pending,root}}
async function add(){try{guard();const d=capture();if(!d.lines.length)throw Error('Add at least one budget item before saving a template.');const actor=liveProfile.id,snapshot=structuredClone(d);const {pending,root}=dialog('Add budget template','<label>Template name<input name="templateName" maxlength="120" required></label><p>Save the items, categories, amounts and currencies for reuse. Receipts, allocations and currency conversions are not copied.</p>');const input=root.querySelector('input');input.focus();root.addEventListener('click',e=>{if(e.target.textContent==='Save'&&!input.value.trim()){e.stopImmediatePropagation();e.preventDefault();input.reportValidity()}},true);if(!await pending)return;guard(actor);const row=await save('budget_templates14313',{name:input.value.trim(),purpose:snapshot.purpose||'',recipient:snapshot.recipient||'',reviewer:snapshot.reviewer||'',notes:snapshot.notes||'',lines:snapshot.lines.map(l=>({category:l.category,description:l.description,amount:Number(l.amount),currency:l.currency}))});state.templates.unshift(row);showCenterStatus('Budget template saved.')}catch(e){showCenterStatus(e.message,true)}}
async function choose(){try{capture();await load(true);const actor=guard(),{root}=dialog('Budget templates','<div class="budget-template-list14313">'+(state.templates.length?state.templates.map(t=>'<div><strong>'+esc(t.data.name)+'</strong><span>'+esc(t.data.lines.length)+' items</span><button type="button" data-use-template14313="'+esc(t.id)+'">Use template</button><button type="button" data-edit-template14319="'+esc(t.id)+'">Edit Template</button></div>').join(''):'<p>No templates yet. Add items, then choose Add Template.</p>')+'</div>',[{label:'Close',value:false}]);root.querySelectorAll('[data-edit-template14319]').forEach(b=>b.onclick=()=>{root.resolve108(false);void edit(b.dataset.editTemplate14319)});root.querySelectorAll('[data-use-template14313]').forEach(b=>b.onclick=async()=>{try{guard(actor);const t=state.templates.find(r=>r.id===b.dataset.useTemplate14313);if(!t)return;root.resolve108(false);if((Finance82.lines.length||Finance82.movements.length)&&!await ui117.confirm('Start a new budget request from this template? Save your current request first if needed.'))return;guard(actor);Object.assign(Finance82,{reference:'',date:today82(),mode:'request',purpose:t.data.purpose||'',recipient:t.data.recipient||'',reviewer:t.data.reviewer||'',notes:t.data.notes||'',lines:t.data.lines.map(l=>({...structuredClone(l),key117:crypto.randomUUID()})),movements:[],conversions:[]});Work82.reportRecord=null;Work82.report=null;renderWork82();showCenterStatus('Template loaded into a new budget request.')}catch(e){showCenterStatus(e.message,true)}})}catch(e){showCenterStatus(e.message,true)}}
async function edit(id){try{
 await load(true);const actor=guard(),record=state.templates.find(t=>t.id===id);if(!record)throw Error('Template unavailable. Reopen Templates.');const original=structuredClone(record.data),currencies=currencyOptions(original.lines).map(([c])=>c);
 const row=l=>'<tr><td><input name="category" aria-label="Category" value="'+esc(l.category)+'" required></td><td><input name="description" aria-label="Description" value="'+esc(l.description)+'" required></td><td><input name="amount" aria-label="Amount" type="number" min="0.01" step="0.01" value="'+esc(l.amount)+'" required></td><td><select name="currency" aria-label="Currency">'+currencies.map(c=>'<option '+(c===l.currency?'selected':'')+'>'+esc(c)+'</option>').join('')+'</select></td><td><button type="button" data-remove-template-item14319>Remove</button></td></tr>';
 const {pending,root}=dialog('Edit budget template','<form data-template-edit14319><label>Template name<input name="name" maxlength="120" value="'+esc(original.name)+'" required></label><label>Purpose<input name="purpose" value="'+esc(original.purpose)+'"></label><label>Recipient label<input name="recipient" value="'+esc(original.recipient)+'"></label><label>Notes<textarea name="notes">'+esc(original.notes)+'</textarea></label><div class="budget-template-items14319"><table><thead><tr><th>Category</th><th>Description</th><th>Amount</th><th>Currency</th><th>Action</th></tr></thead><tbody>'+original.lines.map(row).join('')+'</tbody></table></div><button type="button" data-add-template-item14319>Add Item</button><p role="alert"></p></form>');const form=root.querySelector('form'),body=form.querySelector('tbody');let values;
 form.onclick=e=>{const remove=e.target.closest('[data-remove-template-item14319]');if(remove)remove.closest('tr').remove();if(e.target.closest('[data-add-template-item14319]'))body.insertAdjacentHTML('beforeend',row({category:'',description:'',amount:1,currency:config().currency}))};
 root.addEventListener('click',e=>{if(e.target.textContent!=='Save')return;try{if(!form.reportValidity())throw Error('Complete the template fields.');const lines=[...body.rows].map(tr=>({category:tr.querySelector('[name=category]').value.trim(),description:tr.querySelector('[name=description]').value.trim(),amount:Number(tr.querySelector('[name=amount]').value),currency:tr.querySelector('[name=currency]').value}));if(!lines.length||lines.some(l=>!l.category||!l.description||!Number.isFinite(l.amount)||l.amount<=0))throw Error('Add at least one valid item with a positive amount.');const fields=Object.fromEntries(new FormData(form));if(!fields.name.trim())throw Error('Enter a template name.');values={...original,name:fields.name.trim(),purpose:fields.purpose,recipient:fields.recipient,notes:fields.notes,lines}}catch(err){e.preventDefault();e.stopImmediatePropagation();form.querySelector('[role=alert]').textContent=err.message}},true);
 if(!await pending)return;guard(actor);const saved=await save('budget_templates14313',values,record);state.templates=state.templates.map(t=>t.id===saved.id?saved:t);showCenterStatus('Budget template saved.');
 }catch(e){showCenterStatus(e.message,true)}}

async function settings(){
 try{
  capture();await load(true);const actor=guard(),record=state.settings,c=config(),currencies=[...new Set(['LAK',...accountDataCurrencies79(),c.currency])].filter(Boolean);
  const {pending,root}=dialog('Budget request settings','<form id="budgetSettings14313"><label>Budget categories · one per line<textarea name="categories" rows="5" placeholder="Optional saved suggestions">'+esc(c.categories.join('\n'))+'</textarea></label><label>Default currency<select name="currency">'+currencies.map(v=>'<option value="'+esc(v)+'" '+(v===c.currency?'selected':'')+'>'+esc(v)+'</option>').join('')+'</select></label><label>Email recipients · separate with commas<textarea name="emails" rows="2">'+esc(c.emails)+'</textarea></label><label>Sender email<input name="emailSender" type="email" value="'+esc(c.emailSender)+'" autocomplete="off"></label><p>The company sender is shared and editable. Connect that Google account before sending.</p><div><p>Connected Gmail sender: <strong data-gmail-sender14314>Not connected</strong></p><button type="button" data-gmail-connect14314>Connect Gmail</button> <button type="button" data-gmail-disconnect14314 hidden>Disconnect</button><p data-gmail-status14314 role="status">Connect your Gmail separately from your accounting login. Emails are sent from the Google account you choose.</p></div><label>Test email recipient<input name="trialEmailTo" type="email" value="'+esc(c.trialEmailTo)+'" autocomplete="off"></label><label>Test email template<select name="trialTemplateId14319"><option value="">Choose a sample template</option>'+state.templates.map(t=>'<option value="'+esc(t.id)+'" '+(t.id===c.trialTemplateId14319?'selected':'')+'>'+esc(t.data.name)+'</option>').join('')+'</select></label><button type="button" data-gmail-test14319>Send Test Email</button><p>Test emails use the selected template and test recipient. Regular recipients stay unchanged.</p><details '+(!c.gmailClientId?'open':'')+'><summary>Gmail connection setup</summary><label>Google OAuth client ID<input name="gmailClientId" value="'+esc(c.gmailClientId)+'" placeholder="…apps.googleusercontent.com" autocomplete="off"></label><p>Save the client ID before connecting Gmail. <a href="docs/GMAIL-SETUP-v143.14.md" target="_blank" rel="noopener">Setup instructions</a></p><p>Authorized website origin: <code>'+esc(location.origin)+'</code></p></details><label>WhatsApp / Messenger group name<input name="groupName" value="'+esc(c.groupName)+'"></label><p>Copy the category summary and paste it into your existing group chat.</p><label>Account handover note<input name="sendingAccount" value="'+esc(c.sendingAccount)+'"></label><p>Full breakdown links require an authorized accounting sign-in.</p><p role="alert"></p></form>');
  const f=root.querySelector('form'),connect=root.querySelector('[data-gmail-connect14314]'),disconnect=root.querySelector('[data-gmail-disconnect14314]'),gmailStatus=root.querySelector('[data-gmail-status14314]');let values,busy=false;
  function refresh(){const g=budgetGmail14314.status(c.gmailClientId,c.emailSender);root.querySelector('[data-gmail-sender14314]').textContent=g.email||'Not connected';disconnect.hidden=!g.connected;connect.textContent=g.connected?'Change Gmail':'Connect Gmail';connect.disabled=busy||!budgetGmail14314.validClientId(c.gmailClientId);disconnect.disabled=busy;}
  refresh();if(budgetGmail14314.validClientId(c.gmailClientId)){connect.disabled=true;budgetGmail14314.load().then(()=>{if(root.isConnected)refresh()}).catch(e=>{gmailStatus.textContent=e.message;refresh()})}
  connect.onclick=()=>{try{guard(actor);if(f.elements.gmailClientId.value.trim()!==c.gmailClientId||f.elements.emailSender.value.trim().toLowerCase()!==c.emailSender)throw Error('Save the Gmail setup first, then reopen Settings to connect.');busy=true;refresh();gmailStatus.textContent='Choose your Gmail in the Google connection window.';budgetGmail14314.connect(c.gmailClientId,c.emailSender).then(()=>{guard(actor);gmailStatus.textContent='Gmail connected. You can now send budget requests from this website.'}).catch(e=>{gmailStatus.textContent=e.message}).finally(()=>{busy=false;if(root.isConnected)refresh()})}catch(e){busy=false;gmailStatus.textContent=e.message;refresh()}};
  root.querySelector('[data-gmail-test14319]').onclick=async()=>{try{guard(actor);for(const key of ['gmailClientId','emailSender','trialEmailTo','trialTemplateId14319'])if(f.elements[key].value.trim()!==c[key])throw Error('Save these settings before sending the test email.');await budgetMessages14314.trial({guard,load,config,dialog,templates:()=>state.templates})}catch(e){gmailStatus.textContent=e.message}};
  disconnect.onclick=()=>{guard(actor);budgetGmail14314.disconnect();refresh();gmailStatus.textContent='Gmail disconnected from this page.'};
  root.addEventListener('click',e=>{if(e.target.textContent!=='Save')return;try{
   if(busy)throw Error('Finish or cancel the Gmail connection first.');
   values={...c,...Object.fromEntries(new FormData(f))};values.categories=[...new Set(values.categories.split('\n').map(x=>x.trim()).filter(Boolean))];
   if(values.emails.trim())values.emails=budgetGmail14314.recipients(values.emails).join(', ');
   values.emailSender=companyAccounts14319.email(values.emailSender,'Sender');values.trialEmailTo=companyAccounts14319.email(values.trialEmailTo,'Test recipient');if(values.trialTemplateId14319&&!state.templates.some(t=>t.id===values.trialTemplateId14319))throw Error('Choose an available test template.');
   values.gmailClientId=values.gmailClientId.trim();if(values.gmailClientId&&!budgetGmail14314.validClientId(values.gmailClientId))throw Error('Enter a Google Web application OAuth client ID.');
  }catch(err){e.preventDefault();e.stopImmediatePropagation();f.querySelector('[role=alert]').textContent=err.message}},true);
  if(!await pending)return;guard(actor);state.settings=await save('budget_settings14313',values,record,true);if(c.gmailClientId!==values.gmailClientId||c.emailSender!==values.emailSender)budgetGmail14314.disconnect();renderWork82();showCenterStatus('Budget settings saved for the company.');
 }catch(e){showCenterStatus(e.message,true)}
}
function texts(d,link){return budgetMessages14314.texts(d,link)}
async function send(channel){try{await budgetMessages14314.prepare(channel,{guard,load,config,dialog})}catch(e){showCenterStatus(e.message,true)}}
let opening=false,opened='';async function openLink(){const id=new URL(location.href).searchParams.get('budget');if(!id||!admin()||opening||opened===id+':'+liveProfile.id)return;if(!/^[\da-f-]{36}$/i.test(id))return;opening=true;const actor=liveProfile.id;try{const r=await ojmDb.from('operational_reports').select('*').eq('id',id).single();guard(actor);if(r.error||r.data?.data?.kind!=='finance')throw Error('This budget breakdown is unavailable or your account cannot access it.');opened=id+':'+actor;const d=r.data.data;dialog('Budget request breakdown · '+d.date,(d.document14316?.html||financeHtml82(d)),[{label:'Close',value:false}])}catch(e){showCenterStatus(e.message,true);opened=id+':'+actor}finally{opening=false}}
window.budget14313={viewReport,savedReportsHtml,config,categoryOptions,categoryField,currencyOptions,tools,settingsButton,add,choose,edit,settings,send,texts,load};
document.addEventListener('input',e=>{const f=e.target.closest?.('#financeLine82');if(f)f.dataset.userEdited14313='1'});
window.addEventListener('page113',()=>{if(document.querySelector('#transactions-budget14313.active')&&admin())load().catch(()=>{});openLink()});window.addEventListener('presentation-ready113',openLink);
})();
