/* Semantic action colors. Navigation, profile cards and calendars keep their component designs. */
(()=>{'use strict';
const selectors=['button[type=submit]','button[type=reset]','button.je-btn','button.btn','button.primary82','button.primary113','button.doc-primary105','button.btn-action-edit','button.btn-action-delete','button.btn-icon-edit','button.custom-alert-btn','button.tx-primary','button.tx-outline','.actions82>button','.actions82>a.je-btn','.form-actions82>button','.hr-row-actions14306>button','.je-header-actions>button','.je-actions-right>button','.row-menu-panel99 button','.ui-dialog108>footer>button','.ui-dialog117>footer>button','.modal-footer>button','.doc-quick1426>button','button[data-doc-action]','.fund-tools14316>button','#fundAllocation14316 form button','#fundAllocation14316 table button','#budgetHistory14316 button','#transactions-budget14313 .work82 button','.budget-dialog14313 button','.budget-editor-actions14316>button','.data-actions14232>button','#resetFullBackup14232','#appearanceForm113>footer>button'];
const exclude='.nav-header,.tab-btn,.category-tab,[role=tab],[role=switch],[role=menuitem],.th-button,.th-user,.profile-card105,.doc-worktab1432 button,.workflow-switch14316 button,.oj-date-button104';
function semantic(b){const text=(b.getAttribute('aria-label')||b.textContent||b.title||'').trim().replace(/^[+↻✎×\s]+/,'');if(/^(delete|remove|void|reject|deactivate|discard|sign out)\b/i.test(text))return'danger';if(/^(reset|return|reopen|close year|lock|restore|clear)\b/i.test(text))return'warning';if(/template/i.test(text))return'template';if(/^(save|post|submit|approve|finalize|confirm|apply|update|finish)\b/i.test(text))return'save';if(/^(add|new|create|insert|copy|duplicate)\b/i.test(text))return'add';if(/^(print|download|export|send|whatsapp)\b/i.test(text))return'output';return'neutral'}
function decorate(){if(innerWidth<=640&&document.documentElement.dataset.device132!=='desktop')return;for(const b of document.querySelectorAll(selectors.join(','))){if(b.matches(exclude)||b.closest('#appSidebar,#categoryTabs,.hr-month-grid14306,.attendance-calendar'))continue;const value=semantic(b);if(b.dataset.actionTone14317!==value)b.dataset.actionTone14317=value}}
let queued=false;const schedule=()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})};
function ready(){decorate();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});window.addEventListener('page113',schedule);window.addEventListener('resize',schedule);window.actionControls14317={decorate,semantic}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
