/* Per-user device drafts. These are recovery copies, never automatic ledger or payroll submissions. */
(()=>{'use strict';
const prefix='ojm_unsaved1427:'+String(window.OJM_SUPABASE_URL||location.origin)+':',selector='input,select,textarea';let owner='',state={forms:{}},restoring=false,writing=false,timer,observed=new WeakMap(),ignoredForms=new WeakSet(),queued=false,warned=false;
const user=()=>typeof liveProfile!=='undefined'?liveProfile?.id||'':'';
function read(id){try{return JSON.parse(localStorage.getItem(prefix+id))||{forms:{}}}catch{return {forms:{}}}}
function persist(){if(!owner)return;try{localStorage.setItem(prefix+owner,JSON.stringify(state));warned=false}catch(e){if(!warned){warned=true;showCenterStatus('Device draft storage is full or unavailable. Save or export your unfinished work before leaving.',true)}}}
function allowed(n){if(window.personalJournal1437?.active&&n.closest?.('#journalEntry98'))return false;return n.isConnected&&n.matches?.(selector)&&!n.disabled&&!n.readOnly&&!['password','file','hidden','submit','button','reset'].includes(n.type)&&!/(password|secret|token|verify|recovery)/i.test(n.name+' '+n.id)&&!n.closest('#loginGate,#settings-recovery113,#modalUserAccess,#modalAccessPicker,#document-editor105,.ui-overlay108,.auth-settings105')}
function context(n){const form=n.closest('form'),panel=n.closest('.tab-content'),modal=n.closest('.modal-backdrop');if(!panel&&!modal)return null;const id=form?.id||form?.dataset.settingsGroup||modal?.id||panel?.id;if(!id)return null;let record='';if(form?.id==='employeeForm82'){record=form.dataset.draftRecord1427||(Work82.employee?.id||'new');form.dataset.draftRecord1427=record;}else if(/runMeta/.test(id))record=Work82.run?.month||'';else if(panel?.id==='sub-users-workspace')record=typeof activeSubUserId!=='undefined'?activeSubUserId||'':'';else if(form){record=[...form.querySelectorAll('input[type=hidden]')].filter(x=>/(^id$|recordId|editId|employeeId)/i.test(x.name||x.id)).map(x=>x.value).join(':')}
return {key:(panel?.id||modal?.id||'')+'|'+id+'|'+record,root:form||modal||panel,panel:panel?.id||'',id,record}}
function fieldKey(n,root){if(n.id)return '#'+n.id;const base=n.name?'name:'+n.name:n.dataset.row95!==undefined?'pay:'+n.dataset.row95+':'+n.dataset.field95:n.dataset.attRow95!==undefined?'attendance:'+n.dataset.attRow95+':'+n.dataset.date95:null;if(!base)return null;const same=[...root.querySelectorAll(selector)].filter(x=>x.name===n.name&&x.type===n.type);return base+(n.type==='radio'?':'+n.value:same.length>1?':'+same.indexOf(n):'')}
function value(n){return n.type==='checkbox'||n.type==='radio'?n.checked:n.multiple?[...n.selectedOptions].map(o=>o.value):n.value}
function set(n,v){if(n.type==='checkbox'||n.type==='radio')n.checked=!!v;else if(n.multiple&&Array.isArray(v))[...n.options].forEach(o=>o.selected=v.includes(o.value));else n.value=v??''}
function ownerReady(){const id=user();if(!id)return false;if(owner===id)return true;const previous=owner;owner=id;state=read(id);state.forms||={};observed=new WeakMap();if(previous){for(const n of document.querySelectorAll(selector))if(allowed(n)&&context(n))set(n,n.type==='checkbox'||n.type==='radio'?n.defaultChecked:n.defaultValue??'')}
restoring=true;try{if(previous){Work82.employee=null;Work82.run=null;Work82.runRecord=null;window.payroll95?.restoreDraftState1427?.({open:{},drafts:{},leaveOpen:false,leaveDirty:false,leaveDraft:null},id);if(typeof resetJournalLinesForm==='function')resetJournalLinesForm()}restoreModels();}finally{restoring=false}return true}
function snapshotModels(){if(!owner||owner!==user()||restoring)return;const employee=document.getElementById('employeeForm82');if(employee&&Work82.employee&&(employee.dataset.draftRecord1427||'new')===(Work82.employee.id||'new')&&Object.keys(state.forms).some(k=>k.includes('|employeeForm82|'))){const data={...(Work82.employee.data||{})};for(const n of employee.querySelectorAll(selector))if(allowed(n)&&n.name)data[n.name]=value(n);Work82.employee={...Work82.employee,data};state.employee=structuredClone(Work82.employee)}
if(typeof Work82!=='undefined'&&Work82.owner===owner){if(Work82.run?.status==='draft')state.run={run:structuredClone(Work82.run),record:structuredClone(Work82.runRecord)};else delete state.run;state.payrollUI=window.payroll95?.draftState1427?.()}
if(typeof Finance82!=='undefined'&&Object.keys(state.forms).some(k=>k.includes('finance')))state.finance=structuredClone(Finance82);
if(typeof workspacePendingRows!=='undefined')state.workspace={pending:structuredClone(workspacePendingRows),edits:structuredClone(workspaceRowEdits)};
const lines=document.getElementById('jeLinesBody');if(lines&&!window.personalJournal1437?.active&&Object.keys(state.forms).some(k=>k.startsWith('journal|')))state.journal={...snapshotJournal69(),editing:JournalModule.editingEntryId,pendingLines:JournalModule.pendingLines,mode14232:window.entry1430?.mode,single14232:window.entry1430?.read(),retained14232:window.entry1430?.retained};
state.view=document.querySelector('.tab-content.active')?.id||state.view;state.scroll=typeof appWorkspaceScroller==='function'?appWorkspaceScroller()?.scrollTop||0:0;state.updatedAt=Date.now();}
function restoreModels(){if(!owner||owner!==user())return;if(typeof Work82!=='undefined'){if(state.employee)Work82.employee=structuredClone(state.employee);if(state.run){Work82.run=structuredClone(state.run.run);Work82.runRecord=structuredClone(state.run.record)}Work82.owner=owner;window.payroll95?.restoreDraftState1427?.(state.payrollUI,owner)}if(state.finance&&typeof Finance82!=='undefined')Object.assign(Finance82,structuredClone(state.finance));if(typeof workspacePendingRows!=='undefined'){for(const k of Object.keys(workspacePendingRows))delete workspacePendingRows[k];for(const k of Object.keys(workspaceRowEdits))delete workspaceRowEdits[k];Object.assign(workspacePendingRows,state.workspace?.pending||{});Object.assign(workspaceRowEdits,state.workspace?.edits||{})}if(state.journal&&document.getElementById('jeLinesBody')){if(state.journal.mode14232)window.entry1430?.restore('double',[]);restoreJournal69(state.journal);if(state.journal.mode14232)window.entry1430?.restore(state.journal.mode14232,state.journal.single14232,state.journal.retained14232);JournalModule.editingEntryId=state.journal.editing;JournalModule.pendingLines=state.journal.pendingLines}}
function capture(n){if(restoring||!allowed(n)||!ownerReady())return;const c=context(n);if(!c||ignoredForms.has(c.root))return;const entry=state.forms[c.key]||{fields:{},panel:c.panel,id:c.id,record:c.record};for(const x of c.root.querySelectorAll(selector)){if(!allowed(x))continue;const key=fieldKey(x,c.root);if(key)entry.fields[key]=value(x);observed.set(x,c.key)}entry.updatedAt=Date.now();state.forms[c.key]=entry;snapshotModels();persist();}
function restoreFields(){if(restoring||!ownerReady())return;restoring=true;try{for(const n of document.querySelectorAll(selector)){if(!allowed(n))continue;const c=context(n);if(!c||observed.get(n)===c.key)continue;const key=fieldKey(n,c.root),entry=state.forms[c.key];if(key&&entry&&Object.hasOwn(entry.fields,key))set(n,entry.fields[key]);observed.set(n,c.key)}}finally{restoring=false}}
function flush(){clearTimeout(timer);if(owner!==user()||!owner)return;snapshotModels();persist()}
function forget(id,record){if(!ownerReady())return;for(const n of document.querySelectorAll(selector)){const c=context(n);if(c&&c.id===id&&(record===undefined||c.record===record))ignoredForms.add(c.root)}for(const [key,entry] of Object.entries(state.forms))if(entry.id===id&&(record===undefined||entry.record===record))delete state.forms[key];if(id==='employeeForm82')delete state.employee;persist()}
function scheduleRestore(){if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;restoreFields()})}
function ready(){document.addEventListener('input',e=>{const c=context(e.target);if(e.isTrusted&&c)ignoredForms.delete(c.root);capture(e.target);queueMicrotask(()=>{snapshotModels();persist()})});document.addEventListener('change',e=>{capture(e.target);queueMicrotask(()=>{snapshotModels();persist()})});document.addEventListener('reset',e=>{const n=e.target.querySelector(selector),c=n&&context(n);if(c)forget(c.id,c.record)});
document.addEventListener('change',async e=>{const n=e.target;if(n.name!=='photoFile'||!n.closest('#employeeForm82')||!n.files?.[0]||!ownerReady())return;const id=owner,file=n.files[0];if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>8*1024*1024)return;try{const bitmap=await createImageBitmap(file),canvas=document.createElement('canvas'),scale=Math.min(1,320/Math.max(bitmap.width,bitmap.height));canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();if(id!==user()||!Work82.employee)return;Work82.employee.data={...(Work82.employee.data||{}),photoData:canvas.toDataURL('image/jpeg',.82)};capture(n.closest('form').querySelector('[name=name]'));state.employee=structuredClone(Work82.employee);persist()}catch{showCenterStatus('The employee photo could not be kept in the device draft. Save the employee before leaving.',true)}});
// Capture before the existing renderers replace fields, then restore into their new controls.
const render=window.renderWork82;window.renderWork82=function(...args){if(ownerReady())snapshotModels();const result=render.apply(this,args);restoreFields();return result};
const hydrate=window.hydrateSupabaseSession;window.hydrateSupabaseSession=async function(session){flush();const result=await hydrate.apply(this,arguments);if(user()&&user()===session?.user?.id){ownerReady();restoring=true;try{restoreModels()}finally{restoring=false}if(state.view&&(Object.keys(state.forms).length||state.employee||state.run||state.journal||Object.values(state.workspace?.pending||{}).some(rows=>rows.length))&&document.getElementById(state.view)&&canAccessAppTarget(state.view))switchTab(state.view);renderWork82();restoreFields();requestAnimationFrame(()=>{if(appWorkspaceScroller())appWorkspaceScroller().scrollTop=state.scroll||0})}return result};
const logout=window.logoutDemoUser;window.logoutDemoUser=function(...args){flush();return logout.apply(this,args)};
const sw=window.switchTab;window.switchTab=function(...args){flush();const result=sw.apply(this,args);restoreFields();return result};
const save=window.saveWork82;window.saveWork82=async function(kind,data,record){const result=await save.apply(this,arguments);if(kind==='employees'){forget('employeeForm82',record?.id||'new');delete state.employee}else if(kind==='leaves')forget('leaveForm82');else if(kind==='runs'){forget('runMeta95',data.month);forget('runMeta82',data.month);delete state.run}else if(kind==='reports'){forget('financeForm82');forget('subReportForm82');delete state.finance}persist();return result};
const reset=window.resetJournalLinesForm;window.resetJournalLinesForm=function(...args){if(owner&&owner===user()&&!restoring){for(const [k,e] of Object.entries(state.forms))if(e.panel==='journal')delete state.forms[k];delete state.journal;persist()}return reset.apply(this,args)};
const saveSettings=window.saveSettingsGroup;window.saveSettingsGroup=async function(event){const form=event.currentTarget,group=form.dataset.settingsGroup;const result=await saveSettings.apply(this,arguments);if(Object.entries(collectSettingsForm(form)).every(([k,v])=>String(ApplicationSettings[group]?.[k])===String(v)))forget(form.id||group);return result};document.querySelectorAll('form[data-settings-group]').forEach(f=>f.onsubmit=window.saveSettingsGroup);
// Keep Cancel/New Employee separate from successful saving: an abandoned draft can be resumed.
const openEmployee=window.openEmployee82;window.openEmployee82=function(id=''){ownerReady();const entry=state.forms['payroll-employees|employeeForm82|'+(id||'new')];const result=openEmployee.apply(this,arguments);if(entry)restoreFields();return result};
new MutationObserver(scheduleRestore).observe(document.body,{childList:true,subtree:true});window.addEventListener('pagehide',flush);window.addEventListener('beforeunload',flush);document.addEventListener('visibilitychange',()=>{if(document.hidden)flush();else restoreFields()});window.addEventListener('focus',restoreFields);
window.drafts1427={flush,restore:()=>{ownerReady();restoreModels();renderWork82();restoreFields()},forget};restoreFields();
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
