/* v117: shared presentation, banner controls, linked menu navigation and costing. */
(function(){'use strict';
const $=s=>document.querySelector(s),esc=v=>shell113.esc(v),fmt=v=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(Number(v)||0);
window.ui117={confirm:message=>ui108.modal('Please confirm',`<p>${esc(message)}</p>`,[{label:'Cancel',value:false},{label:'Confirm',value:true}]),prompt:(message,value='')=>{const result=ui108.modal('Enter details',`<label>${esc(message)}<input id="prompt117" value="${esc(value)}" style="display:block;width:100%;margin-top:10px"></label>`,[{label:'Cancel',value:null},{label:'Continue',value:true}]);const root=$('.ui-overlay108:last-child'),input=root.querySelector('input');input.focus();root.querySelector('[data-value]');const resolve=root.resolve108;root.resolve108=v=>resolve(v?input.value:null);return result.then(v=>v===true?input.value:null)}};
function badge(v,type){return `<span class="balance-type117"><b title="Closing balance side">${v>0?'DR':v<0?'CR':'—'}</b>${esc(type||'Unclassified')}</span>`}
function accountName(r){return `<span class="account-name117"><span class="currency-symbol-badge" title="${esc(r.currency)}">${esc(currencySymbolV6(r.currency))}</span><button class="account-link69" onclick="openIndividualLedger69('${encodeURIComponent(r.key)}')">${esc(r.account.name)}</button></span>`}
window.trialHtml69=rows=>[...new Set(rows.map(r=>r.currency))].map(currency=>{const group=rows.filter(r=>r.currency===currency&&(r.opening||r.debit||r.credit)),t=totals69(group)[currency]||{dr:0,cr:0};return `<section class="report-group69"><h4>${esc(currency)} · Trial Balance · ${trialRangeLabel87()}</h4><div class="table-container"><table><thead><tr>${['Account','Type','Opening','Period DR','Period CR','Closing DR','Closing CR'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${group.map(r=>`<tr><td>${accountName(r)}</td><td>${badge(r.closing,r.account.type)}</td><td title="Opening debit less credit">${money69(r.opening)}</td><td>${money69(r.debit)}</td><td>${money69(r.credit)}</td><td>${money69(Math.max(0,r.closing))}</td><td>${money69(Math.max(0,-r.closing))}</td></tr>`).join('')}<tr class="report-total69"><td colspan="5">Closing totals</td><td>${money69(t.dr)}</td><td>${money69(t.cr)}</td></tr></tbody></table></div></section>`}).join('');
window.balancesHtml69=rows=>`<div class="table-container"><table><thead><tr>${['Account','Type','Opening','Period DR','Period CR','Closing','Last Activity'].map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr><td>${accountName(r)}</td><td>${badge(r.closing,r.account.type)}</td><td title="Opening debit less credit">${money69(r.opening)}</td><td>${money69(r.debit)}</td><td>${money69(r.credit)}</td><td>${money69(Math.abs(r.closing))}</td><td>${r.lines.length?formatAppDate(r.lines.at(-1).date):'—'}</td></tr>`).join('')||'<tr><td colspan="7">No accounts.</td></tr>'}</tbody></table></div>`;
function selectedAppearance(){const f=$('#appearanceForm113');return f?{area:f.elements.area.value,key:f.elements.area.value+(f.elements.tab.value?':'+f.elements.tab.value:'')}:null}
function bannerKey(node){if(node.classList.contains('dash-hero112'))return 'dashboard:dashboard-'+($('#dashboard [data-tab112][aria-selected=true]')?.dataset.tab112?.toLowerCase()||'home');const root=node.closest('.tab-content'),area=shell113.area(root);return area+':'+(area==='accounts'&&root.id==='accounts-modular-container'?(document.querySelector('#nav-module-accounts .tab-btn.active')?.getAttribute('onclick')||'').match(/scrollToAccountModule\('([^']+)'\)/)?.[1]||root.id:root.id)}
function quoteData(key){const area=key.split(':')[0];return {...(shell113.state.rows[area]||{}),...(shell113.state.rows[key]||{})}}
function setStyle(n,k,v){if(n.style.getPropertyValue(k)!==v)n.style.setProperty(k,v)}
function paintQuote(q,b,d,style){setStyle(q,'--quote-font',`"${style.font||'Caveat Brush'}"`);setStyle(q,'--quote-color',style.color||'#503b25');setStyle(q,'--quote-angle',(Number(d.quoteAngle??-12))+'deg');setStyle(q,'--quote-x',(d.quoteX??68)+'%');setStyle(q,'--quote-y',(d.quoteY??52)+'%');
 // Clamp the rotated lettering using its actual visible bounds.
 const box=b.getBoundingClientRect();if(!box.width)return;const controls=b.querySelector('.dash-hero-controls112'),topEdge=controls?Math.max(box.top+5,controls.getBoundingClientRect().bottom+10):box.top+5,availableHeight=Math.max(25,box.bottom-5-topEdge);let size=Math.min(27,Math.max(16,box.width*.025));q.style.setProperty('font-size',size+'px','important');let rect=q.getBoundingClientRect();while(size>10&&(rect.height>availableHeight||rect.width>box.width-12)){size--;q.style.setProperty('font-size',size+'px','important');rect=q.getBoundingClientRect()}if(!rect.width)return;let dx=rect.left<box.left+5?box.left+5-rect.left:rect.right>box.right-5?box.right-5-rect.right:0,dy=rect.top<topEdge?topEdge-rect.top:rect.bottom>box.bottom-5?box.bottom-5-rect.bottom:0;if(dx)setStyle(q,'--quote-x',((d.quoteX??68)+dx/box.width*100)+'%');if(dy)setStyle(q,'--quote-y',((d.quoteY??52)+dy/box.height*100)+'%')}
function quotations(){const style=shell113.state.rows['quotation-style117']||{};document.querySelectorAll('.area-banner113,.dash-hero112').forEach(b=>{const q=b.querySelector('blockquote');if(!q)return;const key=bannerKey(b);paintQuote(q,b,quoteData(key),style);if(q.hasAttribute('data-draggable117')||!shell113.admin())return;q.dataset.draggable117='1';q.title='Drag quotation within the banner; use Banners & Quotations to rotate it';q.onpointerdown=e=>{if(!shell113.admin())return;e.preventDefault();const key=bannerKey(b),style=shell113.state.rows['quotation-style117']||{},d=quoteData(key),box=b.getBoundingClientRect(),startX=e.clientX,startY=e.clientY,x=parseFloat(q.style.getPropertyValue('--quote-x'))||68,y=parseFloat(q.style.getPropertyValue('--quote-y'))||52;q.setPointerCapture(e.pointerId);q.onpointermove=ev=>{d.quoteX=x+(ev.clientX-startX)/box.width*100;d.quoteY=y+(ev.clientY-startY)/box.height*100;paintQuote(q,b,d,style)};q.onpointerup=async()=>{q.onpointermove=null;q.onpointerup=null;try{await shell113.save(key,{...(shell113.state.rows[key]||{}),quoteX:parseFloat(q.style.getPropertyValue('--quote-x')),quoteY:parseFloat(q.style.getPropertyValue('--quote-y'))})}catch(err){showCenterStatus(err.message,true)}};q.onpointercancel=()=>{q.onpointermove=null;paintQuote(q,b,quoteData(key),style)}}});}
function quoteSettings(){const f=$('#appearanceForm113');if(!f)return;if(f.querySelector('.quote-controls117')){f.preview117?.();return;}const box=document.createElement('section');box.className='quote-controls117';box.innerHTML=`<h3>Quotation lettering</h3><div class="fields117"><label>Font · all banners<select name="quoteFont117">${['Caveat Brush','Kalam','Permanent Marker'].map(x=>`<option>${x}</option>`).join('')}</select></label><label>Color · all banners<select name="quoteColor117"><option value="#503b25">Warm brown</option><option value="#174c38">Forest green</option><option value="#914511">Oon Jai brown</option><option value="#fff7df">Warm ivory</option></select></label><label>Rotation<input name="quoteAngle117" type="range" min="-30" max="30" value="-12"></label><label>Horizontal position<input name="quoteX117" type="range" min="0" max="90" value="68"></label><label>Vertical position<input name="quoteY117" type="range" min="0" max="85" value="52"></label></div><button type="button" data-save-quote117>Save quotation style</button><p role="status" data-quote-status117></p>`;f.querySelector('footer').before(box);const paint=()=>{const d=quoteData(selectedAppearance().key),s=shell113.state.rows['quotation-style117']||{};f.elements.quoteFont117.value=s.font||'Caveat Brush';f.elements.quoteColor117.value=s.color||'#503b25';for(const [field,key,defaultValue] of [['quoteAngle117','quoteAngle',-12],['quoteX117','quoteX',68],['quoteY117','quoteY',52]])f.elements[field].value=d[key]??defaultValue};f.elements.area.addEventListener('change',paint);f.elements.tab.addEventListener('change',paint);paint();
 const preview=()=>{const p=f.querySelector('.banner-preview113');let q=p.querySelector('blockquote');if(!q){q=document.createElement('blockquote');p.replaceChildren(q)}if(q.textContent!==f.elements.quote.value)q.textContent=f.elements.quote.value;paintQuote(q,p,{quoteAngle:Number(f.elements.quoteAngle117.value),quoteX:Number(f.elements.quoteX117.value),quoteY:Number(f.elements.quoteY117.value)},{font:f.elements.quoteFont117.value,color:f.elements.quoteColor117.value})};f.preview117=preview;box.addEventListener('input',preview);f.addEventListener('input',()=>requestAnimationFrame(preview));f.addEventListener('change',()=>requestAnimationFrame(preview));f.querySelector('[data-default113]').addEventListener('click',()=>requestAnimationFrame(preview));requestAnimationFrame(preview);box.querySelector('button').onclick=async()=>{const out=box.querySelector('[role=status]'),key=selectedAppearance().key;try{await shell113.save('quotation-style117',{font:f.elements.quoteFont117.value,color:f.elements.quoteColor117.value});await shell113.save(key,{...(shell113.state.rows[key]||{}),quoteAngle:Number(f.elements.quoteAngle117.value),quoteX:Number(f.elements.quoteX117.value),quoteY:Number(f.elements.quoteY117.value)});out.textContent='Quotation style saved.';quotations()}catch(e){out.textContent=e.message}};
}
function tidy(){const active=$('.tab-content.active');if(!active)return;
 document.querySelectorAll('.row-menu-panel99 button').forEach(b=>{const fn=b.getAttribute('onclick')||'',label=(b.title||b.getAttribute('aria-label')||b.textContent).trim();if(/openEditAccount|editSubAccount|openEmployee82|editSystemAccount/.test(fn)||/^edit$/i.test(label)){if(b.textContent!=='Edit')b.textContent='Edit'}else if(/delete|remove/i.test(label)||/delete|remove/i.test(fn)&&b.textContent.trim().length<=2){if(b.textContent!=='Delete')b.textContent='Delete';b.classList.add('danger117')}});
 document.querySelectorAll('button[data-dismiss],button[aria-label="Close"],button.modal-close-x,.pay-dialog95 header button,.ui-dialog108>header>button').forEach(b=>{if(!/close|×|✕|x/i.test((b.getAttribute('aria-label')||'')+b.textContent)&&!b.hasAttribute('data-dismiss'))return;if(b.textContent!=='×')b.textContent='×';b.classList.add('close117');b.setAttribute('aria-label','Close')});
 document.querySelectorAll('.modal-backdrop,.pay-overlay95,.submission-compare-overlay').forEach(root=>{const close=root.querySelector('header .close117,.modal-header .close117');if(close)root.querySelectorAll('footer button,.modal-footer button').forEach(b=>{if(/^close$/i.test(b.textContent.trim()))b.hidden=true})});
 active.querySelectorAll('button').forEach(b=>{if(b.textContent.trim()==='*')b.classList.add('asterisk117')});
 active.querySelectorAll('label').forEach(l=>{for(const n of l.childNodes)if(n.nodeType===3&&/Main Entry Number Digits/i.test(n.textContent))n.textContent=n.textContent.replace(/Main Entry Number Digits/ig,'Main Entry Number')});
 active.querySelectorAll('select').forEach(s=>{if(s.multiple||s.closest('#document-editor105')||s.closest('.attendance-table95'))return;const longest=Math.max(...[...s.options].map(o=>o.textContent.trim().length),8);const size=Math.min(31,longest+5)+'ch';if(s.style.width!==size)s.style.width=size;s.style.maxWidth='100%'});
 // Keep the compact workflow navigation; one canonical Recipes tab.
 const duplicate=$('#nav-module-menu [onclick*="menu-details"]');if(duplicate)duplicate.hidden=true;
 document.querySelectorAll('#categoryTabs [onclick*="menu-details"]').forEach(n=>n.hidden=true);
 document.querySelectorAll('#nav-module-menu [onclick*="menu-recipe"],#categoryTabs [onclick*="menu-recipe"]').forEach(n=>{if(n.textContent.trim()!=='Recipes')n.textContent='Recipes'});
 quoteSettings();quotations();
}
const M=window.menuStore108,oldView=window.menuView108;
window.menuView108=function(view){if(view!=='menu-costing')return oldView(view);return M.card('Costing & Promotions',`<p>Try a price or discount to see its ingredient margin. Apply a price only when you are ready.</p><div class="costing117">${M.table(['Product','Ingredient cost','Current price','Try price / discount','Result','Action'],M.state.menu.map(r=>{const c=M.cost(r.data);return [`<button class="im-link117" data-jump117="recipe" data-id="${esc(r.id)}">${esc(r.data.name)}</button>`,c.missing||c.mixed?'Incomplete':fmt(c.amount)+' '+esc(r.data.currency),fmt(r.data.price),`<div class="scenario117" data-cost117="${esc(r.id)}"><input type="number" min="0" step="any" aria-label="Trial price for ${esc(r.data.name)}" data-price117 value="${Number(r.data.price)||0}"><input type="number" min="0" max="100" step="any" aria-label="Discount percentage" data-discount117 value="0"><span>% off</span></div>`,`<output data-cost-result117="${esc(r.id)}"></output>`,`<button data-apply-price117="${esc(r.id)}">Apply price</button><button data-m108="promotion" data-id="${esc(r.id)}">Promotion</button>`]}))}</div>`,M.btn('Create bundle','new-bundle'))};
function costResult(container,changed){const id=container.dataset.cost117,r=M.state.menu.find(r=>r.id===id);if(!r)return;const price=container.querySelector('[data-price117]'),discount=container.querySelector('[data-discount117]'),base=Number(r.data.price)||0;if(changed===discount)price.value=(base*(1-Number(discount.value)/100)).toFixed(2);else if(changed===price)discount.value=base?((1-Number(price.value)/base)*100).toFixed(2):'0';const p=Number(price.value),c=M.cost(r.data),out=document.querySelector('[data-cost-result117="'+CSS.escape(id)+'"]');if(out){const text=c.missing||c.mixed?'Complete the recipe cost first.':`${fmt(p-c.amount)} ${r.data.currency} contribution · ${p>0?fmt((p-c.amount)/p*100)+'%':'—'} margin`;if(out.textContent!==text)out.textContent=text}}
document.addEventListener('input',e=>{const box=e.target.closest('[data-cost117]');if(box)costResult(box,e.target)});
document.addEventListener('click',async e=>{const link=e.target.closest('[data-jump117]');if(link){const kind=link.dataset.jump117,id=link.dataset.id;switchTab(kind==='ingredient'?'menu-ingredients':'menu-recipe');requestAnimationFrame(()=>{const target=document.querySelector(`[data-${kind==='ingredient'?'ingredient':'menu'}117="${CSS.escape(id)}"]`),row=kind==='ingredient'?target?.closest('tr'):target;if(row){if(row.tagName==='DETAILS')row.open=true;row.classList.add('im-highlight117');row.scrollIntoView({block:'center',behavior:'smooth'});setTimeout(()=>row.classList.remove('im-highlight117'),5000)}})}const apply=e.target.closest('[data-apply-price117]');if(apply){const r=M.state.menu.find(r=>r.id===apply.dataset.applyPrice117),input=document.querySelector(`[data-cost117="${CSS.escape(r.id)}"] [data-price117]`),price=Number(input.value);if(!Number.isFinite(price)||price<=0)return showCenterStatus('Enter a positive selling price.',true);if(await ui117.confirm(`Apply ${fmt(price)} ${r.data.currency} as the selling price for ${r.data.name}?`)){try{await M.save('menu',{...r.data,price},r)}catch(err){showCenterStatus(err.message,true)}}}});
document.addEventListener('pointerdown',e=>{const root=e.target;if(!(root instanceof Element)||!root.matches('.modal-backdrop,.pay-overlay95,.submission-compare-overlay,.workspace-cell-overlay')||root.id==='modalRecurringWarnings'||root.dataset.strictOutsideClose97)return;const close=root.querySelector('header button[aria-label^=Close],header button.close117,.modal-header button.modal-close-x,header button[onclick*=remove]');if(close){e.preventDefault();close.click()}else if(root.classList.contains('modal-backdrop'))closeModal(root.id)});
let pending=false;function schedule(){if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;tidy();document.querySelectorAll('[data-cost117]').forEach(n=>costResult(n))})}
function ready(){document.title='Oon Jai Accounting';const sw=window.switchTab;window.switchTab=function(id,...args){return sw.call(this,id==='menu-details'?'menu-recipe':id,...args)};new MutationObserver(schedule).observe(document.querySelector('.workspace-scroll')||document.body,{childList:true,subtree:true});new MutationObserver(schedule).observe(document.body,{childList:true});window.addEventListener('page113',schedule);window.addEventListener('presentation-ready113',schedule);schedule()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
