/* Consolidated feedback and tablet navigation; preserve existing save semantics. */
(function(){'use strict';
let timer;const $=s=>document.querySelector(s);const noticeQueue1440=[];
function notify(message,error=false,pending=false,queued=false){
 const text=String(message||'');let n=$('#status118');
 if(!n){n=document.createElement('div');n.id='status118';n.innerHTML='<span class="status-motion118" aria-hidden="true"></span><span class="status-copy118"></span><button type="button" class="status-close1440" aria-label="Close notification">Close</button>';document.body.append(n);
 n.querySelector('button').onclick=()=>{clearTimeout(timer);n.hidden=true;n.dataset.persistent1440='';const next=noticeQueue1440.shift();if(next)notify(...next,true)};
 n.addEventListener('keydown',e=>{if(e.key==='Escape'){e.stopPropagation();n.querySelector('button').click()}});}
 if(!queued&&!n.hidden&&n.dataset.persistent1440==='true'&&text&&n.querySelector('.status-copy118').textContent!==text){if(!noticeQueue1440.some(x=>x[0]===text))noticeQueue1440.push([text,error,pending]);return;}
 clearTimeout(timer);$('#centerStatusToast')?.remove();const persistent=!pending&&(error||text.length>140||text.includes('\n'));
 n.className=(error?'error ':'')+(pending?'pending':'');n.dataset.persistent1440=String(persistent);n.setAttribute('role',error?'alert':'status');n.setAttribute('aria-live',error?'assertive':'polite');n.querySelector('.status-copy118').textContent=text;n.querySelector('.status-motion118').textContent=pending?'':error?'!':'✓';n.querySelector('button').hidden=!persistent;n.hidden=!text;
 if(!pending&&!persistent)timer=setTimeout(()=>{n.hidden=true;const next=noticeQueue1440.shift();if(next)notify(...next,true)},4500);
}
window.status118={pending:m=>notify(m,false,true),done:m=>notify(m),error:m=>notify(m,true)};window.showCenterStatus=(message,error=false)=>notify(message,error);window.showAppNotification=(title,message,error=false)=>typeof message==='string'?notify(title+': '+message,error):notify(title,Boolean(message));
const seen=new WeakMap();let queued=false;let toggle;
function viewport(){const v=window.visualViewport,root=document.documentElement;root.style.setProperty('--view-left118',(v?.offsetLeft||0)+'px');root.style.setProperty('--view-top118',(v?.offsetTop||0)+'px');root.style.setProperty('--view-width118',(v?.width||innerWidth)+'px');root.style.setProperty('--view-height118',(v?.height||innerHeight)+'px');root.style.setProperty('--view-center-x118',((v?.offsetLeft||0)+(v?.width||innerWidth)/2)+'px');root.style.setProperty('--view-center-y118',((v?.offsetTop||0)+(v?.height||innerHeight)/2)+'px')}
function close(){document.body.classList.remove('nav118','tablet-nav-open99','nav-drawer-open');$('#appSidebar')?.classList.remove('mobile-open');toggle?.setAttribute('aria-expanded','false')}
function tablet(){const touch=navigator.maxTouchPoints>1||matchMedia('(pointer:coarse)').matches;const yes=touch&&Math.min(screen.width,screen.height)>=600;document.body.classList.toggle('tablet118',yes);if(!yes){close();return}const portrait=innerHeight>innerWidth;document.body.classList.toggle('tablet-portrait117',portrait);
// A tablet uses the same CSS layout viewport as a small laptop. Safari scales it
// to the screen; pinch zoom remains available. No mobile alternate table layout.
const meta=$('meta[name=viewport]');if(meta&&document.documentElement.dataset.device132!=='tablet'&&meta.content.includes('width=1280'))meta.content='width=device-width, initial-scale=1.0, maximum-scale=5.0';
placeToggle();}
function placeToggle(){if(!toggle)return;const active=$('.tab-content.active');const target=active?.id==='dashboard'?$('#dashboard [data-tab112]')?.parentElement:active?.id==='pos118'?$('#pos118 .pos-main-tabs118'):active?.id.includes('sub-user')?$('#subUserWorkspaceTabs'):$('#categoryTabShell');if(target&&toggle.parentElement!==target)target.prepend(toggle)}
function polish(){queued=false;placeToggle();document.querySelectorAll('.history-actions95').forEach(n=>{const parent=n.parentElement;if(parent?.classList.contains('pay-group-body95')&&n!==parent.lastElementChild)parent.append(n)});
 document.querySelectorAll('.pay-group95>summary>span:last-child:not([data-summary118])').forEach(n=>{n.dataset.summary118='1';const parts=n.textContent.split(' · ');n.classList.add('pay-summary118');n.replaceChildren(...parts.map(t=>{const item=document.createElement('span'),small=document.createElement('small'),strong=document.createElement('strong');const m=t.match(/^([\d,.]+)\s+(.+)$/);small.textContent=m?m[2]:/draft|finalized|pending/i.test(t)?'Status':t==='Sample'?'Mode':'Scope';strong.textContent=m?m[1]:t;item.append(small,strong);return item}))});
 const avatar=$('#headerAccountInitials'),trigger=$('#headerAccountTrigger');if(avatar&&trigger&&avatar.parentElement!==trigger)trigger.prepend(avatar);
 document.querySelectorAll('[role=status],[role=alert]').forEach(n=>{if(n.closest('#status118,#loginGate,#landscape117,.pos118,.discard-confirm1440'))return;const text=n.textContent.trim(),previous=seen.get(n);seen.set(n,text);if(previous===text||!text||!n.getClientRects().length)return;if(n.getAttribute('role')==='alert'||n.matches('.status113,[data-quote-status117]')||n.closest('form')&&/saved|failed|could not|invalid|error|success|downloaded|imported/i.test(text)){notify(text,n.getAttribute('role')==='alert'||n.classList.contains('error')||/failed|could not|invalid|error/i.test(text),/…$/.test(text));}});
}
function schedule(){if(!queued){queued=true;requestAnimationFrame(polish)}}
function ready(){viewport();window.visualViewport?.addEventListener('resize',viewport);window.visualViewport?.addEventListener('scroll',viewport);window.addEventListener('resize',viewport);toggle=document.createElement('button');toggle.id='tabletMenu118';toggle.type='button';toggle.innerHTML='<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/></svg>';toggle.setAttribute('aria-label','Open navigation');toggle.setAttribute('aria-controls','appSidebar');toggle.setAttribute('aria-expanded','false');toggle.onclick=e=>{e.stopPropagation();const open=document.body.classList.toggle('nav118');toggle.setAttribute('aria-expanded',String(open))};const scrim=document.createElement('button');scrim.id='tabletScrim118';scrim.setAttribute('aria-label','Close navigation');scrim.onclick=close;document.body.append(scrim);$('#appSidebar')?.addEventListener('click',e=>{if(e.target.closest('.tab-btn,.nav-header'))close()});document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});window.addEventListener('resize',tablet);window.addEventListener('orientationchange',()=>setTimeout(tablet,100));window.addEventListener('page113',()=>{close();schedule()});tablet();polish();new MutationObserver(schedule).observe(document.body,{childList:true,subtree:true,characterData:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
