/* HR records share the existing, version-protected employee store. */
(function(){
'use strict';const esc=v=>escapeHtml(String(v??''));
let selection='',editor=null;
function employee(){return Work82.employees.find(e=>e.id===selection)||Work82.employees.find(e=>e.data.active!==false)||Work82.employees[0]}
function form(kind,record={}){const fields=kind==='contracts'?[
 ['Title / contract reference','title','text'],['Start date','start','date'],['End date','end','date'],['Renewal review date','renewal','date'],['Document link (HTTPS)','document','url'],['Notes','notes','text']]:[
 ['Assessment date','date','date'],['Reviewer','reviewer','text'],['Assessment title','title','text'],['Overall rating (1–5)','rating','number'],['Criteria and ratings (one per line)','criteria','textarea'],['Comments / agreed actions','notes','textarea']];
 return `<form id="hrRecord99"><div class="fields82">${fields.map(([label,name,type])=>type==='textarea'?`<label class="hr-paragraph105">${label}<textarea name="${name}" rows="4">${esc(record[name]||'')}</textarea></label>`:field82(label,name,record[name]||'',type,(name==='title'?'required ':'')+(name==='rating'?'min="1" max="5" step="0.1"':''))).join('')}</div><footer><button type="button" onclick="cancelHr99()">Cancel</button><button class="primary82">Save ${kind==='contracts'?'Contract':'Assessment'}</button></footer></form>`;
}
window.hrHistory99=function(kind,id){const e=employee(),record=e?.data[kind+'99']?.find(r=>r.id===id);if(!record)return;document.getElementById('hrHistory99')?.remove();const root=document.createElement('div');root.id='hrHistory99';root.className='pay-overlay95';root.innerHTML='<section class="pay-dialog95" role="dialog" aria-modal="true" aria-label="Record history"><header><h3>Record History</h3><button type="button" aria-label="Close">×</button></header>'+[record,...(record.revisions||[]).slice().reverse()].map((r,i)=>'<section class="block82"><h4>'+esc(i===0?'Current record':r.updatedAt||'Earlier revision')+'</h4>'+Object.entries(r).filter(([k])=>!['id','revisions'].includes(k)).map(([k,v])=>'<p><strong>'+esc(k)+':</strong> '+esc(v)+'</p>').join('')+'</section>').join('')+'</section>';document.body.append(root);root.querySelector('header button').onclick=()=>root.remove()};
window.deleteHr108=async function(kind,id){const e=employee(),list=e?.data[kind+'99']||[],record=list.find(r=>r.id===id);if(!record)return;if(!await ui108.confirm('Delete HR record','Remove '+record.title+'? Its prior data will remain in the employee audit history.'))return;runAction82(async()=>{await saveWork82('employees',{...e.data,[kind+'99']:list.filter(r=>r.id!==id),deletedHr108:[...(e.data.deletedHr108||[]),{kind,record,deletedAt:new Date().toISOString(),deletedBy:liveProfile.id}]},e);renderHr99()})};
window.cancelHr99=function(){editor=null;renderHr99()};window.editHr99=function(kind,id=''){const e=employee();if(!e)return;editor={kind,id};renderHr99()};
window.renderHr99=function(){
 const id=document.querySelector('.tab-content.active')?.id;if(!id?.startsWith('hr-'))return;if(!admin82()){document.getElementById(id).replaceChildren();return;}
 if(id==='hr-calendar'){window.hrCalendar14306?.render();return}
 if(window.hrWorkspace14306&&id==='hr-contracts'){hrWorkspace14306.renderContracts();return}
 if(window.hrWorkspace14306&&id==='hr-leave'){hrWorkspace14306.renderLeave();return}
 if(id==='hr-attendance'){if(!Work82.run){payroll95.selectMonth(today82().slice(0,7));syncPayrollRoster99()}mount82(id,'Attendance','Shared with Payroll → Deductions. Save attendance after recording exceptions.',Work82.run?renderAttendance99(Work82.run,Work82.run.status==='finalized'):'<p>Open a payroll month first.</p>',Work82.run?.status==='finalized'?'':action82('Save Attendance','runAction82(()=>hrWorkspace14306.saveAttendance())',true));const root=document.querySelector('#hr-attendance .work82');if(root){const toolbar=root.querySelector(':scope > .attendance-toolbar99'),calendar=root.querySelector(':scope > .attendance-scroll99'),summary=root.querySelector(':scope > .attendance-summary99');if(toolbar&&calendar){const section=document.createElement('section');section.className='block82 attendance-calendar102';section.innerHTML='<header><h4>Attendance Calendar</h4></header>';toolbar.before(section);section.append(toolbar,calendar)}if(summary){summary.classList.add('block82');summary.querySelector('h4')?.remove();summary.insertAdjacentHTML('afterbegin','<header><h4>Attendance Summary</h4></header>')}}return}
 if(id==='hr-leave'){mount82(id,'Leave','Shared employee balances and approved leave.',leaveForm82()+table82(['Employee','Dates','Type','Status','Actions'],Work82.leaves.map(r=>[esc(Work82.employees.find(e=>e.id===r.data.employeeId)?.data.name||'Employee'),esc(r.data.from+' – '+r.data.to),esc(r.data.type),esc(r.data.status),action82('Print Form',`printLeaveApplication97('${r.id}')`)+action82('Delete',`deleteWork108('leaves','${r.id}')`)+(['pending','approved'].includes(r.data.status)?action82('Approve',`leaveStatus82('${r.id}','approved')`)+action82('Cancel',`leaveStatus82('${r.id}','cancelled')`):'')])),action82('Employee Balances',"switchTab('payroll-employees')")+action82('Print Blank Leave Form',"printLeaveApplication97('')"));return}
 const kind=id==='hr-contracts'?'contracts':'assessments',e=employee();if(e)selection=e.id;
 const list=e?.data[kind+'99']||[],record=editor?.kind===kind?list.find(r=>r.id===editor.id)||{}:null;
 const select=`<div class="fields82 hr-picker102 hr-picker105"><label for="hrEmployee99">Employee<select id="hrEmployee99">${Work82.employees.map(r=>`<option value="${esc(r.id)}" ${r.id===e?.id?'selected':''}>${esc(r.data.name)}${r.data.active===false?' (archived)':''}</option>`).join('')}</select></label></div>`;
 const rows=list.map(r=>[esc(r.title),esc(kind==='contracts'?[r.start,r.end].filter(Boolean).join(' – '):r.date),kind==='contracts'?esc(r.renewal||'—'):esc(r.rating||'—'),esc(r.notes||''),kind==='contracts'&&/^https:\/\//i.test(r.document||'')?`<a href="${esc(r.document)}" target="_blank" rel="noopener noreferrer">Open Document</a>`:kind==='assessments'?`<pre class="hr-criteria99">${esc(r.criteria||'')}</pre>`:'—',action82('Edit',`editHr99('${kind}','${r.id}')`)+action82('History',`hrHistory99('${kind}','${r.id}')`)+action82('Delete',`deleteHr108('${kind}','${r.id}')`)]);
 mount82(id,kind==='contracts'?'Contracts & Documents':'Assessments','Records are linked to the employee and kept separately from payroll calculations.',storageNotice82()+select+(e?(record?form(kind,record):'')+table82(['Title','Date / term',kind==='contracts'?'Renewal review':'Rating','Notes',kind==='contracts'?'Document':'Criteria & ratings','Actions'],rows):'<p>Add an employee first.</p>'),e?action82(kind==='contracts'?'Add Contract':'Add Assessment',`editHr99('${kind}')`,true):'');
 document.getElementById('hrEmployee99').onchange=event=>{selection=event.target.value;editor=null;renderHr99()};
 const f=document.getElementById('hrRecord99');if(f&&!editor?.id)window.armNewForm108?.(f,cancelHr99);if(f){f.classList.add('hr-form105');const picker=document.querySelector('#'+id+' .hr-picker105 label');if(picker){const old=picker.parentElement;f.querySelector('.fields82').prepend(picker);old.remove()}}if(f)f.onsubmit=event=>{event.preventDefault();if(!f.reportValidity())return;runAction82(async()=>{
 const data=Object.fromEntries(new FormData(f));if(data.start&&data.end&&data.start>data.end)throw Error('The contract end date must follow its start date.');if(data.document&&!/^https:\/\//i.test(data.document))throw Error('Use an HTTPS document link.');
 const prior=list.find(r=>r.id===editor.id);const next={...data,id:prior?.id||crypto.randomUUID(),updatedAt:new Date().toISOString(),reviewer:data.reviewer||liveProfile.full_name||liveProfile.email,revisions:[...(prior?.revisions||[]),...(prior?[{...prior,revisions:undefined}]:[])]};
 await saveWork82('employees',{...e.data,[kind+'99']:[next,...list.filter(r=>r.id!==next.id)]},e);editor=null;renderHr99();showCenterStatus('HR record saved.');
 })};
};
window.addEventListener('DOMContentLoaded',()=>{
 const nav=document.getElementById('nav-module-payroll');if(!nav)return;
 let hr=document.getElementById('nav-module-hr');if(!hr){hr=document.createElement('div');hr.id='nav-module-hr';hr.className='nav-category';hr.dataset.module='hr';
 hr.innerHTML='<div class="nav-header" onclick="activateCategory(this, \'payroll-employees\')">Human Resources <span class="arrow">▼</span></div><div class="nav-links"></div>';nav.before(hr)}
 const links=hr.querySelector('.nav-links'),employees=nav.querySelector('[onclick*="payroll-employees"]');if(employees){employees.textContent='Employee';if(!links.querySelector('[onclick*="payroll-employees"]'))links.append(employees);else employees.remove()}
 for(const [id,label] of [['hr-attendance','Attendance'],['hr-leave','Leave'],['hr-assessments','Assessment'],['hr-contracts','Contract Documents'],['hr-calendar','Calendar']]){
 if(!links.querySelector(`[onclick*="${id}"]`)){const b=document.createElement('button');b.type='button';b.className='tab-btn';b.textContent=label;b.setAttribute('onclick',`switchTab('${id}')`);links.append(b)}
 if(!document.getElementById(id)){const section=document.createElement('div');section.id=id;section.dataset.module='hr';section.className='tab-content';document.getElementById('payroll-overview').parentElement.append(section)}
 }nav.before(hr);window.applyGranularPermissionAccess?.();
 const render=renderWork82;window.renderWork82=function(...args){const out=render.apply(this,args);renderHr99();const active=document.querySelector('.tab-content.active');if(active?.id.startsWith('payroll-')&&active.id!=='payroll-employees'){const header=active.querySelector('.work82>header .actions82');if(header&&!header.querySelector('[data-hr99]')){const b=document.createElement('button');b.dataset.hr99='';b.type='button';b.textContent='Manage Employees / Leave';b.onclick=()=>switchTab('payroll-employees');header.prepend(b)}}return out};
 const change=switchTab;window.switchTab=function(id,...args){const out=change.call(this,id,...args);if(id.startsWith('hr-')){if(!Work82.loaded)loadWork82();else renderHr99()}return out};
});
})();
