/* Company setup and handover are server-versioned; service ownership stays explicit. */
(()=>{'use strict';const esc=v=>escapeHtml(String(v??''));let current=null,owner='',job=null,opened=false,prompted='';
const checks={github:'Incoming owner can update and publish the GitHub repository',supabase:'Incoming owner has access to this Supabase project',recovery:'Website origin and password-recovery links are configured and tested',login:'Incoming administrator has signed in successfully',gmail:'Saved sender has authorized Gmail and completed a test',chatgpt:'Incoming ChatGPT task works; the previous task is paused'};
function guard(actor=owner){if(!actor||liveProfile?.id!==actor||liveProfile.role!=='admin'||liveProfile.status!=='active')throw Error('Administrator access changed. Reopen these settings.');return actor}
function apply(data){const d=data?.installation?.deployment;if(!d||!Object.keys(d).length)return;const c=deployment14320.config;c.site={...(c.site||{}),url:d.siteUrl,repository:d.repository,branch:d.branch};c.workspaces={...(c.workspaces||{}),accounting:d.accounting,publicRestaurant:d.publicRestaurant,restaurant:d.restaurant};window.OJM_PUBLIC_APP_URL=d.siteUrl;window.OJM_WORKSPACE_URLS={...c.workspaces};try{localStorage.removeItem('ojm_workspace_urls14234')}catch{};window.budgetGmail14314?.disconnect?.();}
async function load(){const actor=liveProfile?.id;guard(actor);if(job&&owner===actor)return job;owner=actor;job=(async()=>{const r=await ojmDb.rpc('installation_status14320');guard(actor);if(r.error)throw r.error;if(!r.data?.installation?.instance)throw Error('Installation status was not confirmed.');current=r.data;apply(current);return current})().finally(()=>{if(owner===actor)job=null});return job}
function fields(data){const s=data.installation,d=s.deployment||{},c=deployment14320.config,a=data.accounts?.data||{},b=data.company||{};return {name:b.display_name||b.legal_name||'',companyEmail:b.email||'',emailSender:a.emailSender||'',emails:a.emails||'',trialEmailTo:a.trialEmailTo||'',chatgptAccountEmail:a.chatgptAccountEmail||'',gmailClientId:a.gmailClientId||'',siteUrl:d.siteUrl||deployment14320.site(),repository:d.repository||c.site?.repository||'',branch:d.branch||c.site?.branch||'main',accounting:d.accounting||c.workspaces?.accounting||deployment14320.site(),publicRestaurant:d.publicRestaurant||c.workspaces?.publicRestaurant||'',restaurant:d.restaurant||c.workspaces?.restaurant||''}}
const input=(key,label,value,type='text',required=false)=>'<label>'+label+'<input name="'+key+'" type="'+type+'" value="'+esc(value)+'" '+(required?'required ':'')+'autocomplete="off"></label>';
function configFile(d){return '// Public settings only. Keep service keys on the server.\nwindow.OJM_DEPLOYMENT = '+JSON.stringify({...deployment14320.config,site:{url:d.siteUrl,repository:d.repository,branch:d.branch},workspaces:{accounting:d.accounting,publicRestaurant:d.publicRestaurant,restaurant:d.restaurant}},null,2)+';\n'}
function download(text,name){const url=URL.createObjectURL(new Blob([text],{type:'text/javascript'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
async function open(mode='settings'){if(opened)return;opened=true;let root;
try{const data=await load(),actor=guard(),v=fields(data),fresh=!data.installation.initialized;if(fresh)mode='install';
const users=await ojmDb.from('profiles').select('id,full_name,email,role,status').eq('role','admin').eq('status','active');guard(actor);if(users.error)throw users.error;
const title=mode==='install'?'Set up this company':mode==='handover'?'Administrator handover':'Installation & Handover';
const pending=ui108.modal(title,'<form id="installationForm14320"><p>Save company details and verify the connected services. Each owner uses their own service accounts.</p><div class="installation-grid14320">'+input('name','Company name',v.name,'text',true)+input('companyEmail','Company email',v.companyEmail,'email')+input('emailSender','Email sender',v.emailSender,'email')+input('emails','Regular recipients',v.emails)+input('trialEmailTo','Test recipient',v.trialEmailTo,'email')+input('chatgptAccountEmail','ChatGPT account',v.chatgptAccountEmail,'email')+input('gmailClientId','Gmail client ID',v.gmailClientId)+input('siteUrl','Published accounting website',v.siteUrl,'url',true)+input('repository','GitHub repository (owner/name)',v.repository,'text',true)+input('branch','Published branch',v.branch,'text',true)+input('accounting','Accounting link',v.accounting,'url',true)+input('publicRestaurant','Public restaurant link',v.publicRestaurant,'url')+input('restaurant','Restaurant Back Office link',v.restaurant,'url')+'<label>'+(mode==='handover'?'Incoming administrator':'Responsible administrator')+'<select name="incoming" required>'+users.data.filter(u=>mode!=='handover'||u.id!==actor).map(u=>'<option value="'+esc(u.id)+'" '+(u.id===(data.installation.incoming_admin||actor)?'selected':'')+'>'+esc(u.full_name||u.email)+'</option>').join('')+'</select></label></div>'+(mode==='handover'?'<p>Create the incoming administrator in Users & Permissions first. User permissions remain managed there.</p>':'')+'<fieldset><legend>Service verification</legend>'+Object.entries(checks).map(([key,label])=>'<label class="installation-check14320"><input type="checkbox" name="check_'+key+'" '+(mode==='settings'&&data.installation.checks?.[key]?'checked':'')+'>'+label+'</label>').join('')+'</fieldset><p>Changing these saved details does not transfer GitHub or Supabase ownership, sign into Gmail or ChatGPT, or move scheduled tasks. Verify access in those services before completing a handover.</p><div class="actions82"><button type="submit" class="je-btn je-btn-emerald">'+(mode==='install'?'Complete Setup':mode==='handover'?'Complete Handover':'Save Details')+'</button><button type="button" class="je-btn je-btn-secondary" data-download-config14320>Download Configuration</button><a href="docs/PORTABILITY-v143.20.md" target="_blank" rel="noopener">Installation guide</a></div><p role="status"></p><p role="alert"></p></form>',[{label:'Close',value:false}],true);root=document.querySelector('.ui-overlay108:last-child');root.classList.add('installation-dialog14320');const form=root.querySelector('form');let attempt=null,saved=false,savedValues=null;
const values=()=>Object.fromEntries(new FormData(form));root.querySelector('[data-download-config14320]').onclick=()=>{if(form.reportValidity())download(configFile(savedValues||values()),'deployment-config.js')};
form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]');if(button.disabled)return;button.disabled=true;form.querySelector('[role=alert]').textContent='';
try{guard(actor);const f=values(),accounts={emailSender:companyAccounts14319.email(f.emailSender,'Sender'),emails:budgetGmail14314.recipients(f.emails).join(', '),trialEmailTo:companyAccounts14319.email(f.trialEmailTo,'Test recipient'),chatgptAccountEmail:companyAccounts14319.email(f.chatgptAccountEmail,'ChatGPT account'),gmailClientId:f.gmailClientId.trim()};if(accounts.gmailClientId&&!budgetGmail14314.validClientId(accounts.gmailClientId))throw Error('Enter a valid Gmail client ID.');
const deployment=Object.fromEntries(['siteUrl','repository','branch','accounting','publicRestaurant','restaurant'].map(k=>[k,f[k].trim()]));for(const k of ['siteUrl','accounting','publicRestaurant','restaurant'])if(deployment[k]){const u=new URL(deployment[k]);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)throw Error('Use published HTTP or HTTPS website links.');}
const params={p_expected_version:data.installation.version,p_expected_budget_version:data.accounts?.version||0,p_mode:mode,p_company:{name:f.name.trim(),email:companyAccounts14319.email(f.companyEmail,'Company')},p_accounts:accounts,p_deployment:deployment,p_incoming:f.incoming||null,p_checks:Object.fromEntries(Object.keys(checks).map(k=>[k,form.elements['check_'+k].checked]))};
const signature=JSON.stringify(params);if(!attempt||attempt.signature!==signature)attempt={signature,key:crypto.randomUUID()};const r=await ojmDb.rpc('save_installation14320',{p_request_key:attempt.key,...params});guard(actor);if(r.error)throw r.error;if(!r.data?.installation?.initialized)throw Error('Save was not confirmed. Retry the same details.');current=r.data;apply(current);savedValues=f;saved=true;form.querySelector('[role=status]').textContent=(mode==='handover'?'Handover details saved.':mode==='install'?'Company setup completed.':'Company details saved.')+' Refresh other open devices to load the saved defaults.';button.disabled=true;form.querySelectorAll('input,select').forEach(n=>n.disabled=true);window.dispatchEvent(new Event('companysettings14320'));void budget14313.load(true).catch(()=>{});void loadBusinessSettingsFromSupabase().catch(()=>{});
}catch(error){if(root.isConnected)form.querySelector('[role=alert]').textContent=error.message}finally{if(!saved&&root.isConnected)button.disabled=false}};
await pending;
}catch(e){showCenterStatus(['PGRST202','42P01','PGRST205'].includes(e.code)?'Installation settings need the v143.20 database update. Your existing workspace is available.':e.message,true)}finally{opened=false}}
function ready(){const host=document.getElementById('settings-system');if(!host)return;const section=document.createElement('section');section.className='settings-section-card';section.id='installationSettings14320';section.innerHTML='<div class="settings-section-header"><h4>Installation &amp; Handover</h4></div><div class="actions82"><button type="button" class="je-btn je-btn-secondary" data-installation14320>Company &amp; Deployment</button><button type="button" class="je-btn je-btn-emerald" data-handover14320>Handover</button></div>';host.append(section);section.querySelector('[data-installation14320]').onclick=()=>open();section.querySelector('[data-handover14320]').onclick=()=>open('handover');
const hydrate=window.hydrateSupabaseSession;window.hydrateSupabaseSession=async function(...args){const result=await hydrate.apply(this,args);if(liveProfile?.role==='admin'&&liveProfile.status==='active'){const actor=liveProfile.id;void load().then(data=>{if(data.installation.initialized||prompted===actor)return;guard(actor);prompted=actor;return open('install')}).catch(()=>{/* Offline or an older database is never interpreted as a clean installation. */})}return result};}
window.installation14320={open,load,apply,fields,configFile};window.addEventListener('DOMContentLoaded',ready,{once:true});
})();
