/* Administrator maintenance hub. Reads full server snapshots; closing is one guarded RPC. */
(()=>{'use strict';const ID='settings-maintenance14324',CLOSE='transactions-closing14325',$=id=>document.getElementById(id),E=maintenanceEngine14324,esc=v=>escapeHtml(String(v??''));let owner='',generation=0,pack=null,checkup=null,diagnostic=null,busy=false;
const actor=()=>typeof liveProfile!=='undefined'&&liveProfile?.role==='admin'&&liveProfile.status==='active'&&window.access113?.can(ID)?liveProfile.id:'';
const monthNow=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Vientiane',year:'numeric',month:'2-digit'}).format(new Date()).replace('/','-');
function guard(id){if(!id||id!==actor())throw Error('Administrator sign-in changed. Run the check again.')}
async function rpc(name,args={}){const id=actor();guard(id);if(navigator.onLine===false)throw Error('Connect to the database to run current maintenance checks.');const r=await ojmDb.rpc(name,args);guard(id);if(r.error)throw Error(r.error.code==='PGRST202'||/maintenance.*(schema cache|does not exist)/i.test(r.error.message)?'Install setup/INSTALL-MAINTENANCE-v143.24.sql in this company database, then retry. Closing requires this database update.':r.error.message);return r.data}
function clear(){document.querySelectorAll('.maintenance-modal14324').forEach(n=>n.resolve108?.(false));generation++;pack=checkup=diagnostic=null;owner=actor();for(const id of ['maintenanceChecks14324','maintenanceTrace14324','maintenanceDiagnostics14324'])$(id)?.replaceChildren();}
function table(headers,values){return '<div class="maintenance-table14324"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+values.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function download(name,value,type='application/json'){const text=type==='application/json'?JSON.stringify(value,null,2):value,url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function status(message){for(const id of ['maintenanceStatus14324','maintenanceClosingStatus14325'])if($(id))$(id).textContent=message}
async function task(fn){if(busy)return;busy=true;const id=actor();try{guard(id);if(owner!==id)clear();document.querySelectorAll('#'+ID+' button,#'+CLOSE+' button').forEach(b=>b.disabled=true);await fn(id);guard(id)}catch(e){if(id===actor()){status(e.message);if(!document.querySelector('.maintenance-modal14324'))await modal('Action needs attention','<p>'+esc(e.message)+'</p>')}}finally{busy=false;document.querySelectorAll('#'+ID+' button,#'+CLOSE+' button').forEach(b=>b.disabled=false)}}
function validateCheck(c,month){if(c?.version!==14324||c.month!==month+'-01'||typeof c.fingerprint!=='string'||!Array.isArray(c.issues)||!Array.isArray(c.trial)||!Array.isArray(c.balances)||!c.pending?.revision)throw Error('Incomplete database check. Closing is unavailable.');return c}
async function preflight(month){E.cutoff(month);return validateCheck(await rpc('maintenance_preflight14324',{p_month:month+'-01'}),month)}
async function snapshot(){const p=await rpc('maintenance_snapshot14324');if(p?.maintenanceVersion!==14324||!p.tables||!['accounts','journal_entries','journal_lines','payroll_runs','payroll_lines'].every(t=>Array.isArray(p.tables[t])))throw Error('Incomplete maintenance snapshot');return p}
function renderCheck(c){const block=c.issues.filter(x=>x.severity==='block');return '<h3>'+esc(c.month.slice(0,7))+' Closing Checks</h3><p>'+esc(block.length?block.length+' blocking error(s). Closing cannot continue.':c.issues.length+' item(s) need review. '+(c.selectedCoverage?'Selected checks only; see the complete flag list before closing.':'Trial balance has no blocking difference.'))+'</p><p>Posted ledger through month-end. Currencies stay separate. Checked '+esc(formatAppDate(c.checkedAt,true))+'.</p>'+table(['Currency','Debit','Credit','Difference'],c.trial.map(t=>[t.currency,t.debit,t.credit,t.difference]))+(c.trial.length?'':'<p>No posted ledger lines through this month.</p>')+table(['Severity','Issue','Record / detail'],c.issues.map(i=>[i.severity,i.title,i.detail]))}
async function runChecks(){const month=$('maintenanceMonth14324').value;status('Checking current saved records…');const c=await preflight(month);if($('maintenanceMonth14324').value!==month)throw Error('The selected month changed. Run the check again.');checkup=c;$('maintenanceChecks14324').innerHTML=renderCheck(checkup);status('Checks complete. Reconciliation and individual acknowledgments are required when closing.');return checkup}
function reviewHTML(c){return '<div class="maintenance-review14324">'+renderCheck(c)+'<h3>Cash and bank reconciliation</h3>'+(c.projected?'<p>Balances below include this book’s staged corrections. The database verifies them again when committing.</p>':'')+'<p>Enter actual month-end cash counts and statement balances. A difference needs a reason and explicit acknowledgment.</p><div data-reconciliations>'+c.balances.filter(b=>b.cash_candidate).map(reconHTML).join('')+'</div><label>Include another cash / bank / control account<select data-add-account><option value="">Choose an account…</option>'+c.balances.filter(b=>!b.cash_candidate).map(b=>'<option value="'+esc(b.id)+'">'+esc(b.code+' '+b.name+' ('+b.currency+')')+'</option>').join('')+'</select></label><label><input type="checkbox" data-coverage>I checked the account list and included every cash and bank account used by this company.</label><h3>Intentional open items</h3>'+c.issues.filter(i=>i.severity==='warning').map(i=>'<fieldset data-ack="'+esc(i.id)+'"><legend>'+esc(i.title)+'</legend><p>'+esc(i.detail)+'</p><label><input type="checkbox" data-accept>I intentionally leave this item open / excluded for this closing.</label><label>Reason<input type="text" data-reason maxlength="2000" required></label></fieldset>').join('')+'<p data-validation role="status"></p></div>'}
function reconHTML(b){return '<fieldset data-recon="'+esc(b.id)+'" data-balance="'+esc(b.balance)+'"><legend>'+esc(b.code+' '+b.name+' / '+b.currency)+'</legend><p>Ledger balance: '+esc(b.balance)+' (debit positive, credit negative)</p><label>Actual balance<input type="number" step="0.01" data-actual required></label><p data-difference>Enter the actual balance.</p><label><input type="checkbox" data-accept>I acknowledge this reconciliation difference.</label><label>Reason for difference<input type="text" data-reason maxlength="2000"></label></fieldset>'}
function answers(root){const result={coverageConfirmed:root.querySelector('[data-coverage]').checked,acknowledgments:{},reconciliations:{}};if(!result.coverageConfirmed)throw Error('Confirm the cash and bank account list.');for(const f of root.querySelectorAll('[data-ack]')){const a={acknowledged:f.querySelector('[data-accept]').checked,reason:f.querySelector('[data-reason]').value.trim()};if(!a.acknowledged||a.reason.length<3)throw Error('Acknowledge and explain each open item.');result.acknowledgments[f.dataset.ack]=a}for(const f of root.querySelectorAll('[data-recon]')){const actual=f.querySelector('[data-actual]').value;const delta=E.cents(actual)-E.cents(f.dataset.balance),a={actual,expectedBalance:f.dataset.balance,acknowledged:f.querySelector('[data-accept]').checked,reason:f.querySelector('[data-reason]').value.trim()};if(delta!==0&&(!a.acknowledged||a.reason.length<3))throw Error('Explain and acknowledge each cash / bank difference.');result.reconciliations[f.dataset.recon]=a}return result}
async function review(month,options={}){const id=actor(),c=await preflight(month);if(options.kind==='session'){const p=await snapshot();c.balances=E.projectSession(p,options.session,month,c.balances);c.projected=true;}guard(id);if(c.issues.some(i=>i.severity==='block')){switchTab(CLOSE);$('maintenanceMonth14324').value=month;checkup=c;$('maintenanceChecks14324').innerHTML=renderCheck(c);void modal('Closing blocked — '+month,renderCheck(c));throw Error('Closing blocked. Review Bookkeeping → Closing & Data Checks for the listed errors.')}const pending=modal('Closing review — '+month,reviewHTML(c),[{label:'Cancel',value:false},{label:options.kind==='period'?(options.status==='locked'?'Confirm & Lock Month':'Confirm & Close Month'):options.kind==='year'?'Confirm & Close Year':options.kind==='session'?'Confirm & Finish Corrections':'Export Reconciliation Review',value:true,primary:true}],true),root=document.querySelector('.ui-overlay108:last-child'),button=root.querySelector('footer button:last-child');root.classList.add('maintenance-modal14324');button.disabled=true;const validate=()=>{for(const f of root.querySelectorAll('[data-recon]')){try{f.querySelector('[data-difference]').textContent='Difference: '+((E.cents(f.querySelector('[data-actual]').value)-E.cents(f.dataset.balance))/100)}catch{f.querySelector('[data-difference]').textContent='Enter a valid amount.'}}try{answers(root);button.disabled=false;root.querySelector('[data-validation]').textContent='Ready to submit this review. Saved records are checked again during closing.'}catch(e){button.disabled=true;root.querySelector('[data-validation]').textContent=e.message}};root.addEventListener('input',validate);root.addEventListener('change',validate);root.querySelector('[data-add-account]').onchange=e=>{const b=c.balances.find(x=>x.id===e.target.value);if(b&&!root.querySelector('[data-recon="'+b.id+'"]'))root.querySelector('[data-reconciliations]').insertAdjacentHTML('beforeend',reconHTML(b));e.target.value='';validate()};if(!await pending)return null;guard(id);return {check:c,review:answers(root),actor:id}}
let closing=false;async function finish(options){if(closing)throw Error('A closing review is already in progress.');closing=true;try{const r=await review(options.month,options);if(!r)return false;guard(r.actor);await rpc('maintenance_finish14324',{p_month:options.month+'-01',p_kind:options.kind,p_fingerprint:r.check.fingerprint,p_review:r.review,p_status:options.status||'closed',p_session:options.session||null,p_year:options.year||null,p_confirmation:options.confirmation||null,p_year_fingerprint:options.fingerprint||null});return true}finally{closing=false}}
function modal(title,html,buttons=[{label:'Close',value:false}],wide=true){
 const pending=ui108.modal(title,html,buttons,wide),root=document.querySelector('.ui-overlay108:last-child');root.classList.add('maintenance-modal14324');return pending;
}
async function choose(title,html,confirm='Continue'){
 const id=actor();guard(id);const pending=modal(title,html,[{label:'Cancel',value:false},{label:confirm,value:true,primary:true}]);
 const root=document.querySelector('.ui-overlay108:last-child'),button=root.querySelector('footer button:last-child');
 const validate=()=>{const picks=root.querySelectorAll('[data-pick]');button.disabled=!!picks.length&&!root.querySelector('[data-pick]:checked')||[...root.querySelectorAll('input[required]')].some(n=>!n.checkValidity());};root.addEventListener('change',validate);root.addEventListener('input',validate);validate();
 if(!await pending)return null;guard(id);return root;
}
async function testSelected(){
 const root=await choose('Choose data checks','<label>Month<input type="month" data-month required value="'+esc($('maintenanceMonth14324').value)+'"></label><fieldset><legend>Checks to display</legend>'+[['ledger','Journal IDs, lines and trial balance'],['pending','Pending entries, payroll and unresolved reviews'],['control','Descriptions and control accounts']].map(([id,name])=>'<label><input type="checkbox" data-pick value="'+id+'" checked> '+name+'</label>').join('')+'</fieldset><p>Checks use records through month-end. Closing always runs all mandatory checks. The complete flag list remains in Bookkeeping.</p>','Run Checks');
 if(!root)return;const selected=[...root.querySelectorAll('[data-pick]:checked')].map(n=>n.value);$('maintenanceMonth14324').value=root.querySelector('[data-month]').value;const c=await runChecks();
 const filtered={...c,selectedCoverage:true,issues:c.issues.filter(i=>selected.includes(maintenanceSelection14325.issueGroup(i)))};
 await modal('Data check results — '+c.month.slice(0,7),'<p>Selected coverage: '+esc(selected.join(', '))+'. The trial balance summary is always included. This is a review, not a closing approval.</p>'+renderCheck(filtered));
}
async function exportSelected(id){
 const root=await choose('Export maintenance data','<label>Comparison month<input type="month" data-month required value="'+esc($('maintenanceMonth14324').value)+'"></label><label>Raw record dates<select data-scope><option value="month">Selected month</option><option value="all">All dates</option></select></label><fieldset><legend>Datasets</legend>'+[['ledger','Journal and account balances'],['payroll','Payroll results and source records'],['staff','Sub-user entries and reports'],['vouchers','Vouchers and versions'],['reference','Chart of accounts and currencies'],['audit','Audit records'],['complete','Complete raw snapshot — all datasets, all dates']].map(([key,label])=>'<label><input type="checkbox" data-pick value="'+key+'" '+(['ledger','payroll'].includes(key)?'checked':'')+'> '+label+'</label>').join('')+'</fieldset><label>Download format<select data-format><option value="xlsx">Excel — General Ledger, Trial Balance, Payroll and comparison formulas</option><option value="zip">ZIP — selected raw CSV / JSON, Excel reports and comparison CSV</option><option value="csv">Comparison CSV — account balances and/or payroll only</option></select></label><p>Balances are cumulative through the comparison month; payroll comparison covers that month. Chart and employee references stay included where needed. A complete snapshot always includes all dates.</p>','Export');
 if(!root)return;const month=root.querySelector('[data-month]').value,groups=[...root.querySelectorAll('[data-pick]:checked')].map(n=>n.value),format=root.querySelector('[data-format]').value,scope=root.querySelector('[data-scope]').value;
 const complete=groups.includes('complete');if(format==='xlsx'&&!complete&&!groups.some(g=>['ledger','payroll'].includes(g)))throw Error('Excel reports require Journal or Payroll. Use ZIP for other datasets.');if(format==='csv'&&!complete&&!groups.some(g=>['ledger','payroll'].includes(g)))throw Error('Comparison CSV requires Journal balances or Payroll. Use ZIP for other datasets.');
 status('Preparing selected data…');const c=await preflight(month);pack=await snapshot();const after=await preflight(month);if(after.fingerprint!==c.fingerprint)throw Error('Records changed during export. Retry for a consistent comparison.');
 const selected=maintenanceSelection14325.select(pack,{month,groups,scope}),comparison=E.comparisonRows(pack,month,c.balances).filter(r=>complete||groups.includes(r.dataset==='balance'?'ledger':'payroll'));
 const csv=E.csv(comparison,['dataset','record_id','period','currency','amount','description']);guard(id);
 if(format==='xlsx'){const blob=await maintenanceReports14326.workbook(pack,month,c.balances,groups,BusinessSettings.current?.companyName||AccountingStore.companyName||'Oon Jai');guard(id);download('oonjai-comparison-'+month+'.xlsx',blob,'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');status('Excel reports and comparison formulas exported.');return;}
 if(format==='csv'){download('comparison-'+month+'.csv',csv,'text/csv;charset=utf-8');status('Comparison CSV exported.');return;}
 const zip=new JSZip();zip.file('raw-snapshot.json',JSON.stringify(selected,null,2));for(const [t,records]of Object.entries(selected.tables)){if(!Array.isArray(records))continue;const headers=[...new Set(records.flatMap(r=>Object.keys(r)))];zip.file('raw/'+t+'.csv',E.csv(records,headers));}
 zip.file('comparison-'+month+'.csv',csv);if(complete||groups.includes('payroll'))zip.file('payroll-results.csv',E.csv(E.payroll(selected)));
 if(complete||groups.some(g=>['ledger','payroll'].includes(g))){const workbook=await maintenanceReports14326.workbook(pack,month,c.balances,groups,BusinessSettings.current?.companyName||AccountingStore.companyName||'Oon Jai');guard(id);zip.file('comparison-reports-'+month+'.xlsx',workbook);}
 zip.file('export-selection.json',JSON.stringify(selected.exportSelection,null,2));
 zip.file('READ-ME.txt','Selected raw data is described in export-selection.json. Reference rows are not date-filtered. Comparison contains cumulative posted balances through '+month+' and payroll results for that month, only for the selected datasets. Currencies are separate. Open comparison-reports-' + month + '.xlsx. Its General Ledger and Trial Balance calculate from Journal Data; Payroll calculates from saved payroll components. Enter independently prepared amounts in yellow External cells on Comparison. Re-export when adding records. The older six-column comparison CSV remains available for other systems. CSV text is escaped against spreadsheet formulas; JSON preserves exact source text.');
 const blob=await zip.generateAsync({type:'blob'});guard(id);download('oonjai-maintenance-'+month+'.zip',blob,'application/zip');status('Selected maintenance export prepared.');
}
function mountClosing(){
 const closing=document.createElement('section');closing.id=CLOSE;closing.className='tab-content';closing.dataset.module='transactions';$(ID).after(closing);
 const card=$(ID).querySelector('.maintenance-card14324');closing.append(card);
 const finishButton=document.createElement('button');finishButton.type='button';finishButton.id='maintenanceClose14325';finishButton.textContent='Review & Close Month';card.querySelector('.maintenance-actions14324').append(finishButton);
 const message=document.createElement('p');message.id='maintenanceClosingStatus14325';message.setAttribute('role','status');closing.append(message,$('maintenanceChecks14324'));
 const nav=document.querySelector('#nav-module-transactions .nav-links'),button=document.createElement('button');button.type='button';button.className='tab-btn';button.textContent='Data Check';button.setAttribute('onclick',"switchTab('"+CLOSE+"')");nav.append(button);
 const tree=APP_PERMISSION_TREE.find(t=>t.id==='transactions');if(tree&&!tree.children.some(([id])=>id===CLOSE))tree.children.push([CLOSE,'Closing & Data Checks']);
 const link=document.createElement('p');link.innerHTML='<button type="button" class="je-btn" id="maintenanceGoClosing14325">Open Closing & Data Checks in Bookkeeping</button>';$(ID).prepend(link);link.firstChild.onclick=()=>switchTab(CLOSE);
 finishButton.onclick=()=>task(async()=>{const month=$('maintenanceMonth14324').value;if(await finish({kind:'period',month,status:'closed'})){status(month+' closed successfully.');if(typeof loadAccountingPeriodStatuses==='function')await loadAccountingPeriodStatuses();await runChecks();status(month+' closed successfully.');}});
 window.navigationWorkflow14316?.sync();
}
function install(){if(!$('settings-system')||$(ID))return;shell113.addSettings(ID,'Maintenance & Audit');$(ID).innerHTML='<div class="maintenance-grid14324"><section class="maintenance-card14324"><h3>Closing & Data Checks</h3><p><strong>Before period closing</strong></p><p>Run checks, reconcile cash and bank accounts, review flags, then confirm month closing. Test and reconciliation buttons do not close the month.</p><label>Month <input id="maintenanceMonth14324" type="month"></label><div class="maintenance-actions14324"><button id="maintenanceRun14324" type="button">Test Data</button><button id="maintenanceReconcile14324" type="button">Reconcile Accounts</button><button id="maintenanceReport14324" type="button">Export Check Report</button></div></section><section class="maintenance-card14324"><h3>Investigator</h3><p>Find an exact Entry ID, record ID, reference or employee ID and follow its saved links and audit history across all dates.</p><label>Identifier <input id="maintenanceQuery14324" type="search" placeholder="Entry ID or reference" autocomplete="off"></label><div class="maintenance-actions14324"><button id="maintenanceFind14324" type="button">Investigate</button></div></section><section class="maintenance-card14324"><h3>Independent Data Comparison</h3><p>Download General Ledger, Trial Balance and Payroll as an Excel comparison workbook with the selected month already filled in. Review its formulas, then enter independent figures in the yellow External cells to see differences. ZIP and CSV exports remain available.</p><div class="maintenance-actions14324"><button id="maintenanceExport14324" type="button">Export Maintenance Data</button><button type="button" class="maintenance-download14324">Excel Comparison Workbook</button></div><p>Exports contain company and payroll records. Keep downloaded copies with your accounting files.</p></section><section class="maintenance-card14324"><h3>System Diagnostics</h3><p>Check release files, required code, known logic tests and the current maintenance layout. Findings name the file and explain the likely effect.</p><div class="maintenance-actions14324"><button id="maintenanceSystem14324" type="button">Run System Diagnostics</button><button id="maintenanceSystemExport14324" type="button">Export Diagnostic Report</button></div><p>Checks compare against the tested release and recorded approved rules. They do not prove every possible workflow is free of bugs.</p></section></div><p id="maintenanceStatus14324" role="status" aria-live="polite"></p><p><a href="setup/INSTALL-MAINTENANCE-v143.24.sql" download>Database update</a> · <a href="docs/MAINTENANCE-v143.24.md" target="_blank" rel="noopener">Maintenance guide and check coverage</a></p><section id="maintenanceChecks14324" class="maintenance-result14324"></section><section id="maintenanceTrace14324" class="maintenance-result14324"></section><section id="maintenanceDiagnostics14324" class="maintenance-result14324"></section>';
 $('maintenanceMonth14324').value=monthNow();$('maintenanceMonth14324').onchange=()=>{checkup=null;$('maintenanceChecks14324').replaceChildren()};
 mountClosing();
 $('maintenanceRun14324').onclick=()=>task(testSelected);
 $('maintenanceReconcile14324').onclick=()=>task(async()=>{const r=await review($('maintenanceMonth14324').value);if(r){download('reconciliation-'+r.check.month+'.json',{check:r.check,review:r.review});status('Reconciliation review exported. No period status was changed.')}});
 $('maintenanceReport14324').onclick=()=>task(async()=>{if(!checkup)await runChecks();if(await modal('Export closing check report',renderCheck(checkup),[{label:'Cancel',value:false},{label:'Download Report',value:true,primary:true}]))download('closing-check-'+checkup.month+'.json',checkup)});
 $('maintenanceFind14324').onclick=()=>task(async()=>{const q=$('maintenanceQuery14324').value.trim();if(!q)throw Error('Enter an identifier.');status('Reading current linked records…');pack=await snapshot();const matches=E.investigate(pack,q);$('maintenanceTrace14324').innerHTML='<h3>Investigation: '+esc(q)+'</h3><p>'+matches.length+' connected record(s). Snapshot '+esc(formatAppDate(pack.copiedAt14324,true))+'. '+(matches.length>200?'Showing the first 200. Download the complete raw snapshot to inspect the rest.':'')+'</p>'+matches.slice(0,200).map(m=>'<details><summary>'+esc(m.table+' / '+(m.record.id||m.record.journal_id||m.record.journal_line_id||'record')+' — '+m.connection)+'</summary><pre>'+esc(JSON.stringify(m.record,null,2))+'</pre></details>').join('');status(matches.length?'Investigation complete.':'No exact identifier match. Check the original ID or reference.');await modal('Investigation — '+q,$('maintenanceTrace14324').innerHTML);$('maintenanceTrace14324').replaceChildren()});
 $('maintenanceQuery14324').onkeydown=e=>{if(e.key==='Enter')$('maintenanceFind14324').click()};
 $('maintenanceExport14324').onclick=()=>task(exportSelected);
 const template=$(ID).querySelector('.maintenance-download14324');template.textContent='Excel Comparison Workbook';template.onclick=e=>{e.preventDefault();task(id=>exportSelected(id))};

 $('maintenanceSystem14324').onclick=()=>task(async(id)=>{status('Checking release files and runtime…');diagnostic=await systemDiagnostics14324.run();guard(id);$('maintenanceDiagnostics14324').innerHTML='<h3>System Diagnostics</h3><p>'+esc(diagnostic.coverage)+'</p>'+table(['Status','File','Finding','Likely effect'],diagnostic.findings.map(f=>[f.status,f.file,f.problem,f.effect]));status('Diagnostics complete: '+diagnostic.findings.filter(f=>f.status==='error').length+' error(s), '+diagnostic.findings.filter(f=>f.status==='warning').length+' warning(s).');await modal('System Diagnostics',$('maintenanceDiagnostics14324').innerHTML);$('maintenanceDiagnostics14324').replaceChildren()});
 $('maintenanceSystemExport14324').onclick=()=>task(async()=>{if(!diagnostic)throw Error('Run System Diagnostics first.');if(await modal('Export diagnostic report','<p>Download the last completed diagnostic findings, file names and effects as JSON.</p>',[{label:'Cancel',value:false},{label:'Download Report',value:true,primary:true}]))download('system-diagnostics14324.json',diagnostic)});
 const original=window.loadLiveProfile;if(typeof original==='function')window.loadLiveProfile=async function(...a){clear();const r=await original.apply(this,a);clear();return r};
 window.addEventListener('page113',()=>{if(owner!==actor())clear()});
 const gate=$('loginGate');if(gate)new MutationObserver(()=>{if(!gate.classList.contains('is-authenticated'))clear()}).observe(gate,{attributes:true,attributeFilter:['class']});
}
window.maintenance14324={preflight,snapshot,finish,review,runChecks};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();})();
