/* Administrator maintenance hub. Reads full server snapshots; closing is one guarded RPC. */
(()=>{'use strict';const ID='settings-maintenance14324',$=id=>document.getElementById(id),E=maintenanceEngine14324,esc=v=>escapeHtml(String(v??''));let owner='',generation=0,pack=null,checkup=null,diagnostic=null,busy=false;
const actor=()=>typeof liveProfile!=='undefined'&&liveProfile?.role==='admin'&&liveProfile.status==='active'&&window.access113?.can(ID)?liveProfile.id:'';
const monthNow=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Vientiane',year:'numeric',month:'2-digit'}).format(new Date()).replace('/','-');
function guard(id){if(!id||id!==actor())throw Error('Administrator sign-in changed. Run the check again.')}
async function rpc(name,args={}){const id=actor();guard(id);if(navigator.onLine===false)throw Error('Connect to the database to run current maintenance checks.');const r=await ojmDb.rpc(name,args);guard(id);if(r.error)throw Error(r.error.code==='PGRST202'||/maintenance.*(schema cache|does not exist)/i.test(r.error.message)?'Install setup/INSTALL-MAINTENANCE-v143.24.sql in this company database, then retry. Closing requires this database update.':r.error.message);return r.data}
function clear(){document.querySelectorAll('.maintenance-modal14324').forEach(n=>n.resolve108?.(false));generation++;pack=checkup=diagnostic=null;owner=actor();for(const id of ['maintenanceChecks14324','maintenanceTrace14324','maintenanceDiagnostics14324'])$(id)?.replaceChildren();}
function table(headers,values){return '<div class="maintenance-table14324"><table><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+values.map(row=>'<tr>'+row.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>'}
function download(name,value,type='application/json'){const text=type==='application/json'?JSON.stringify(value,null,2):value,url=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),3000)}
function status(message){if($('maintenanceStatus14324'))$('maintenanceStatus14324').textContent=message}
async function task(fn){if(busy)return;busy=true;const id=actor();try{guard(id);if(owner!==id)clear();document.querySelectorAll('#'+ID+' button').forEach(b=>b.disabled=true);await fn(id);guard(id)}catch(e){status(e.message)}finally{busy=false;document.querySelectorAll('#'+ID+' button').forEach(b=>b.disabled=false)}}
function validateCheck(c,month){if(c?.version!==14324||c.month!==month+'-01'||typeof c.fingerprint!=='string'||!Array.isArray(c.issues)||!Array.isArray(c.trial)||!Array.isArray(c.balances)||!c.pending?.revision)throw Error('Incomplete database check. Closing is unavailable.');return c}
async function preflight(month){E.cutoff(month);return validateCheck(await rpc('maintenance_preflight14324',{p_month:month+'-01'}),month)}
async function snapshot(){const p=await rpc('maintenance_snapshot14324');if(p?.maintenanceVersion!==14324||!p.tables||!['accounts','journal_entries','journal_lines','payroll_runs','payroll_lines'].every(t=>Array.isArray(p.tables[t])))throw Error('Incomplete maintenance snapshot');return p}
function renderCheck(c){const block=c.issues.filter(x=>x.severity==='block');return '<h3>'+esc(c.month.slice(0,7))+' Closing Checks</h3><p>'+esc(block.length?block.length+' blocking error(s). Closing cannot continue.':c.issues.length+' item(s) need review. Trial balance has no blocking difference.')+'</p><p>Posted ledger through month-end. Currencies stay separate. Checked '+esc(c.checkedAt)+'.</p>'+table(['Currency','Debit','Credit','Difference'],c.trial.map(t=>[t.currency,t.debit,t.credit,t.difference]))+(c.trial.length?'':'<p>No posted ledger lines through this month.</p>')+table(['Severity','Issue','Record / detail'],c.issues.map(i=>[i.severity,i.title,i.detail]))}
async function runChecks(){const month=$('maintenanceMonth14324').value;status('Checking current saved records…');checkup=await preflight(month);$('maintenanceChecks14324').innerHTML=renderCheck(checkup);status('Checks complete. Reconciliation and individual acknowledgments are required when closing.');return checkup}
function reviewHTML(c){return '<div class="maintenance-review14324">'+renderCheck(c)+'<h3>Cash and bank reconciliation</h3>'+(c.projected?'<p>Balances below include this book’s staged corrections. The database verifies them again when committing.</p>':'')+'<p>Enter actual month-end cash counts and statement balances. A difference needs a reason and explicit acknowledgment.</p><div data-reconciliations>'+c.balances.filter(b=>b.cash_candidate).map(reconHTML).join('')+'</div><label>Include another cash / bank / control account<select data-add-account><option value="">Choose an account…</option>'+c.balances.filter(b=>!b.cash_candidate).map(b=>'<option value="'+esc(b.id)+'">'+esc(b.code+' '+b.name+' ('+b.currency+')')+'</option>').join('')+'</select></label><label><input type="checkbox" data-coverage>I checked the account list and included every cash and bank account used by this company.</label><h3>Intentional open items</h3>'+c.issues.filter(i=>i.severity==='warning').map(i=>'<fieldset data-ack="'+esc(i.id)+'"><legend>'+esc(i.title)+'</legend><p>'+esc(i.detail)+'</p><label><input type="checkbox" data-accept>I intentionally leave this item open / excluded for this closing.</label><label>Reason<input type="text" data-reason maxlength="2000" required></label></fieldset>').join('')+'<p data-validation role="status"></p></div>'}
function reconHTML(b){return '<fieldset data-recon="'+esc(b.id)+'" data-balance="'+esc(b.balance)+'"><legend>'+esc(b.code+' '+b.name+' / '+b.currency)+'</legend><p>Ledger balance: '+esc(b.balance)+' (debit positive, credit negative)</p><label>Actual balance<input type="number" step="0.01" data-actual required></label><p data-difference>Enter the actual balance.</p><label><input type="checkbox" data-accept>I acknowledge this reconciliation difference.</label><label>Reason for difference<input type="text" data-reason maxlength="2000"></label></fieldset>'}
function answers(root){const result={coverageConfirmed:root.querySelector('[data-coverage]').checked,acknowledgments:{},reconciliations:{}};if(!result.coverageConfirmed)throw Error('Confirm the cash and bank account list.');for(const f of root.querySelectorAll('[data-ack]')){const a={acknowledged:f.querySelector('[data-accept]').checked,reason:f.querySelector('[data-reason]').value.trim()};if(!a.acknowledged||a.reason.length<3)throw Error('Acknowledge and explain each open item.');result.acknowledgments[f.dataset.ack]=a}for(const f of root.querySelectorAll('[data-recon]')){const actual=f.querySelector('[data-actual]').value;const delta=E.cents(actual)-E.cents(f.dataset.balance),a={actual,expectedBalance:f.dataset.balance,acknowledged:f.querySelector('[data-accept]').checked,reason:f.querySelector('[data-reason]').value.trim()};if(delta!==0&&(!a.acknowledged||a.reason.length<3))throw Error('Explain and acknowledge each cash / bank difference.');result.reconciliations[f.dataset.recon]=a}return result}
async function review(month,options={}){const id=actor(),c=await preflight(month);if(options.kind==='session'){const p=await snapshot();c.balances=E.projectSession(p,options.session,month,c.balances);c.projected=true;}guard(id);if(c.issues.some(i=>i.severity==='block')){switchTab(ID);$('maintenanceMonth14324').value=month;checkup=c;$('maintenanceChecks14324').innerHTML=renderCheck(c);throw Error('Closing blocked. Review Maintenance & Audit for the listed errors.')}const pending=ui108.modal('Closing review — '+month,reviewHTML(c),[{label:'Cancel',value:false},{label:'Confirm reviewed checks',value:true,primary:true}],true),root=document.querySelector('.ui-overlay108:last-child'),button=root.querySelector('footer button:last-child');root.classList.add('maintenance-modal14324');button.disabled=true;const validate=()=>{for(const f of root.querySelectorAll('[data-recon]')){try{f.querySelector('[data-difference]').textContent='Difference: '+((E.cents(f.querySelector('[data-actual]').value)-E.cents(f.dataset.balance))/100)}catch{f.querySelector('[data-difference]').textContent='Enter a valid amount.'}}try{answers(root);button.disabled=false;root.querySelector('[data-validation]').textContent='Ready to submit this review. Saved records are checked again during closing.'}catch(e){button.disabled=true;root.querySelector('[data-validation]').textContent=e.message}};root.addEventListener('input',validate);root.addEventListener('change',validate);root.querySelector('[data-add-account]').onchange=e=>{const b=c.balances.find(x=>x.id===e.target.value);if(b&&!root.querySelector('[data-recon="'+b.id+'"]'))root.querySelector('[data-reconciliations]').insertAdjacentHTML('beforeend',reconHTML(b));e.target.value='';validate()};if(!await pending)return null;guard(id);return {check:c,review:answers(root),actor:id}}
let closing=false;async function finish(options){if(closing)throw Error('A closing review is already in progress.');closing=true;try{const r=await review(options.month,options);if(!r)return false;guard(r.actor);await rpc('maintenance_finish14324',{p_month:options.month+'-01',p_kind:options.kind,p_fingerprint:r.check.fingerprint,p_review:r.review,p_status:options.status||'closed',p_session:options.session||null,p_year:options.year||null,p_confirmation:options.confirmation||null,p_year_fingerprint:options.fingerprint||null});return true}finally{closing=false}}
function install(){if(!$('settings-system')||$(ID))return;shell113.addSettings(ID,'Maintenance & Audit');$(ID).innerHTML='<div class="maintenance-grid14324"><section class="maintenance-card14324"><h3>Closing & Data Checks</h3><p>Test saved entries, trial balances, pending records and control accounts. Cash and bank balances are reconciled before closing.</p><label>Month <input id="maintenanceMonth14324" type="month"></label><div class="maintenance-actions14324"><button id="maintenanceRun14324" type="button">Test All Data</button><button id="maintenanceReconcile14324" type="button">Reconcile Accounts</button><button id="maintenanceReport14324" type="button">Export Check Report</button></div></section><section class="maintenance-card14324"><h3>Investigator</h3><p>Find an exact Entry ID, record ID, reference or employee ID and follow its saved links and audit history across all dates.</p><label>Identifier <input id="maintenanceQuery14324" type="search" placeholder="Entry ID or reference" autocomplete="off"></label><div class="maintenance-actions14324"><button id="maintenanceFind14324" type="button">Investigate</button></div></section><section class="maintenance-card14324"><h3>Independent Data Comparison</h3><p>Export the complete raw accounting snapshot and selected-month balance / payroll comparison rows. Paste comparison rows into the Excel template and compare with your outside records.</p><div class="maintenance-actions14324"><button id="maintenanceExport14324" type="button">Export Maintenance Data</button><a class="maintenance-download14324" href="assets/maintenance/Oon-Jai-Maintenance-Comparison.xlsx" download>Excel Comparison Template</a></div><p>Exports contain company and payroll records. Keep downloaded copies with your accounting files.</p></section><section class="maintenance-card14324"><h3>System Diagnostics</h3><p>Check release files, required code, known logic tests and the current maintenance layout. Findings name the file and explain the likely effect.</p><div class="maintenance-actions14324"><button id="maintenanceSystem14324" type="button">Run System Diagnostics</button><button id="maintenanceSystemExport14324" type="button">Export Diagnostic Report</button></div><p>Checks compare against the tested release and recorded approved rules. They do not prove every possible workflow is free of bugs.</p></section></div><p id="maintenanceStatus14324" role="status" aria-live="polite"></p><p><a href="setup/INSTALL-MAINTENANCE-v143.24.sql" download>Database update</a> · <a href="docs/MAINTENANCE-v143.24.md" target="_blank" rel="noopener">Maintenance guide and check coverage</a></p><section id="maintenanceChecks14324" class="maintenance-result14324"></section><section id="maintenanceTrace14324" class="maintenance-result14324"></section><section id="maintenanceDiagnostics14324" class="maintenance-result14324"></section>';
 $('maintenanceMonth14324').value=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Vientiane'}).slice(0,7);$('maintenanceMonth14324').onchange=()=>{checkup=null;$('maintenanceChecks14324').replaceChildren()};
 $('maintenanceRun14324').onclick=()=>task(runChecks);
 $('maintenanceReconcile14324').onclick=()=>task(async()=>{const r=await review($('maintenanceMonth14324').value);if(r){download('reconciliation-'+r.check.month+'.json',{check:r.check,review:r.review});status('Reconciliation review exported. No period status was changed.')}});
 $('maintenanceReport14324').onclick=()=>task(async()=>{if(!checkup)await runChecks();download('closing-check-'+checkup.month+'.json',checkup)});
 $('maintenanceFind14324').onclick=()=>task(async()=>{const q=$('maintenanceQuery14324').value.trim();if(!q)throw Error('Enter an identifier.');status('Reading current linked records…');pack=await snapshot();const matches=E.investigate(pack,q);$('maintenanceTrace14324').innerHTML='<h3>Investigation: '+esc(q)+'</h3><p>'+matches.length+' connected record(s). Snapshot '+esc(pack.copiedAt14324)+'. '+(matches.length>200?'Showing the first 200. Download the complete raw snapshot to inspect the rest.':'')+'</p>'+matches.slice(0,200).map(m=>'<details><summary>'+esc(m.table+' / '+(m.record.id||m.record.journal_id||m.record.journal_line_id||'record')+' — '+m.connection)+'</summary><pre>'+esc(JSON.stringify(m.record,null,2))+'</pre></details>').join('');status(matches.length?'Investigation complete.':'No exact identifier match. Check the original ID or reference.')});
 $('maintenanceQuery14324').onkeydown=e=>{if(e.key==='Enter')$('maintenanceFind14324').click()};
 $('maintenanceExport14324').onclick=()=>task(async(id)=>{const month=$('maintenanceMonth14324').value;status('Preparing complete raw data and comparison files…');const c=await preflight(month);pack=await snapshot();const after=await preflight(month);if(after.fingerprint!==c.fingerprint)throw Error('Records changed during export. Retry for a consistent comparison.');const zip=new JSZip();zip.file('raw-snapshot.json',JSON.stringify(pack,null,2));for(const [t,records]of Object.entries(pack.tables)){if(!Array.isArray(records))continue;const headers=[...new Set(records.flatMap(r=>Object.keys(r)))];zip.file('raw/'+t+'.csv',E.csv(records,headers))}zip.file('comparison-'+month+'.csv',E.csv(E.comparisonRows(pack,month,c.balances),['dataset','record_id','period','currency','amount','description']));zip.file('payroll-results.csv',E.csv(E.payroll(pack)));zip.file('closing-check.json',JSON.stringify(c,null,2));zip.file('READ-ME.txt','Raw tables are all-time, unchanged source values. CSV text is escaped against spreadsheet formulas; use JSON for exact text fidelity. Comparison CSV covers '+month+' payroll results and cumulative posted ledger balances through that month. Paste comparison CSV values (without its header) into App Data A2:F1001 of the separate workbook. Import identifiers as text. Use the same dataset, record IDs, period and currency for External Data. Different payroll runs remain separate. No amounts are converted between currencies.');const blob=await zip.generateAsync({type:'blob'});guard(id);const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='oonjai-maintenance-'+month+'.zip';a.click();setTimeout(()=>URL.revokeObjectURL(url),3000);status('Maintenance export prepared. No saved financial records were changed.')});
 $('maintenanceSystem14324').onclick=()=>task(async()=>{status('Checking release files and runtime…');diagnostic=await systemDiagnostics14324.run();$('maintenanceDiagnostics14324').innerHTML='<h3>System Diagnostics</h3><p>'+esc(diagnostic.coverage)+'</p>'+table(['Status','File','Finding','Likely effect'],diagnostic.findings.map(f=>[f.status,f.file,f.problem,f.effect]));status('Diagnostics complete: '+diagnostic.findings.filter(f=>f.status==='error').length+' error(s), '+diagnostic.findings.filter(f=>f.status==='warning').length+' warning(s).')});
 $('maintenanceSystemExport14324').onclick=()=>task(async()=>{if(!diagnostic)throw Error('Run System Diagnostics first.');download('system-diagnostics14324.json',diagnostic)});
 const original=window.loadLiveProfile;if(typeof original==='function')window.loadLiveProfile=async function(...a){clear();const r=await original.apply(this,a);clear();return r};
 window.addEventListener('page113',()=>{if(owner!==actor())clear()});
 const gate=$('loginGate');if(gate)new MutationObserver(()=>{if(!gate.classList.contains('is-authenticated'))clear()}).observe(gate,{attributes:true,attributeFilter:['class']});
}
window.maintenance14324={preflight,snapshot,finish,review,runChecks};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();})();
