/* Organization routing: job titles describe people; permissions authorize actions. */
(()=>{'use strict';
const can=(id,action='view')=>window.access113?.can(id,action)===true;
const actor=()=>typeof liveProfile==='undefined'?'':liveProfile?.id||'';
let homeGeneration=0;let priorJournalLoader=null;let homeActor='',homeData={users:[],balances:{},reports:[]},homeRequest=null;
const esc=v=>escapeHtml(String(v??''));
function homeAllowed(){return can('sub-users-home14229')}
function invalidate(){homeGeneration++;homeActor='';homeData={users:[],balances:{},reports:[]};homeRequest=null;window.TeamHome14227?.invalidate();}
async function loadHome(force=false){const who=actor();if(!who||!homeAllowed()){invalidate();return homeData}if(homeActor===who&&!force)return homeData;if(homeRequest)return homeRequest;const generation=homeGeneration;const request=(async()=>{const r=await ojmDb.rpc('branch_home14229');if(r.error)throw r.error;if(actor()!==who||!homeAllowed()||generation!==homeGeneration)return {users:[],balances:{},reports:[]};homeActor=who;homeData=r.data||{users:[],balances:{},reports:[]};return homeData})();homeRequest=request;try{return await request}finally{if(homeRequest===request)homeRequest=null}}
function homeUsers(){return homeAllowed()&&homeActor===actor()?homeData.users:[]}
function mayOpen(id){if(!actor()||!can('sub-users-workspace'))return false;return id===actor()||liveProfile.role==='admin'||liveProfiles.some(u=>u.id===id)&&can('user-entry-review')}
function info(j){const route=j?.review_route14229,supervisor=livePermission?.manager_id;const current=!!j&&j.owner_id!==actor()&&can('user-entry-review','approve')&&(liveProfile.role==='admin'||(route?route.current_reviewer===actor():liveProfiles.find(u=>u.id===j.owner_id)?.user_permissions?.manager_id===actor()));return {current,forward:current&&liveProfile.role!=='admin'&&!!supervisor&&!route?.final_approved,next:supervisor,final:!!route?.final_approved,steps:route?.steps||[]}}
function pending(j){return j.status==='submitted'&&info(j).current}
async function loadProfiles(){const who=actor();if(!who)return false;const r=await ojmDb.rpc('review_directory14229');if(r.error)throw Object.assign(Error('User directory could not refresh. '+r.error.message),r.error,{status:r.status||r.error.status});if(actor()!==who)return false;if(!Array.isArray(r.data))throw Error('The complete dataset was not returned.');const next=r.data;if(JSON.stringify(next)===JSON.stringify(liveProfiles))return false;liveProfiles=next;window.renderUserAccessTable?.();window.renderSubUserWorkspace?.();renderOrganization();return true;}
async function loadJournals(){const who=actor();if(!who)return false;const r=await ojmDb.rpc('review_inbox14229');if(r.error)throw Object.assign(Error('Reports could not refresh. '+r.error.message),r.error,{status:r.status||r.error.status});if(actor()!==who)return false;if(!Array.isArray(r.data))throw Error('The complete dataset was not returned.');const next=r.data;if(JSON.stringify(next)===JSON.stringify(reviewStaffJournals))return false;if(priorJournalLoader)await priorJournalLoader();if(actor()!==who)return false;reviewStaffJournals=next;renderUserEntryReview();renderSubUserWorkspace();return true;}
async function revalidate(){const who=actor();if(!who)return;try{const peopleChanged=await loadProfiles(),reportsChanged=await loadJournals();if(peopleChanged||reportsChanged)invalidate();else if(document.getElementById('sub-users-home14229')?.classList.contains('active')&&homeAllowed())await window.TeamHome14227?.reload();}catch(e){if(actor()!==who)return;const denied=['42501','ACCESS_REVOKED','PGRST301','PGRST302'].includes(e.code)||[401,403].includes(Number(e.status));if(!denied){showCenterStatus('Showing previously loaded team records. Refresh could not finish: '+e.message,true);return}if(liveProfile?.role!=='admin'){liveProfiles=[{...liveProfile,user_permissions:livePermission||{}}];reviewStaffJournals=[];renderUserEntryReview();renderSubUserWorkspace();}invalidate();showCenterStatus('Current team access could not be refreshed. '+e.message,true)}}
function directory(){if(!actor())return [];const self={...liveProfile,user_permissions:livePermission||{}};const others=(liveProfiles||[]).filter(u=>u.id!==actor()&&u.role!=='admin');return [self,...others]}
// One reporting-tree sequence for the chart and both workspace navigations.
function orderUsers(input){
 const nodes=new Map(),self=typeof liveProfile==='undefined'?null:liveProfile;
 for(const u of [...input,...(liveProfiles||[]),...(self?[{...self,user_permissions:typeof livePermission==='undefined'?self.user_permissions:livePermission}]:[])]){if(!u?.id)continue;const prior=nodes.get(String(u.id))||{};nodes.set(String(u.id),{...prior,...u,user_permissions:{...prior.user_permissions,...u.user_permissions}});}
 const compare=(a,b)=>String(a.full_name||a.name||a.email||'').localeCompare(String(b.full_name||b.name||b.email||''),'en',{sensitivity:'base'})||String(a.id).localeCompare(String(b.id));
 const people=[...nodes.values()].sort(compare),children=new Map(),visited=new Set(),rank=new Map();
 for(const u of people){const manager=String(u.user_permissions?.manager_id||'');if(!children.has(manager))children.set(manager,[]);children.get(manager).push(u);}
 function visit(u){const id=String(u.id);if(visited.has(id))return;visited.add(id);rank.set(id,rank.size);for(const child of children.get(id)||[])visit(child);}
 people.filter(u=>!nodes.has(String(u.user_permissions?.manager_id||''))||String(u.user_permissions?.manager_id)===String(u.id)).forEach(visit);people.forEach(visit);
 return [...input].sort((a,b)=>rank.get(String(a.id))-rank.get(String(b.id))||compare(a,b));
}
function renderOrganization(){const host=document.getElementById('settings-organization14229');if(!host)return;if(!can('settings-organization14229')){host.replaceChildren();host._organization14231='';return}const people=orderUsers((liveProfiles||[]).filter(u=>u.status==='active')),byId=new Map(people.map(u=>[u.id,u])),children=id=>people.filter(u=>u.user_permissions?.manager_id===id),roots=people.filter(u=>!byId.has(u.user_permissions?.manager_id)),visited=new Set();
 function branch(u){if(visited.has(u.id))return '';visited.add(u.id);const p=u.user_permissions||{},below=children(u.id);return `<li><article class="org-person14231"><span class="org-position14231">${esc(p.job_title||'Position not set')}</span><strong>${esc(u.full_name||u.email)}</strong><small>${esc(p.department14229||'Department not set')}</small><button type="button" class="je-btn je-btn-secondary" data-org-edit14231="${esc(u.id)}">Edit reporting</button></article>${below.length?'<ul>'+below.map(branch).join('')+'</ul>':''}</li>`}
 const tree=roots.map(branch).join(''),unplaced=people.filter(u=>!visited.has(u.id)).map(branch).join('');const html=`<section class="je-card organization-card14231"><header class="je-card-header"><h3 class="je-title">Organization & Reporting</h3></header><p>Each branch shows the assigned supervisor above their team. Reports follow these assignments.</p><div class="organization-scroll14231"><ul class="organization-tree14231">${tree||'<li><p>No active people to display.</p></li>'}</ul>${unplaced?'<h4>Unresolved reporting assignments</h4><ul class="organization-tree14231">'+unplaced+'</ul>':''}</div></section>`;if(host._organization14231===html)return;host._organization14231=html;host.innerHTML=html;host.querySelectorAll('[data-org-edit14231]').forEach(b=>b.onclick=()=>editReporting14231(b.dataset.orgEdit14231));window.headerIcons112?.decorate();}
async function editReporting14231(id){if(liveProfile?.role!=='admin'||!can('settings-organization14229','edit'))return;const person=liveProfiles.find(u=>u.id===id);if(!person)return;const p=person.user_permissions||{},supervisors=liveProfiles.filter(u=>u.id!==id&&u.status==='active'&&(u.role==='admin'||(u.user_permissions?.module_actions113?['view','approve'].every(a=>u.user_permissions.module_actions113['user-entry-review']?.includes(a)):u.user_permissions?.can_approve)));
 const done=ui108.modal('Edit reporting — '+(person.full_name||person.email),`<form id="organizationEditor14231"><label>Position<input name="position" maxlength="100" value="${esc(p.job_title||'')}"></label><label>Department / Team<input name="department" maxlength="100" value="${esc(p.department14229||'')}"></label><label>Direct supervisor<select name="supervisor"><option value="">No assigned supervisor — administrator review</option>${supervisors.map(u=>`<option value="${esc(u.id)}" ${p.manager_id===u.id?'selected':''}>${esc(u.full_name||u.email)}${u.user_permissions?.job_title?' · '+esc(u.user_permissions.job_title):''}</option>`).join('')}</select></label><p role="status"></p><button type="submit" class="je-btn je-btn-emerald">Save reporting</button></form>`,[{label:'Cancel',value:false}],true),overlay=document.querySelector('.ui-overlay108:last-child'),form=overlay.querySelector('form'),who=actor();
 form.onsubmit=async e=>{e.preventDefault();const button=form.querySelector('[type=submit]'),status=form.querySelector('[role=status]');if(button.disabled||actor()!==who||!can('settings-organization14229','edit'))return;button.disabled=true;try{const values={job_title:form.elements.position.value.trim(),department14229:form.elements.department.value.trim(),manager_id:form.elements.supervisor.value||null};const result=await ojmDb.from('user_permissions').update(values).eq('user_id',id).select('user_id,job_title,department14229,manager_id').single();if(result.error)throw result.error;if(result.data?.user_id!==id)throw Error('Reporting save was not confirmed. Reload the structure before retrying.');if(actor()!==who)return;await loadProfiles();renderOrganization();invalidate();overlay.resolve108(true);showCenterStatus('Reporting structure saved.')}catch(e){status.textContent=e.message||'Reporting save was not confirmed.';showCenterStatus(status.textContent,true)}finally{button.disabled=false}};const guard=setInterval(()=>{if(actor()!==who||!can('settings-organization14229','edit'))overlay.resolve108(false)},200);try{await done}finally{clearInterval(guard)}
}
function managerOptions(selected=''){const select=document.getElementById('userAccessManager'),edited=document.getElementById('userAccessId')?.value;if(!select)return;select.innerHTML='<option value="">No assigned supervisor — administrator review</option>'+(liveProfiles||[]).filter(u=>u.id!==edited&&u.status==='active'&&(u.role==='admin'||(u.user_permissions?.module_actions113?['view','approve'].every(a=>u.user_permissions.module_actions113['user-entry-review']?.includes(a)):u.user_permissions?.can_approve))).map(u=>`<option value="${esc(u.id)}">${esc(u.full_name||u.email)}${u.user_permissions?.job_title?' · '+esc(u.user_permissions.job_title):''}${u.user_permissions?.department14229?' · '+esc(u.user_permissions.department14229):''}</option>`).join('');select.value=selected;}
function reviewDecoration(){const root=document.getElementById('submissionComparisonOverlay');if(!root)return;const journalId=[...root.querySelectorAll('[onclick]')].map(b=>(b.getAttribute('onclick')||'').match(/(?:prepareReviewJournal|returnComparison69|postCompared69)\('([^']+)'/)?.[1]).find(Boolean),journal=journalId&&allReviewJournals().find(j=>j.id===journalId);if(journal&&!root.querySelector('[data-route14229]')){const note=document.createElement('div');note.dataset.route14229='1';note.className='settings-compact-note';const state=info(journal);note.innerHTML='<strong>'+(state.final?'Final approval recorded':state.forward?'Next action: Review & Forward to your direct supervisor':state.current?'Awaiting your final review':'Awaiting the assigned reviewer')+'</strong>'+(state.steps.length?'<ul>'+state.steps.map(s=>'<li>'+esc(s.by_name||s.by)+' — '+(s.action==='forward'?'Reviewed & forwarded to '+esc(s.to_name||s.to):'Final approval')+'</li>').join('')+'</ul>':'');root.querySelector('.compare-footer69')?.before(note);}const buttons=[...root.querySelectorAll('[onclick]')];for(const b of buttons){const match=(b.getAttribute('onclick')||'').match(/(?:prepareReviewJournal|approveReviewJournal|prepareComparison69)\('([^']+)'/);if(match){const j=allReviewJournals().find(j=>j.id===match[1]),state=info(j);b.textContent=state.forward?'Review & Forward':'Final Approve';b.dataset.permissionAction1440='approve';if(!state.current)b.remove();}if(/postCompared69/.test(b.getAttribute('onclick'))){const match=(b.getAttribute('onclick')||'').match(/\('([^']+)'/),j=match&&allReviewJournals().find(j=>j.id===match[1]),state=info(j);if(!state.current)b.remove();else if(!state.final){b.textContent=state.forward?'Review & Forward':'Final Approve';b.setAttribute('onclick',`prepareReviewJournal('${j.id}')`);b.dataset.permissionAction1440='approve';}else if((j.lines||[]).some(l=>!wsIsCollection(l)&&!l.journal_entry_id)&&!can('user-entry-review','post'))b.remove();else if((j.lines||[]).every(wsIsCollection))b.dataset.permissionAction1440='approve';}if(/returnComparison69/.test(b.getAttribute('onclick'))){const match=(b.getAttribute('onclick')||'').match(/\('([^']+)'/),j=match&&allReviewJournals().find(j=>j.id===match[1]);if(j&&(!info(j).current||info(j).steps.length))b.remove();}}
}
function ready(){const sub=APP_PERMISSION_TREE.find(p=>p.id==='sub-users');if(sub&&!sub.children.some(([id])=>id==='sub-users-home14229'))sub.children.unshift(['sub-users-home14229','Main Home (branch summary)']);shell113.addSettings?.('settings-organization14229','Organization & Reporting');if(!document.getElementById('settings-organization14229')){const node=document.createElement('div');node.className='tab-content';node.dataset.module='settings';node.id='settings-organization14229';document.getElementById('settings-system')?.parentElement.append(node);const b=document.createElement('button');b.className='tab-btn';b.textContent='Organization & Reporting';b.setAttribute('onclick',"switchTab('settings-organization14229')");document.querySelector('#nav-module-settings .nav-links')?.append(b);APP_PERMISSION_TREE.find(p=>p.id==='settings')?.children.push([node.id,'Organization & Reporting']);}if(!document.getElementById('sub-users-home14229')){const node=document.createElement('div');node.id='sub-users-home14229';node.dataset.module='sub-users';node.className='tab-content';node.innerHTML='<div id="branchHome14229"></div>';document.getElementById('sub-users-workspace')?.parentElement.append(node);const b=document.createElement('button');b.className='tab-btn';b.textContent='Main Home';b.setAttribute('onclick',"switchTab('sub-users-home14229')");b.dataset.target='sub-users-home14229';document.querySelector('#nav-module-sub-users .nav-links')?.prepend(b);}window.populateUserManagerOptions=managerOptions;window.loadProfilesFromSupabase=loadProfiles;window.loadProfilesWithPermissions=loadProfiles;window.availableSubUsers=directory;const priorAllReviews=window.allReviewJournals;window.allReviewJournals=function(){return actor()?(reviewStaffJournals||[]).filter(j=>j.lines?.length):priorAllReviews()};priorJournalLoader=window.loadStaffJournalsForReview;window.loadStaffJournalsForReview=loadJournals;const open=window.openUserAccessEditor;window.openUserAccessEditor=function(id=''){open(id);const u=liveProfiles.find(u=>u.id===id);document.getElementById('userAccessDepartment14229').value=u?.user_permissions?.department14229||'';managerOptions(u?.user_permissions?.manager_id||'')};window.addEventListener('page113',()=>{renderOrganization();reviewDecoration();});const compare=window.openSubmissionComparison;window.openSubmissionComparison=async function(...args){const result=await compare.apply(this,args);reviewDecoration();return result;};window.applyGranularPermissionAccess?.();}
window.Organization14229={orderUsers,homeAllowed,loadHome,homeUsers,mayOpen,info,pending,invalidate,renderOrganization,loadProfiles,loadJournals,revalidate};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
