(function(){
'use strict';const esc=v=>escapeHtml(String(v??''));let queued=false;
const image=data=>/^data:image\/(png|jpeg|webp);base64,/i.test(data||'')?data:'';
function companyLogo(){return image(localStorage.getItem('ojm_company_logo101'))}
window.openProfile105=function(id){
 const e=Work82.employees.find(e=>e.id===id),d=e?.data||{name:liveProfile?.full_name||'User',profileEmail:liveProfile?.email,position:liveProfile?.role};
 document.getElementById('profileView105')?.remove();const box=document.createElement('div');box.id='profileView105';box.className='pay-overlay95';
 const photo=image(d.photoData)||companyLogo();box.innerHTML=`<section class="pay-dialog95 profile-dialog105" role="dialog" aria-modal="true" aria-label="Employee profile"><header class="profile-heading1444"><button type="button" data-close aria-label="Close">×</button>${photo?`<img class="profile-photo105" src="${photo}" alt="${esc(d.photoData?d.name:'Company logo')}">`:`<span class="profile-initials1444" aria-hidden="true">${esc((d.name||'User').trim().split(/\s+/).slice(0,2).map(n=>n[0]).join(''))}</span>`}<h3>${esc(d.name)}</h3></header><dl>${[['Employee code',d.code],['Position',d.position],['Email',d.profileEmail],['Phone',d.phone],['Address',d.address],['Emergency contact',d.emergencyContact],['Status',e?(d.active===false?'Archived':'Active'):'Signed in']].map(([k,v])=>`<dt>${k}</dt><dd>${esc(v||'—')}</dd>`).join('')}</dl><footer>${e&&admin82()?'<button type="button" data-edit>Edit employee</button><button type="button" data-documents>Documents</button>':''}<button type="button" data-close>Close</button></footer></section>`;
 document.body.append(box);box.querySelector('[data-documents]')?.addEventListener('click',()=>{box.remove();window.hrWorkspace14306?hrWorkspace14306.documents(e.id):openDocumentEditor105({employeeId:e.id,list:true})});box.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>box.remove());box.querySelector('[data-edit]')?.addEventListener('click',()=>{box.remove();switchTab('payroll-employees');openEmployee82(e.id)});box.addEventListener('click',e=>{if(e.target===box)box.remove()});box.querySelector('button').focus();box.onkeydown=e=>{if(e.key==='Escape')box.remove()};
};
function profiles(){
 const root=document.querySelector('#payroll-employees.active .work82');if(!root||root.querySelector('#employeeForm82')||root.querySelector('.profile-list105'))return;
 const wrap=document.createElement('div');wrap.className='profile-list105';wrap.innerHTML=Work82.employees.map(e=>{const photo=image(e.data.photoData)||companyLogo();return `<button class="profile-card105" type="button" data-employee="${esc(e.id)}">${photo?`<img src="${photo}" alt="">`:''}<span><strong>${esc(e.data.name)}</strong><small>${esc(e.data.position||'Employee')}</small></span></button>`}).join('');root.querySelector('header')?.after(wrap);wrap.querySelectorAll('button').forEach(b=>b.onclick=()=>openProfile105(b.dataset.employee));
}
function polish(){queued=false;profiles();const contracts=document.querySelector('#hr-contracts.active .work82>header .actions82');if(contracts&&!contracts.querySelector('[data-documents105]')){const b=document.createElement('button');b.type='button';b.dataset.documents105='';b.textContent='Saved Documents';b.onclick=()=>openDocumentEditor105({employeeId:document.getElementById('hrEmployee99')?.value,list:true});contracts.append(b)}const menu=document.getElementById('headerAccountDropdown');if(menu&&!menu.querySelector('[data-profile105]')){const b=document.createElement('button');b.type='button';b.className='header-menu-item';b.dataset.profile105='';b.textContent='View Profile';b.onclick=()=>{menu.hidden=true;const email=String(liveProfile?.email||'').toLowerCase();const e=Work82.employees.find(e=>email&&String(e.data.profileEmail||'').toLowerCase()===email);openProfile105(e?.id)};menu.prepend(b)}}
function ready(){
 const hamburger=document.getElementById('mobileMenuToggle');if(hamburger)document.getElementById('transactionsHeading98')?.prepend(hamburger);
 const settings=document.getElementById('settings-system');const form=document.createElement('form');form.className='settings-section-card auth-settings105';form.innerHTML=`<h3>Password Recovery</h3><label>Published app URL<input type="url" name="url" placeholder="https://your-site.example/accounting/" value="${esc(window.OJM_PUBLIC_APP_URL||localStorage.getItem('ojm_public_app_url105')||'')}"></label><button type="submit" class="je-btn je-btn-emerald">Save recovery address</button><p role="status"></p><p><a href="setup/SETUP-GUIDE-v142.20.txt" download>Recovery setup instructions</a></p>`;settings?.append(form);form.onsubmit=e=>{e.preventDefault();const value=form.elements.url.value.trim();const status=form.querySelector('[role=status]');try{if(value){const u=new URL(value);if(u.protocol!=='https:'||u.username||u.password)throw Error('Use the published HTTPS address.')}localStorage.setItem('ojm_public_app_url105',value);window.OJM_PUBLIC_APP_URL=value;status.textContent='Saved for this browser. Recovery return address: '+passwordRecoveryRedirectUrl()}catch(error){status.textContent=error.message}};
 polish();new MutationObserver(()=>{if(!queued){queued=true;requestAnimationFrame(polish)}}).observe(document.body,{childList:true,subtree:true});
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
