/* Shared module geometry, immediate navigation feedback, account tools and recovery. */
(function(){'use strict';
window.showRecoveryCode109=function(email){let box=document.getElementById('recoveryCode109');box?.remove();box=document.createElement('section');box.id='recoveryCode109';box.innerHTML='<p>Have a recovery code from your email?</p><label>Email recovery code<input autocomplete="one-time-code" inputmode="numeric" maxlength="12"></label><button type="button">Verify code</button><p role="status"></p>';document.getElementById('loginForm').append(box);const button=box.querySelector('button');button.onclick=async()=>{const code=box.querySelector('input').value.trim();if(!/^\d{6,12}$/.test(code)){box.querySelector('[role=status]').textContent='Enter the numeric recovery code from the email.';return}button.disabled=true;passwordRecoveryMode=true;try{const r=await ojmDb.auth.verifyOtp({email,token:code,type:'recovery'});if(r.error)throw r.error;if(!r.data?.session)throw Error('No recovery session was returned. Request a fresh code.');box.remove();showPasswordRecoveryForm();document.querySelector('#passwordRecoveryForm [type=submit]').disabled=false}catch(e){passwordRecoveryMode=false;box.querySelector('[role=status]').textContent=e.message}finally{button.disabled=false}}};
const moduleSelector='.je-card,.work82,.block82,.im-card104,.settings-section-card,.workspace-main-card,.module-card,.ledger-account69,.pay-group95,.schedule-card91,.im-menu106,.r79,.r79-group,.menu-shell109';
const tableWrappers='.table-container,.data-table82,.im-scroll104,.schedule-table91,.r79-table,.final-scroll-table,.attendance-scroll99,.tax-table-scroll102';
const groups=new WeakSet();function decorate(){const active=document.querySelector('.tab-content.active');if(!active)return;
 if(active.id.startsWith('menu-')&&!active.querySelector('.menu-shell109')){const shell=document.createElement('section');shell.className='menu-shell109 module109';shell.append(...active.childNodes);active.append(shell)}const filters=active.querySelector('.engineering-filter108');if(filters&&!filters.parentElement.classList.contains('engineering-filter109')){const box=document.createElement('section');box.className='engineering-filter109';filters.before(box);box.append(filters)}
 active.querySelectorAll(moduleSelector).forEach(m=>{m.classList.add('module109');if(m.parentElement.closest(moduleSelector))m.classList.add('inner-module109')});
 active.querySelectorAll('table').forEach(table=>{if(table.closest('#document-editor105,.legacy82,[hidden]'))return;const wrap=table.parentElement.matches(tableWrappers)?table.parentElement:table;const module=wrap.closest(moduleSelector);if(!module)return;if(module.classList.contains('inner-module109')||module.matches('details')){wrap.classList.add('edge-table109');return}if(!wrap.parentElement.classList.contains('table-module109')){const box=document.createElement('section');box.className='table-module109 inner-module109';wrap.before(box);box.append(wrap)}wrap.classList.add('edge-table109')});
 const parents=new Set([...active.querySelectorAll('details:not(.row-menu99):not(.nav-category)')].filter(d=>!d.closest('#document-editor105,form,.legacy82')).map(d=>d.parentElement));for(const parent of parents){if(groups.has(parent))continue;groups.add(parent);const items=[...parent.children].filter(n=>n.tagName==='DETAILS'&&!n.classList.contains('row-menu99'));if(!items.length)continue;items.forEach((d,i)=>{d.classList.add('collapse109');d.open=i===0});}
 const dock=document.getElementById('workspaceTools108');if(dock){dock.hidden=!liveProfile;const has=!!active.querySelector('table')&&active.id!=='document-editor105';for(const id of ['editorIcon108','auditMode101']){const n=document.getElementById(id);if(n)n.hidden=!has}}
}
function installDock(){const dock=document.getElementById('workspaceTools108');if(!dock)return;const profile=document.getElementById('topHeaderProfile104'),sidebar=document.getElementById('appSidebar'),quote=sidebar?.querySelector('.sidebar-quote108');if(profile&&sidebar){profile.classList.add('sidebar-profile109');if(quote)quote.before(profile);else sidebar.append(profile);const trigger=document.getElementById('headerAccountTrigger');trigger?.removeAttribute('onclick');if(trigger){trigger.onclick=()=>document.querySelector('[data-profile105]')?.click();trigger.setAttribute('aria-label','View profile')}}const bell=document.getElementById('upcomingBell101');if(bell){bell.title='Notifications';bell.querySelectorAll(':scope>span:not(#headerNoticeBadge104)').forEach(n=>n.remove());dock.append(bell)}for(const [id,label,path,fn] of [['switchAccount110','Switch account','<path d="M4 7h15m-4-4 4 4-4 4M20 17H5m4-4-4 4 4 4"/>',()=>switchAccount()],['signOut110','Sign out','<path d="M10 4H4v16h6M9 12h12m-5-5 5 5-5 5"/>',()=>confirmSignOut()]]){const b=document.createElement('button');b.type='button';b.id=id;b.title=label;b.setAttribute('aria-label',label);b.innerHTML='<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7">'+path+'</svg>';b.onclick=fn;dock.append(b)}}
// Collapse repeated table renders within one navigation operation, without caching data edits.
function installNavigation(){const names=['renderJournalHistoryTable','renderAllTransactionsTable','renderNewTransactionsTable','renderReopened67','renderTransactionReviewTable'];let batch=null;for(const name of names){const fn=window[name];if(typeof fn!=='function')continue;window[name]=function(...args){if(batch&&name!=='renderTransactionReviewTable'){if(batch.has(name))return;batch.add(name)}return fn.apply(this,args)}}const sw=window.switchTab;window.switchTab=function(...args){const prior=batch;batch=new Set();try{return sw.apply(this,args)}finally{batch=prior;document.querySelectorAll('#appSidebar .nav-selected109').forEach(n=>n.classList.remove('nav-selected109'));queueMicrotask(decorate)}};
 // Paint selected navigation before synchronous module rendering starts.
 let pending=0;document.getElementById('appSidebar')?.addEventListener('click',e=>{const target=e.target.closest('[onclick]');if(!target||e.__nav109)return;const code=target.getAttribute('onclick'),match=code.match(/(?:switchTab|activateCategory)\([^']*'([^']+)'/);if(!match||!canAccessAppTarget(match[1]))return;e.preventDefault();e.stopImmediatePropagation();document.querySelectorAll('#appSidebar .nav-selected109').forEach(n=>n.classList.remove('nav-selected109'));target.classList.add('nav-selected109');const token=++pending;requestAnimationFrame(()=>setTimeout(()=>{if(token!==pending)return;const click=new MouseEvent('click',{bubbles:true,cancelable:true});click.__nav109=true;target.dispatchEvent(click)},0));},true);}
function ready(){document.getElementById('settings-integration82')?.remove();document.querySelectorAll('[onclick*="settings-integration82"]').forEach(n=>n.remove());const setting=APP_PERMISSION_TREE.find(p=>p.id==='settings');if(setting)setting.children=setting.children.filter(c=>c[0]!=='settings-integration82');installDock();installNavigation();decorate();let queued=false;new MutationObserver(rs=>{if(!rs.some(r=>[...r.addedNodes].some(n=>n.nodeType===1)))return;if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;decorate()})}).observe(document.querySelector('.workspace-scroll')||document.body,{childList:true,subtree:true});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
