/* Shared geometry and schedule workflow corrections. */
(function(){
'use strict';
let upcomingTimer92;
function upcomingForm(){return document.getElementById('upcomingEditor92')}
window.openUpcomingEditor92=function(){const f=upcomingForm();if(!f)return;f.hidden=false;f.dataset.edited='false';clearTimeout(upcomingTimer92);upcomingTimer92=setTimeout(()=>{if(f.dataset.edited!=='true')f.hidden=true},30000);f.scrollIntoView({behavior:'smooth',block:'start'});document.getElementById('recurringMemo')?.focus({preventScroll:true})};
window.closeUpcomingEditor92=function(){clearTimeout(upcomingTimer92);if(upcomingForm())upcomingForm().hidden=true};
const saveUpcoming=saveRecurringTransaction;
window.saveRecurringTransaction=function(...args){const before=RecurringStore.items.length;const result=saveUpcoming(...args);if(RecurringStore.items.length>before)closeUpcomingEditor92();return result};
function mountUpcoming(){const root=document.getElementById('transactions-recurring');if(!root||upcomingForm())return;const editor=root.querySelector(':scope>.je-card');editor.id='upcomingEditor92';editor.hidden=true;editor.addEventListener('input',()=>{editor.dataset.edited='true';clearTimeout(upcomingTimer92)});editor.addEventListener('change',()=>{editor.dataset.edited='true';clearTimeout(upcomingTimer92)});editor.addEventListener('click',event=>{if(event.target.closest('button')){editor.dataset.edited='true';clearTimeout(upcomingTimer92)}});
 const cancel=document.createElement('button');cancel.type='button';cancel.className='je-btn je-btn-secondary';cancel.textContent='Close';cancel.onclick=closeUpcomingEditor92;editor.querySelector('.je-card-header').append(cancel);
 const list=editor.nextElementSibling;const add=document.createElement('button');add.type='button';add.className='je-btn je-btn-emerald';add.textContent='Add Transaction';add.onclick=openUpcomingEditor92;list.querySelector('.je-card-header').append(add);
}
// Identical column definitions keep the requested and applied comparisons aligned.
window.adjustmentReport69=function(item){const lines=item.lines||[];const table=applied=>`<section class="adjustment-comparison92"><h3>${applied?'Applied to Live Activity':'Submitted Comparison'}</h3><div class="final-scroll-table final-four-column"><table><colgroup><col style="width:28%"><col style="width:24%"><col style="width:24%"><col style="width:24%"></colgroup><thead><tr><th>Activity</th>${(applied?['Current Before','Difference Applied','Current After']:['Original','Requested','Difference']).map(t=>`<th>${t}</th>`).join('')}</tr></thead><tbody>${lines.map(l=>`<tr><td>${escapeHtml(String(l.activity_key||'').replaceAll('_',' '))}</td>${(applied?[l.current_before,l.difference_applied,l.current_after]:[l.original_value,l.requested_value,l.difference]).map(n=>`<td>${formatAppNumber(Number(n)||0)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></section>`;return `<div class="adjustment-tables92">${table(false)}${item.status==='approved_applied'?table(true):''}</div><p class="final-record-note"><strong>Explanation:</strong> ${escapeHtml(item.explanation||'—')}<br><strong>Supporting report:</strong> ${escapeHtml(item.report_reference||'—')}<br><strong>Submitted:</strong> ${escapeHtml(item.submitted_at||'')}${item.reviewed_at?`<br><strong>Approved:</strong> ${escapeHtml(item.reviewed_at)} · ${escapeHtml(getLiveUserName(item.reviewed_by))}`:''}</p>`};
const auditDetails=auditComparisonHtml;
window.auditComparisonHtml=function(before,after,action){if(!before?.schedule_no&&!after?.schedule_no)return auditDetails(before,after,action);const fields=[['schedule_no','Schedule ID'],['title','Name'],['memo','Description'],['frequency','Frequency'],['start_date','First posting date'],['next_due','Next date'],['end_date','End date'],['debit_account_id','Debit account'],['credit_account_id','Credit account'],['amount','Debit amount'],['credit_amount','Credit amount'],['currency_code','Currency'],['auto_post','Automatic posting'],['status','Status']];const value=(r,k)=>{const v=r?.[k];if(v==null)return '—';if(k.endsWith('_account_id'))return AccountingStore.accounts.find(a=>a.id===v)?.name||v;return String(v)};return `<table class="audit-compare-table"><thead><tr><th>Schedule field</th><th>Original</th><th>Result</th></tr></thead><tbody>${fields.map(([k,label])=>`<tr><td>${label}</td><td>${escapeHtml(value(before,k))}</td><td>${escapeHtml(value(after,k))}</td></tr>`).join('')}</tbody></table>`};
function polish93(){mountUpcoming();
 document.querySelectorAll('.audit-summary-row').forEach(row=>{let item;try{item=JSON.parse(row.dataset.auditSearch||'{}')}catch{return}const action=String(item.action||'').toUpperCase();row.dataset.auditSeverity=/DELETE|REMOVE|PURGE/.test(action)?'destructive':/VOID/.test(action)?'void':/UPDATE|MODIFY|EDIT|ADJUST/.test(action)?'edit':'info'});
 // Preserve the original Home search and metrics; isolate just its title block.
 document.querySelectorAll('.v49-desktop-home-title:not([data-title93])').forEach(n=>{n.dataset.title93='true';const heading=document.createElement('div');heading.className='subuser-title93';const title=n.querySelector('h2'),subtitle=n.querySelector('p');if(title)heading.append(title);if(subtitle)heading.append(subtitle);n.prepend(heading)});
}
let queued=false;new MutationObserver(()=>{if(queued)return;queued=true;requestAnimationFrame(()=>{queued=false;polish93()})}).observe(document.body,{childList:true,subtree:true});polish93();
})();
