/* Approved print foundation. Rendering only: never changes payroll or journal amounts. */
(()=>{'use strict';
const esc=v=>escapeHtml(String(v??'')), num=v=>Number(v)||0, money=v=>formatAppNumber(num(v)), quantity=v=>num(v).toLocaleString(appNumberLocale(),{maximumFractionDigits:6});
const green='#176249',pale='#eaf1eb',line='#b8c8bd';
const textStyle='font-family:Arial,sans-serif;font-size:10pt;line-height:1.15;';
const cellStyle='border-bottom:0.5pt solid '+line+';padding:0.55mm 0.65mm;vertical-align:top;';
const safeColor=v=>/^#[0-9a-f]{3,8}$/i.test(v||'')?v:'#888888';
const heading=(text,n)=>`<h3 style="${textStyle}font-weight:bold;background-color:${green};color:white;padding:1mm 1.5mm;margin:2mm 0 1mm;break-after:avoid">${n?esc(n)+'. ':''}${esc(text)}</h3>`;
const title=(name,details)=>`<h1 style="${textStyle}font-size:15pt;color:${green};margin:0 0 1.5mm">${esc(name)}</h1><p style="${textStyle}margin:0 0 2mm">${esc(details)}</p>`;
function table(headers,rows,widths,options={}){return `<table style="${textStyle}width:100%;border-collapse:collapse;table-layout:fixed;margin:0 0 2mm">${widths?'<colgroup>'+widths.map(w=>`<col style="width:${w}%">`).join('')+'</colgroup>':''}<thead><tr>${headers.map(h=>`<th style="${cellStyle}background-color:${pale};text-align:left;font-weight:bold">${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>'<tr>'+r.map((v,i)=>`<td style="${cellStyle}${options.numeric?.includes(i)?'text-align:right;':''}">${options.raw?v:esc(v)}</td>`).join('')+'</tr>').join('')}</tbody></table>`;}
function settings(language='en'){const p=ApplicationSettings.printing||{},margin={narrow:8,normal:10,wide:22}[p.marginSize]||10;return {paper:'A4',orientation:'portrait',top:margin,bottom:margin,left:margin,right:margin,font:'Arial',size:language==='lo'?10.5:10,line:1.15,headerGap:2,footerGap:2,headerHeight:18,footerHeight:12,showBusinessName:false,pageNumbers:p.showPageNumbers!==false,headerImage:PrintSettings.headerImage||'',footerImage:PrintSettings.footerImage||''};}
const sign=(choices,receiver,id)=>typeof printSignatures1424==='function'?printSignatures1424(choices,receiver,id):'';
function journalTable(rows,withTotals=true){const groups=new Map(),totals=new Map();for(const r of [...rows].sort((a,b)=>String(a.date).localeCompare(String(b.date)))){const key=r.group||r.dbEntryId||r.id; if(!groups.has(key))groups.set(key,[]);groups.get(key).push(r);const c=r.currency||'LAK',t=totals.get(c)||{debit:0,credit:0};t.debit+=num(r.debit);t.credit+=num(r.credit);totals.set(c,t);}
const headers=['Date','Entry / reference','Account / description','Currency','Debit','Credit'];let html=`<table style="${textStyle}width:100%;border-collapse:collapse;table-layout:fixed;margin:0 0 2mm"><colgroup>${[12,17,37,9,12.5,12.5].map(w=>`<col style="width:${w}%">`).join('')}</colgroup><thead><tr>${headers.map(h=>`<th style="${cellStyle}text-align:left;background-color:${pale}">${esc(h)}</th>`).join('')}</tr></thead><tbody>`;
for(const group of groups.values()){
 const first=group[0],general=String(first.generalMemo||'').trim(),same=group.every(r=>String(r.memo||'').trim()===String(first.memo||'').trim()),shared=general||(same?String(first.memo||'').trim():'');
 if(shared)html+=`<tr><td style="${cellStyle}border-top:1pt solid ${green}">${esc(formatAppDate(first.date))}</td><td style="${cellStyle}border-top:1pt solid ${green}">${esc(first.id)}${first.reference?'<br>'+esc(first.reference):''}</td><td colspan="4" style="${cellStyle}border-top:1pt solid ${green};font-weight:bold">${esc(shared)}</td></tr>`;
 group.forEach((r,i)=>{const border=!shared&&i===0?'border-top:1pt solid '+green+';':'',memo=String(r.memo||'').trim();html+=`<tr>${i===0?`<td rowspan="${group.length}" style="${cellStyle}${border}">${shared?'':esc(formatAppDate(r.date))}</td><td rowspan="${group.length}" style="${cellStyle}${border}">${shared?'':esc(r.id)}${!shared&&r.reference?'<br>'+esc(r.reference):''}${r.source?'<br>'+esc(r.source):''}</td>`:''}<td style="${cellStyle}${border}">${esc([r.accountCode,r.account].filter(Boolean).join(' — '))}${memo&&memo!==shared?'<br><span style="font-size:9pt">'+esc(memo)+'</span>':''}</td><td style="${cellStyle}${border}">${esc(r.currency)}</td><td style="${cellStyle}${border}text-align:right">${num(r.debit)?money(r.debit):'—'}</td><td style="${cellStyle}${border}text-align:right">${num(r.credit)?money(r.credit):'—'}</td></tr>`;});}
html+='</tbody></table>';
if(withTotals&&totals.size)html+=`<table style="${textStyle}width:100%;border-collapse:collapse;table-layout:fixed;margin:1mm 0 3mm;border-top:1.5pt solid ${green};border-bottom:1.5pt solid ${green}"><colgroup><col style="width:66%"><col style="width:9%"><col style="width:12.5%"><col style="width:12.5%"></colgroup><thead><tr>${['Total for period','Currency','Debit','Credit'].map(h=>`<th style="${cellStyle}text-align:left">${esc(h)}</th>`).join('')}</tr></thead><tbody>${[...totals].map(([c,t])=>`<tr><td style="${cellStyle}">Total for period</td><td style="${cellStyle}">${esc(c)}</td><td style="${cellStyle}text-align:right">${money(t.debit)}</td><td style="${cellStyle}text-align:right">${money(t.credit)}</td></tr>`).join('')}</tbody></table>`;return html;}
function accountReport(pack){const j=pack.journal||{},accounts=pack.accounts||[],user=pack.user||{},name=id=>{const a=accounts.find(a=>String(a.id)===String(id));return a?[a.code,a.name].filter(Boolean).join(' — '):String(id||'Unassigned account');},source=(j.lines||[]).filter(l=>l.status!=='voided'&&!l.voided_at),rows=[],liquidation=new Map(),funds=new Map();
for(const l of source){const currency=l.currency_code||accounts.find(a=>String(a.id)===String(l.fund_account_id))?.currency_code||'LAK',amount=num(l.amount),incoming=l.direction==='in'||l.entry_kind==='collection',base={date:l.transaction_date,id:l.workspace_entry_no||l.id,group:l.id,reference:l.reference,memo:l.memo,currency};rows.push({...base,account:incoming?name(l.fund_account_id):name(l.account_id),debit:amount,credit:0},{...base,account:incoming?name(l.account_id):name(l.fund_account_id),debit:0,credit:amount});const key=l.fund_account_id+'|'+currency,f=funds.get(key)||{id:l.fund_account_id,currency,received:0,spent:0};f[incoming?'received':'spent']+=amount;funds.set(key,f);const k=key+'|'+l.account_id,t=liquidation.get(k)||{fund:l.fund_account_id,account:l.account_id,currency,received:0,spent:0};t[incoming?'received':'spent']+=amount;liquidation.set(k,t);}
const person=user.full_name||user.name||'Sub-user',period=String(j.period_start||'').slice(0,7),types=(j.report_types14253||[]).map(t=>t.name).filter(Boolean).join(' / '),reportTitle=types||'Sub-user Account Report';let html=title(reportTitle,person+' · '+period+' · '+(j.seed_key||j.id||'')+' · '+(j.status||''))+journalTable(rows,false);
html+=heading('Main account summary');const snapshot=pack.fund_snapshot14254;
if(Array.isArray(snapshot)){html+=table(['Main account','Currency','Opening','Received','Used','Handover','Closing'],snapshot.map(f=>[accounts.some(a=>String(a.id)===String(f.account_id||f.id))?name(f.account_id||f.id):(f.name||name(f.account_id||f.id)),f.currency,money(f.opening),money(f.received),money(f.used),money(f.handover),money(f.closing)]),[28,9,12,13,12,13,13],{numeric:[2,3,4,5,6]});html+=`<p style="${textStyle}font-size:9pt;margin:0 0 2mm">Posted ledger balances saved with this report${pack.fund_snapshot_at14254?' on '+esc(formatAppDate(pack.fund_snapshot_at14254,true)):''}. Report activity below may await posting.</p>`;}
else html+=table(['Main account','Currency','Opening','Received in report','Spent in report','Closing'],[...funds.values()].map(f=>[name(f.id),f.currency,'Not recorded',money(f.received),money(f.spent),'Not recorded']),[29,9,15,16,16,15],{numeric:[3,4]})+`<p style="${textStyle}font-size:9pt;margin:0 0 2mm">This earlier report has no saved opening or closing balances.</p>`;
html+=heading('Liquidation by account')+table(['Main account','Account / category','Currency','Received','Spent','Net activity'],[...liquidation.values()].map(t=>[name(t.fund),name(t.account),t.currency,money(t.received),money(t.spent),money(t.received-t.spent)]),[25,27,9,13,13,13],{numeric:[3,4,5]});
html+=sign({enabled:true,prepared:person,receiver:'',approver:pack.approver?.full_name||''});return {title:reportTitle+' '+period,category:'Reports',printPreview:true,approvedLayout14254:true,savedReport1434:true,reportSigner1434:person,reportApprover1434:pack.approver?.full_name||'',sourceJournal1434:j.id,html,settings:settings()};}
const lao={
'Salary Payment Voucher':'ໃບສຳຄັນຈ່າຍເງິນເດືອນ','Voucher number':'ເລກທີໃບສຳຄັນ','Salary month':'ເດືອນເງິນເດືອນ','Payment date':'ວັນທີຈ່າຍ','Currency':'ສະກຸນເງິນ','Employee':'ພະນັກງານ','Employee code':'ລະຫັດພະນັກງານ','Salary calculation':'ການຄິດໄລ່ເງິນເດືອນ','Description':'ລາຍການ','Amount':'ຈຳນວນເງິນ','Contract salary':'ເງິນເດືອນຕາມສັນຍາ','Overtime':'ຄ່າລ່ວງເວລາ','Taxable allowance':'ເງິນອຸດໜູນ','Internal deductions':'ລາຍການຫັກພາຍໃນ','Gross earnings':'ລາຍຮັບລວມ','Employee SSO':'ເງິນສົມທົບປະກັນສັງຄົມ','Employee PIT':'ອາກອນລາຍໄດ້','Reimbursement':'ເງິນຊົດເຊີຍ','Cash advance recovery':'ຫັກເງິນເບີກລ່ວງໜ້າ','Loan repayment':'ຊຳລະເງິນກູ້','Final payment':'ເງິນຈ່າຍສຸດທ້າຍ','Attendance record':'ບັນທຶກການມາເຮັດວຽກ','Attendance summary':'ສະຫຼຸບການມາເຮັດວຽກ','Item':'ລາຍການ','Days / count':'ວັນ / ຈຳນວນ','Minutes':'ນາທີ','Value':'ມູນຄ່າ','Deduction':'ເງິນຫັກ','Late time':'ມາຊ້າ','Absence':'ຂາດວຽກ','Paid leave / holiday':'ພັກທີ່ໄດ້ຮັບເງິນເດືອນ','Unpaid leave':'ພັກໂດຍບໍ່ຮັບເງິນເດືອນ','Reported missed time':'ບໍ່ໄດ້ບັນທຶກເວລາ ແລະ ແຈ້ງແລ້ວ','Unreported missed time':'ບໍ່ໄດ້ບັນທຶກເວລາ ແລະ ບໍ່ໄດ້ແຈ້ງ','Other attendance adjustments':'ການປັບປຸງການເຂົ້າວຽກອື່ນໆ','Total attendance deductions':'ລວມເງິນຫັກການເຂົ້າວຽກ','Actual / deductible':'ຕົວຈິງ / ທີ່ຖືກຫັກ','Present':'ມາເຮັດວຽກ','Late':'ມາຊ້າ','Non-work day':'ວັນພັກ','Paid holiday':'ວັນພັກທີ່ໄດ້ຮັບເງິນ','Paid leave':'ລາພັກທີ່ໄດ້ຮັບເງິນ','Unpaid absence':'ຂາດວຽກໂດຍບໍ່ຮັບເງິນ','Reported missed time tracking':'ບໍ່ໄດ້ບັນທຶກເວລາ ແລະ ແຈ້ງແລ້ວ','Unreported missed time tracking':'ບໍ່ໄດ້ບັນທຶກເວລາ ແລະ ບໍ່ໄດ້ແຈ້ງ','Excused late minutes':'ມາຊ້າທີ່ໄດ້ຮັບອະນຸຍາດ','Acknowledgment':'ການຢັ້ງຢືນການຮັບເງິນ','I acknowledge receipt of the final payment shown above.':'ຂ້າພະເຈົ້າຢັ້ງຢືນວ່າໄດ້ຮັບເງິນຈ່າຍສຸດທ້າຍຕາມທີ່ລະບຸຂ້າງເທິງ.','Prepared by':'ຜູ້ຈັດກຽມ','Verified by':'ຜູ້ກວດສອບ','Approved by':'ຜູ້ອະນຸມັດ','Received by':'ຜູ້ຮັບເງິນ','DRAFT — NOT FINALIZED':'ສະບັບຮ່າງ — ຍັງບໍ່ສຳເລັດ','FINALIZED':'ສຳເລັດແລ້ວ','SAMPLE — NOT FOR PAYMENT':'ຕົວຢ່າງ — ບໍ່ໃຊ້ສຳລັບຈ່າຍເງິນ','Included in salary; not added again.':'ລວມຢູ່ໃນເງິນເດືອນແລ້ວ; ບໍ່ໄດ້ບວກຊ້ຳ.','Not recorded':'ບໍ່ໄດ້ບັນທຶກ','Reference':'ເລກອ້າງອີງ'};
const tr=(s,lang)=>lang==='lo'?(lao[s]||s):s;
function translateHTML(html,lang){if(lang!=='lo')return html;const root=document.createElement('div');root.innerHTML=html;const walk=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);let n;while(n=walk.nextNode()){const s=n.textContent.trim();if(lao[s])n.textContent=n.textContent.replace(s,lao[s]);}for(const el of root.querySelectorAll('[style]'))if(el.style.fontSize==='10pt')el.style.fontSize='10.5pt';return root.innerHTML;}
function calendar(run){const [y,m]=run.month.split('-').map(Number);return Array.from({length:new Date(y,m,0).getDate()},(_,i)=>({day:i+1,date:run.month+'-'+String(i+1).padStart(2,'0'),weekday:new Date(y,m-1,i+1).getDay()}));}
const rules=run=>run.status==='finalized'?(run.legendSnapshot95||[]):payroll95.legends();
const leaves=run=>run.status==='finalized'?(run.leaveSnapshot||[]):(Work82.leaves||[]).map(r=>r.data);
function status(run,row,day){const a=(row.input.attendance||[]).find(a=>a.date===day.date);let parsed={minutes:0,rule:null};try{parsed=payroll95.parseMark(a?.mark95??a?.late??0,rules(run));}catch{}const leave=leaves(run).find(l=>l.employeeId===row.employeeId&&l.status==='approved'&&day.date>=l.from&&day.date<=l.to);let rule=parsed.rule;if(!a&&leave)rule=rules(run).find(r=>r.leaveType===leave.type)||{color:'#6366f1',description:leave.type};const off=(run.status==='finalized'?(run.nonWorkDays99||run.settingsSnapshot?.payroll?.nonWorkDays99||[]):ApplicationSettings.payroll.nonWorkDays99||[]).includes(day.weekday);return {color:rule?.color||(parsed.minutes>0?'#f59e0b':!a?'#94a3a0':'#22a06b'),label:rule?.description||(parsed.minutes>0?'Late':!a?(off?'Non-work day':'Not recorded'):'Present'),off};}
const dots=new Map();function dot(color){color=safeColor(color);if(!dots.has(color)){const c=document.createElement('canvas');c.width=24;c.height=24;const ctx=c.getContext('2d');ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(0,0,24,24,5);ctx.fill();dots.set(color,c.toDataURL('image/png'));}return `<img src="${dots.get(color)}" alt="" style="width:2.2mm;height:2.2mm;vertical-align:middle">`;}
function attendance(run,rows,language='en'){const days=calendar(run),legend=new Map();const html=`<table style="${textStyle}font-size:8pt;width:100%;border-collapse:collapse;table-layout:fixed;margin:0 0 1mm"><colgroup><col style="width:14%">${days.map(()=>`<col style="width:${86/days.length}%">`).join('')}</colgroup><thead><tr><th style="padding:0.7mm 0.3mm;background-color:${pale};text-align:left">${esc(tr('Employee code',language))}</th>${days.map(d=>`<th style="padding:0.7mm 0;background-color:${pale};text-align:center">${d.day}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr><td style="${cellStyle}padding:0.8mm 0.3mm">${esc(row.employee.code)}</td>${days.map(d=>{const s=status(run,row,d);legend.set(s.label,s.color);return `<td style="border-bottom:0.5pt solid ${line};padding:0.8mm 0;text-align:center;${s.off?'background-color:#f2f3f1;':''}">${dot(s.color)}</td>`;}).join('')}</tr>`).join('')}</tbody></table>`;return html+`<p style="${textStyle}font-size:8pt;margin:0 0 2mm">${[...legend].map(([s,c])=>dot(c)+' '+esc(tr(s,language))).join(' · ')}</p>`;}
function attendanceDetails(run,x){const row=run.rows.find(r=>r.employeeId===x.employeeId)||{input:{}},ds=x.attendance95||[],sum=(key,filter=()=>true)=>ds.filter(filter).reduce((n,d)=>n+num(d[key]),0),code=d=>String(d.mark||'').split(':')[0],rule=d=>rules(run).find(r=>r.code===code(d));const reported=d=>code(d)==='MTT',unreported=d=>['MMT','MT'].includes(code(d)),unpaid=d=>!!d.leaveType&&num(d.lostDays)>0;
let leaveDays=sum('lostDays',unpaid);const nw=run.status==='finalized'?(run.nonWorkDays99||run.settingsSnapshot?.payroll?.nonWorkDays99||[]):ApplicationSettings.payroll.nonWorkDays99||[];
for(const l of leaves(run).filter(l=>l.employeeId===x.employeeId&&l.status==='approved'&&l.month===run.month&&l.paid==='no')){const dates=[];for(let d=new Date(l.from+'T12:00:00');d<=new Date(l.to+'T12:00:00');d.setDate(d.getDate()+1)){if(!nw.includes(d.getDay()))dates.push(d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0'));}const overridden=new Set((row.input.attendance||[]).map(a=>a.date));if(dates.length)leaveDays+=num(l.days)*dates.filter(d=>!overridden.has(d)).length/dates.length;}
leaveDays=Math.min(num(x.unpaidDays),leaveDays);const leaveAmount=Math.min(num(x.absence),leaveDays*num(x.daily)),absenceAmount=num(x.absence)-leaveAmount;
const rep=sum('fixed',reported)+num(x.reportedMissed),unrep=sum('fixed',unreported)+num(x.unreportedMissed),other=sum('fixed',d=>!reported(d)&&!unreported(d))+sum('manual'),late=num(x.late)+num(x.latePenalty),total=late+num(x.absence)+rep+unrep+other;
const count=filter=>ds.filter(filter).length,chargeCount=(filter,extra)=>count(filter)+(num(extra)>0?' + charge':'');
return [
{label:'Late time',count:count(d=>num(d.minutes)>0),minutes:quantity(sum('minutes'))+' / '+quantity(x.minutes),value:null,deduction:late},
{label:'Absence',count:Math.max(0,num(x.unpaidDays)-leaveDays),value:null,deduction:absenceAmount},
{label:'Paid leave / holiday',count:num(x.paidLeaveDays),value:num(x.paidLeaveValue),deduction:0},
{label:'Unpaid leave',count:leaveDays,value:null,deduction:leaveAmount},
{label:'Reported missed time',count:chargeCount(reported,x.reportedMissed),value:null,deduction:rep},
{label:'Unreported missed time',count:chargeCount(unreported,x.unreportedMissed),value:null,deduction:unrep},
{label:'Other attendance adjustments',count:count(d=>num(d.manual)>0||num(d.fixed)>0&&!reported(d)&&!unreported(d)),value:null,deduction:other},
{label:'Total attendance deductions',count:'',value:null,deduction:total}];}
function attendanceSummary(run,results,language='en',compact=false){if(compact){const details=results.map(x=>({x,rows:attendanceDetails(run,x)}));const pair=d=>quantity(d.count)+' / '+money(d.deduction),first=table(['Employee code','Late minutes actual / deducted','Late deduction','Absence days / deduction','Paid leave days / value','Unpaid leave days / deduction'],details.map(({x,rows:r})=>[x.employee.code,r[0].minutes,money(r[0].deduction),pair(r[1]),quantity(r[2].count)+' / '+money(r[2].value),pair(r[3])]),[14,18,15,18,17,18]);return first+table(['Employee code','Reported missed count / deduction','Unreported missed count / deduction','Other attendance deductions','Total attendance deductions'],details.map(({x,rows:r})=>[x.employee.code,r[4].count+' / '+money(r[4].deduction),r[5].count+' / '+money(r[5].deduction),money(r[6].deduction),money(r[7].deduction)]),[14,23,23,20,20])+`<p style="${textStyle}font-size:9pt;margin:0 0 2mm">All deduction amounts and leave values are LAK. Paid leave is included in salary. “+ charge” means a separate charge without a recorded event count.</p>`;}const rows=results.flatMap(x=>attendanceDetails(run,x).map(d=>[tr(d.label,language),typeof d.count==='number'?quantity(d.count):d.count,d.minutes||'—',d.value===null?'—':money(d.value),money(d.deduction)]));return table(['Item','Days / count','Actual / deductible','Value','Deduction'].map(s=>tr(s,language)),rows,[35,12,19,17,17],{numeric:[1,3,4]})+`<p style="${textStyle}font-size:9pt;margin:0 0 2mm">${esc(tr('Included in salary; not added again.',language))} ${language==='lo'?'ມູນຄ່າ ແລະ ເງິນຫັກ: LAK.':'Values and deductions: LAK. Separate charges have no recorded event count.'}</p>`;}
function payroll(run,results){const internal=x=>num(x.late)+num(x.absence)+num(x.penalty)+num(x.other);let html=title('Payroll Calculation Report',run.month+' · '+run.reference+' · '+(run.status==='finalized'?'FINALIZED':'DRAFT — NOT FINALIZED'));
if(run.isSample)html+=`<p style="${textStyle}">SAMPLE — NOT FOR PAYMENT</p>`;
html+=heading('Payroll breakdown',1)+table(['Employee code','Contract / currency','Internal deductions · LAK','Gross · LAK','Taxable · LAK','Net · LAK'],results.map(x=>[x.employee.code,money(x.contract)+' '+x.currency,money(internal(x)),money(x.gross),money(x.taxable),money(x.net)]),[12,24,16,16,16,16],{numeric:[1,2,3,4,5]});
html+=heading('Mandatory deductions · LAK',2)+table(['Employee code','Employee PIT','Employer PIT','Employee SSO','Employer SSO','Employee total'],results.map(x=>[x.employee.code,money(x.employeePit),money(x.employerPit),money(x.employeeSso),money(x.employerSso),money(num(x.employeePit)+num(x.employeeSso))]),[14,17,17,17,17,18],{numeric:[1,2,3,4,5]});
html+=heading('Final payment',3)+table(['Employee code','Allowance · LAK','Reimbursement · LAK','Advance · LAK','Loan · LAK'],results.map(x=>[x.employee.code,money(x.allowance),money(x.reimbursement),money(x.cashAdvance??x.advance),money(x.loanRecovery)]),[14,21,23,21,21],{numeric:[1,2,3,4]})+table(['Employee code','Net · LAK','Final amount','Currency','LAK equivalent'],results.map(x=>[x.employee.code,money(x.net),money(x.paidAmount),x.currency,money(x.adjusted)]),[14,24,24,14,24],{numeric:[1,2,4]});
html+=(run.rows.length<=12?'<div style="break-inside:avoid">':'')+heading('Attendance record',4)+attendance(run,run.rows)+(run.rows.length<=12?'</div>':'')+heading('Attendance summary · LAK',5)+attendanceSummary(run,results,'en',true);
html+=heading('Other internal adjustments · LAK',6)+table(['Employee code','Additional penalty','Other deduction','Total internal deductions','Reference'],results.map(x=>[x.employee.code,money(x.manualPenalty),money(x.other),money(internal(x)),run.rows.find(r=>r.employeeId===x.employeeId)?.input.note||'—']),[14,19,19,23,25],{numeric:[1,2,3]});
html+=`<p style="${textStyle}font-size:9pt;margin:1mm 0">Rate date: ${esc(run.rateDate||'—')} · Source: ${esc(run.rateSource||'—')} · ${esc(run.notes||'')}</p>`;return html;}
function voucher(run,x,choices,language='en'){const internal=num(x.late)+num(x.absence)+num(x.penalty)+num(x.other),rate=num(x.rate);if(rate<=0)throw Error('Saved payroll exchange rate is missing.');const rows=[['Contract salary',x.contract],['Overtime',num(x.overtime)/rate],['Taxable allowance',num(x.allowance)/rate],['Internal deductions',-internal/rate],['Gross earnings',num(x.gross)/rate],['Employee SSO',-num(x.employeeSso)/rate],['Employee PIT',-num(x.employeePit)/rate],['Reimbursement',num(x.reimbursement)/rate],['Cash advance recovery',-num(x.cashAdvance??x.advance)/rate],['Loan repayment',-num(x.loanRecovery)/rate],['Final payment',x.paidAmount]];
let html=title(tr('Salary Payment Voucher',language),tr(run.isSample?'SAMPLE — NOT FOR PAYMENT':run.status==='finalized'?'FINALIZED':'',language));
html+=table(['Voucher number','Salary month','Payment date','Currency'].map(s=>tr(s,language)),[[run.reference+' / '+x.employee.code,run.month,run.paymentDate||tr('Not recorded',language),x.currency]],[37,21,26,16]);
html+=`<p style="${textStyle}margin:1mm 0 2mm"><strong>${esc(tr('Employee',language))}: ${esc(x.employee.name)}</strong> · ${esc(x.employee.code)} · ${esc(x.employee.position||'')}</p>`;
html+=heading(tr('Salary calculation',language),1)+table(['Description','Amount','Currency'].map(s=>tr(s,language)),rows.map(([s,v])=>[tr(s,language),money(v),x.currency]),[65,23,12],{numeric:[1]});
const employeeRow=run.rows.filter(r=>r.employeeId===x.employeeId);
html+=heading(tr('Attendance record',language),2)+attendance(run,employeeRow,language)+heading(tr('Attendance summary',language)+' · LAK',3)+attendanceSummary(run,[x],language);
html+=heading(tr('Acknowledgment',language),4)+`<p style="${textStyle}margin:1mm 0 2mm">${esc(tr('I acknowledge receipt of the final payment shown above.',language))}</p>`+sign(choices,x.employee.name,x.employeeId);return translateHTML(html,language);}
async function printPayroll(vouchers=false){try{const actor=liveProfile?.id,allowed=()=>['payroll-entries','payroll-history','report-payroll'].some(id=>access113.can(id,'view')&&access113.can(id,'export'));if(!actor||!allowed())throw Error('Payroll view and print permission are required.');if(!Work82.run)throw Error('Open a payroll month first.');if(Work82.run.status!=='finalized')updateRun82();const run=structuredClone(Work82.run),results=runResults82(run);if(!results.length)throw Error('This payroll has no employees.');if(vouchers){const receivers=results.map(voucherSignatories1433.receiver),choices=await choosePrintSignatories1424({voucherOnly1433:true,receivers,actionLabel:'Open vouchers'});if(!choices)return;if(liveProfile?.id!==actor||!allowed())throw Error('Your account or payroll access changed. Open the report again.');const languages=Object.fromEntries(results.map(x=>[x.employeeId,(x.employee.voucherLanguage||Work82.employees?.find(e=>e.id===x.employeeId)?.data?.voucherLanguage)==='lo'?'lo':'en']));choices.voucherLanguages14254=languages;return openDocumentEditor105({title:'Salary Vouchers '+run.month,category:'Payroll',printPreview:true,approvedLayout14254:true,payrollVouchers:true,payrollReceivers1433:receivers,voucherSignatories1433:choices,voucherLanguages14254:languages,receiverName:results.length===1?results[0].employee.name:'',html:results.map(x=>voucher(run,x,choices,languages[x.employeeId])).join('<div data-page-break="1"></div>'),settings:settings(Object.values(languages).includes('lo')?'lo':'en')});}
return openDocumentEditor105({title:'Payroll Calculation Report '+run.month,category:'Payroll',source:'payroll-entries',printPreview:true,approvedLayout14254:true,html:payroll(run,results)+sign({enabled:true,prepared:run.finalizedBy||liveProfile.full_name||liveProfile.email,receiver:'',approver:''}),settings:settings()});}catch(e){showCenterStatus(e.message,true);}}
async function printJournal(){try{const actor=liveProfile?.id,source=document.querySelector('.tab-content.active')?.id;if(!source||!access113.can(source,'view')||!access113.can(source,'export'))throw Error('Journal view and print permission are required.');const available=[...new Set(JournalModule.entries.map(r=>String(r.date).slice(0,7)))].sort().reverse(),current=document.getElementById('journalMonthFilter')?.value||new Date().toISOString().slice(0,7);const pending=ui108.modal('Journal report',`<label>Report month <input type="month" id="reportMonth14254" value="${esc(available.includes(current)?current:available[0]||current)}" required></label>`,[{label:'Cancel',value:false},{label:'Open report',value:true,primary:true}],true);const input=document.getElementById('reportMonth14254');if(!await pending)return;if(liveProfile?.id!==actor||!access113.can(source,'export'))throw Error('Your account or journal access changed. Open the report again.');const month=input.value;if(!/^\d{4}-\d{2}$/.test(month))throw Error('Select a report month.');const rows=JournalModule.entries.filter(r=>String(r.date).slice(0,7)===month);if(!rows.length)throw Error('No posted entries in this month.');return openDocumentEditor105({title:'Journal Report '+month,category:'Transactions',source,printPreview:true,approvedLayout14254:true,html:title('Journal Report',month)+journalTable(rows)+sign({enabled:true,prepared:liveProfile.full_name||liveProfile.email,receiver:'',approver:''}),settings:settings()});}catch(e){showCenterStatus(e.message,true);}}
async function historyPicker(host){
 if(!host?.isConnected||host.querySelector('[data-report-period14254]')||host.reportPeriodLoading14254||!host.querySelector('.report-history-row1443'))return;
 host.reportPeriodLoading14254=true;const actor=liveProfile?.id;
 try{const rows=await reportHistory1443.load();if(liveProfile?.id!==actor||!host.isConnected)return;
 const periods=new Map(rows.map(r=>[r.journal_id,String(r.period_start||'').slice(0,7)]));
 for(const r of rows.filter(r=>!periods.get(r.journal_id))){const result=await ojmDb.rpc('approved_report1443',{p_journal:r.journal_id});if(liveProfile?.id!==actor||!host.isConnected)return;if(!result.error)periods.set(r.journal_id,String(result.data?.journal?.period_start||'').slice(0,7));}
 for(const j of reviewStaffJournals||[])if(!periods.has(j.id))periods.set(j.id,String(j.period_start||'').slice(0,7));
 const reportRows=[...host.querySelectorAll('.report-history-row1443')];for(const row of reportRows){const button=row.querySelector('[data-open-report1443],[data-legacy-report1443]');row.dataset.reportMonth14254=periods.get(button?.dataset.openReport1443||button?.dataset.legacyReport1443)||'';}
 const label=document.createElement('label');label.dataset.reportPeriod14254='1';label.textContent='Report month ';const select=document.createElement('select');select.setAttribute('aria-label','Report history month');select.innerHTML='<option value="">All months</option>'+[...new Set(reportRows.map(r=>r.dataset.reportMonth14254).filter(Boolean))].sort().reverse().map(m=>'<option value="'+esc(m)+'">'+esc(m)+'</option>').join('');label.append(select);host.querySelector('h3')?.after(label);select.onchange=()=>reportRows.forEach(row=>row.hidden=!!select.value&&row.dataset.reportMonth14254!==select.value);
 }catch(e){if(host.isConnected&&liveProfile?.id===actor){const p=document.createElement('p');p.dataset.reportPeriod14254='1';p.setAttribute('role','status');p.textContent='Month filter unavailable: '+e.message;host.querySelector('h3')?.after(p);}}finally{host.reportPeriodLoading14254=false;}
}
function installSavedReports(){
 // Public hooks only: leave the original mixed-purpose application bundle intact.
 savedReports1434.model=accountReport;
 const marker='<!-- approved-report14254 -->',clean=window.cleanPrint1434;window.cleanPrint1434=html=>String(html).startsWith(marker)?String(html).slice(marker.length):clean(html);
 const choose=window.choosePrintSignatories1424;window.choosePrintSignatories1424=async function(options={}){const result=await choose.call(this,options);if(result&&options.previous?.voucherLanguages14254)result.voucherLanguages14254=structuredClone(options.previous.voucherLanguages14254);return result;};
 const open=window.openDocumentEditor105;
 window.openDocumentEditor105=async function(options={}){
  if(options.savedReport1434&&options.sourceJournal1434&&!options.approvedLayout14254){const actor=liveProfile?.id;try{const result=await ojmDb.rpc('staff_report1434',{p_journal:options.sourceJournal1434});if(result.error)throw result.error;if(!actor||liveProfile?.id!==actor)throw Error('Your account changed. Open the report again.');options={...options,...accountReport(result.data)};}catch(e){showCenterStatus('Report could not be opened: '+e.message,true);return;}}
  if(options.approvedLayout14254&&!options.payrollVouchers)options={...options,html:marker+options.html};
  return open.call(this,options);
 };
 const render=reportHistory1443.render;reportHistory1443.render=async function(userId,host){const result=await render.call(this,userId,host);if(host)await historyPicker(host);return result;};
 reportHistory1443.open=function(userId){ui108.modal('Report History','<div id="reportHistory1443"></div>',undefined,true);return reportHistory1443.render(userId,document.getElementById('reportHistory1443'));};
 // Existing buttons also retain private callbacks; decorate their rendered history.
 let pending=false;new MutationObserver(()=>{if(pending)return;pending=true;requestAnimationFrame(()=>{pending=false;for(const row of document.querySelectorAll('.report-history-row1443')){const host=row.parentElement;if(host.querySelector('h3'))void historyPicker(host);}});}).observe(document.body,{childList:true,subtree:true});
}
function ready(){installSavedReports();const oldSign=window.printSignatures1424;window.printSignatures1424=function(...args){const html=oldSign(...args).replaceAll('margin-top:22mm','margin-top:3mm').replaceAll('gap:12mm','gap:8mm').replaceAll('height:9mm','height:6mm');return translateHTML(html,args[0]?.voucherLanguages14254?.[args[2]||'']);};
const form=window.employeeForm82;window.employeeForm82=function(record){return form(record).replace('<div class="form-actions82">',`<div class="fields82"><label>Salary voucher language<select name="voucherLanguage"><option value="en" ${record?.data?.voucherLanguage!=='lo'?'selected':''}>English</option><option value="lo" ${record?.data?.voucherLanguage==='lo'?'selected':''}>Lao</option></select></label></div><div class="form-actions82">`);};
const render=window.renderWork82;window.renderWork82=function(...args){const result=render.apply(this,args);for(const id of ['payroll-history','report-payroll']){const panel=document.getElementById(id);if(!panel||!panel.querySelector('table')||panel.querySelector('[data-payroll-month14254]'))continue;const label=document.createElement('label');label.dataset.payrollMonth14254='1';label.textContent='Report month ';const input=document.createElement('input');input.type='month';input.setAttribute('aria-label','Payroll history month');label.append(input);panel.querySelector('table').parentElement.before(label);input.onchange=()=>{for(const row of panel.querySelectorAll('tbody tr'))row.hidden=!!input.value&&!row.textContent.includes(input.value);};}return result;};
window.printPayroll82=printPayroll;window.printPayrollBody99=run=>payroll(run,runResults82(run));window.payrollVoucherPreview1424=(run,x,choices)=>voucher(run,x,choices,(x.employee.voucherLanguage||Work82.employees?.find(e=>e.id===x.employeeId)?.data?.voucherLanguage)==='lo'?'lo':'en');
const oldPrint=window.print,oldCopy=window.copyReportToEditor105;const route=()=>{const id=document.querySelector('.tab-content.active')?.id;if(['journal','transactions-all','transactions-new'].includes(id))return printJournal;if(id==='payroll-entries')return ()=>printPayroll(false);return null;};window.print=function(...args){const action=route();return action?action():oldPrint.apply(this,args);};window.copyReportToEditor105=function(...args){const action=route();return action?action():oldCopy.apply(this,args);};
}
window.reports14254={settings,table,journalTable,accountReport,calendar,status,attendance,attendanceDetails,attendanceSummary,payroll,voucher,translateHTML,printPayroll,printJournal};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
