/* One comparative model for screen, CSV, print and document editor. */
(function(){'use strict';
const baseModel=reportModel79,baseContent=reportContent79,baseTable=reportTable79;let firstBalance=true;
const side=n=>n>0?'DR':n<0?'CR':'—';
function periods(){const s=Reports79;let year=+s.year,month=1,step=12;if(s.mode==='monthly'){[year,month]=s.month.split('-').map(Number);step=1}else if(s.mode==='quarterly'){month=(+s.quarter-1)*3+1;step=3}else if(s.mode==='custom'){const end=new Date(s.to+'T00:00:00Z'),days=Math.round((end-new Date(s.from+'T00:00:00Z'))/86400000)+1;return [2,1,0].map(i=>{const to=new Date(end-i*days*86400000),from=new Date(to-(days-1)*86400000);return{from:from.toISOString().slice(0,10),to:to.toISOString().slice(0,10),label:from.toISOString().slice(0,10)+' – '+to.toISOString().slice(0,10)}})}return [2,1,0].map(i=>{const start=new Date(Date.UTC(year,month-1-i*step,1)),end=new Date(Date.UTC(start.getUTCFullYear(),start.getUTCMonth()+step,0));return{from:start.toISOString().slice(0,10),to:end.toISOString().slice(0,10),label:step===3?'Q'+(Math.floor(start.getUTCMonth()/3)+1)+' '+start.getUTCFullYear():step===12?String(start.getUTCFullYear()):start.toLocaleDateString('en-GB',{month:'short',year:'numeric',timeZone:'UTC'})}})}
window.reportModel79=function(kind,oldest=false){if(kind!=='bs'){const groups=baseModel(kind,oldest);if(['gl','activity'].includes(kind))for(const g of groups){g.headers[g.headers.length-1]='Running amount';g.values.forEach(r=>{const value=r.at(-1),match=String(value).match(/\s(DR|CR)$/);r[2]=(match?match[1]:'—')+' · '+r[2];r[r.length-1]=String(value).replace(/\s(DR|CR)$/,'')})}return groups}const old={...Reports79},p=periods();let models;try{models=p.map(period=>{Object.assign(Reports79,{from:period.from,to:period.to});return baseModel('bs',oldest)})}finally{Object.assign(Reports79,old)}const currencies=[...new Set(models.flatMap(m=>m.map(g=>g.currency)))];return currencies.map(currency=>{const group=models.map(m=>m.find(g=>g.currency===currency)),keys=[...new Set(group.flatMap(g=>(g?.values||[]).map(r=>JSON.stringify(r.slice(0,2)))))];return{currency,headers:['Classification','Account',...p.map(x=>x.label)],values:keys.map(k=>[...JSON.parse(k),...group.map(g=>g?.values.find(r=>JSON.stringify(r.slice(0,2))===k)?.[2]||money69(0))]),metrics:group[2]?.metrics||[],note:'Three consecutive '+(Reports79.mode==='quarterly'?'quarters':Reports79.mode==='monthly'?'months':'periods')+', ending with the selected period. Each column shows the position at that period end; unclosed accumulated result is included once. '+(group[2]?.note||'')}})};
window.reportContent79=function(kind,oldest=false){if(kind!=='bs')return baseContent(kind,oldest);return reportModel79(kind,oldest).map(g=>`<section class="r79-group statement82"><h4>${re79(g.currency)} · Balance Sheet</h4>${['ASSET','LIABILITY','EQUITY'].map(type=>{const rows=g.values.filter(r=>r[0]===type),total=[2,3,4].map(i=>money69(rows.reduce((n,r)=>n+Math.round(Number(String(r[i]).replaceAll(',',''))*100),0)));return `<section class="statement-section82"><h5>${re79(type)}</h5>${reportTable79(g.headers.slice(1),[...rows.map(r=>r.slice(1)),['Total '+type.toLowerCase(),...total]],g.currency,oldest)}</section>`}).join('')}<div class="r79-metrics">${g.metrics.map(([k,v])=>`<div><small>${re79(k)}</small><strong>${money69(v)}</strong></div>`).join('')}</div><p class="r79-note">${re79(g.note)}</p></section>`).join('')};
window.reportTable79=function(headers,rows,currency,print=false){const html=baseTable(headers,rows,currency,print);const t=document.createElement('template');t.innerHTML=html;t.content.querySelectorAll('tbody tr').forEach((tr,index)=>{[...tr.cells].forEach((td,i)=>{if(!['Classification','Account'].includes(headers[i]))return;const raw=String(rows[index]?.[i]||''),m=raw.match(/^(DR|CR|—) · (.*)$/);if(!m)return;const link=td.querySelector('button');if(link){link.textContent=m[2];link.dataset.account=m[2]}else td.textContent=m[2];const b=document.createElement('span');b.className='balance-badge118';b.style.cssText='display:inline-block;border:1px solid #93a993;border-radius:4px;padding:2px 5px;margin-right:7px;font-size:10px;white-space:nowrap';b.textContent=m[1];b.title='Balance side';td.prepend(b)})});return t.innerHTML};
const sw=switchTab;window.switchTab=function(id,...args){if(id==='report-bs'&&firstBalance){firstBalance=false;Reports79.mode='quarterly';reportRange79()}return sw.call(this,id,...args)};
window.reportPeriods118=periods;
})();
