/* v113: one page hierarchy, saved presentation settings, contextual header artwork. */
(function(){'use strict';
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const areas={dashboard:['Dashboard','See the whole picture. Take the next good step.','A clear view of the work we share.'],transactions:['Transactions','Count with care. Record with purpose.','Journal, review and period closing.'],accounts:['Accounts','A balanced record supports a sound decision.','Your ledger, balances and account structure.'],'sub-users':['Sub-users','Shared responsibility begins with clear records.','Assigned funds and accountable teamwork.'],hr:['Human Resources','Care for the people behind the work.','People, attendance and shared commitments.'],payroll:['Payroll','Careful preparation. Fair recognition.','Salary calculations and payment history.'],reports:['Reports','Understand the story behind the numbers.','Review performance and make informed decisions.'],'tax-sso':['Tax & Social Security','Prepare carefully. Meet each commitment.','Tax records, contributions and payments.'],settings:['Settings','A thoughtful setup makes everyday work easier.','Company preferences, access and recovery.'],documents:['Document Editor','Give each idea a clear place on the page.','Create and maintain company documents.']};
const palettes={Ivory:'#fffaf1',Sand:'#eddfc5',White:'#ffffff',Sage:'#e4ecdf',Gold:'#ecce88'};
const state={owner:null,rows:{},loaded:false,error:'',busy:false};
const active=()=>$('.tab-content.active');const admin=()=>typeof liveProfile!=='undefined'&&liveProfile?.role==='admin';
function area(node=active()){const id=node?.id||'';if(id==='hr-calendar')return'local-events';if(id==='document-editor105')return'documents';if(id.startsWith('hr-')||id==='payroll-employees')return'hr';if(id.startsWith('report-'))return'reports';if(id.startsWith('settings-'))return'settings';if(id.startsWith('menu-'))return'menu';if(id.startsWith('inv-'))return'inventory';if(id.includes('sub-user'))return'sub-users';if(id==='trial-balance'||id==='account-balances'||id==='accounts-modular-container')return'accounts';return node?.dataset.module||'transactions'}
async function load(force=false){const owner=typeof liveProfile!=='undefined'?liveProfile?.id:null;if(!owner||!window.ojmDb&&typeof ojmDb==='undefined'||state.busy)return;if(state.loaded&&state.owner===owner&&!force)return;state.busy=true;if(state.owner!==owner){state.rows={};state.photo='';state.loaded=false}state.owner=owner;try{const r=await ojmDb.from('presentation_settings113').select('*');if(r.error)throw r.error;if(liveProfile?.id!==owner)return;state.rows=Object.fromEntries((r.data||[]).map(x=>[x.area,x.data]));state.loaded=true;state.error='';ojmDb.rpc('employee_photo113',{p_user:owner}).then(photo=>{if(liveProfile?.id===owner&&!photo.error){state.photo=photo.data||'';window.updateHeaderProfile104?.()}});window.dispatchEvent(new Event('presentation-ready113'));sync()}catch(e){state.error=e.message}finally{state.busy=false}}
async function save(key,data){if(!admin())throw Error('Administrator access required.');const r=await ojmDb.from('presentation_settings113').upsert({area:key,data,updated_by:liveProfile.id,updated_at:new Date().toISOString()});if(r.error)throw Error('Could not save appearance. '+r.error.message);state.rows[key]=data;sync()}
async function saveMany(rows){if(!admin())throw Error('Administrator access required.');const r=await ojmDb.from('presentation_settings113').upsert(Object.entries(rows).map(([area,data])=>({area,data,updated_by:liveProfile.id,updated_at:new Date().toISOString()})));if(r.error)throw Error('Could not save appearance. '+r.error.message);Object.assign(state.rows,rows);sync();window.dispatchEvent(new Event('presentation-ready113'));}
function iconPath(key){return ({pos:'M2 3h3l3 13h11l3-9H6 M9 20h.01 M18 20h.01',transactions:'M5 3h14v18H5z M8 7h8 M8 11h8 M8 15h5',accounts:'M3 9h18 M5 9v10 M10 9v10 M15 9v10 M20 9v10 M2 21h20 M3 6l9-4 9 4',hr:'M8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M1 21v-3a7 7 0 0 1 14 0v3 M17 4a4 4 0 0 1 0 8 M18 15a5 5 0 0 1 5 5',payroll:'M3 5h18v14H3z M3 9h18 M7 15h4',reports:'M3 2v20h19 M7 18v-7 M12 18V6 M17 18v-10',inventory:'M3 7l9-4 9 4v11l-9 4-9-4z M3 7l9 5 9-5 M12 12v10',menu:'M5 2v8h6V2 M8 2v20 M19 2c-4 3-4 7-4 11h4v9V2',settings:'M4 7h16 M4 17h16 M8 3v8 M16 13v8',documents:'M5 2h9l5 5v15H5z M14 2v5h5 M8 12h8 M8 16h8','sub-users':'M8 10a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M2 22v-3a6 6 0 0 1 12 0v3 M17 7h5 M17 12h5 M17 17h5','tax-sso':'M12 2L3 6v6c0 5 5 8 9 10 4-2 9-5 9-10V6z M7 12l3 3 7-7',dashboard:'M3 11l9-9 9 9 M5 10v12h14V10 M10 22v-7h4v7'})[key]||'M4 4h16v16H4z'}
function svg(key){return `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${iconPath(key)}"/></svg>`}
function addSettings(id,label){const nav=$('#nav-module-settings .nav-links');if(!document.getElementById(id)){const b=document.createElement('button');b.type='button';b.className='tab-btn';b.textContent=label;b.setAttribute('onclick',`switchTab('${id}')`);nav?.append(b);const section=document.createElement('div');section.id=id;section.dataset.module='settings';section.className='tab-content';$('#settings-system')?.parentElement.append(section);const tree=typeof APP_PERMISSION_TREE!=='undefined'?APP_PERMISSION_TREE.find(x=>x.id==='settings'):null;tree?.children.push([id,label])}}
function currentTabId(node,key){if(key==='accounts'&&node?.id==='accounts-modular-container')return (document.querySelector('#nav-module-accounts .tab-btn.active')?.getAttribute('onclick')||'').match(/scrollToAccountModule\('([^']+)'\)/)?.[1]||node.id;return node?.id||''}
function tabLabel14311(button){if(!button)return '';const copy=button.cloneNode(true);copy.querySelectorAll('.nav-count14311,.submission-count-badge').forEach(n=>n.remove());return copy.textContent.trim().replace(/\s+/g,' ')}
function tabName(node,key){const id=currentTabId(node,key),nav=document.querySelector('#nav-module-'+key);const button=[...(nav?.querySelectorAll('.tab-btn')||[])].find(b=>(b.getAttribute('onclick')||'').includes("('"+id+"')"));return tabLabel14311(button)||areas[key]?.[0]||id}
function tabChoices(key){if(key==='dashboard')return ['Home','Finance','People','Operation','Compliance','Documents'].map(x=>['dashboard-'+x.toLowerCase(),x]);const nav=document.querySelector('#nav-module-'+key);const seen=new Set();return [...(nav?.querySelectorAll('.tab-btn')||[])].map(b=>{const id=(b.getAttribute('onclick')||'').match(/(?:switchTab|scrollToAccountModule)\('([^']+)'\)/)?.[1];if(!id||seen.has(id))return null;seen.add(id);return [id,tabLabel14311(b)]}).filter(Boolean)}
// Share one optimized image across every area.
function defaultPhoto(){return 'assets/banners/transactions.webp'}
function form(){const host=$('#settings-appearance113');if(!host||host.dataset.ready113)return;host.dataset.ready113='1';host.innerHTML=`<section class="panel113"><header><h2>Banner</h2></header><p>The Transactions image is shared across the website. Drag the preview to adjust its position in this area.</p><form id="appearanceForm113"><div class="form113"><label>Main area<select name="area">${Object.entries(areas).map(([k,v])=>`<option value="${k}">${v[0]}</option>`).join('')}</select></label><label>Tab<select name="tab"></select></label><label>Horizontal position<input name="position" type="range" min="0" max="100" value="70"></label><label>Vertical position<input name="positionY14229" type="range" min="0" max="100" value="50"></label></div><div class="banner-preview113" role="img" aria-label="Banner preview. Drag vertically to reposition the image." style="touch-action:none;cursor:grab"></div><footer><button type="button" data-center14229>Center image</button><button type="button" data-default113>Use default</button><button type="submit" class="primary113">Save banner</button></footer><p role="status"></p></form></section>`;const f=$('#appearanceForm113'),status=f.querySelector('[role=status]'),p=f.querySelector('.banner-preview113');let selectedImage='',imageSize=null,previewSource='',imageToken=0;const selectedKey=()=>f.elements.tab.value?f.elements.area.value+':'+f.elements.tab.value:f.elements.area.value;
 const fillTabs=()=>{f.elements.tab.innerHTML='<option value="">All tabs in this main area</option>'+tabChoices(f.elements.area.value).map(([id,label])=>`<option value="${esc(id)}">${esc(label)}</option>`).join('')};
 const preview=()=>{const src=defaultPhoto();p.style.backgroundImage=`url("${src}")`;p.style.backgroundSize='cover';p.style.backgroundPosition=`${f.elements.position.value}% ${f.elements.positionY14229.value}%`;if(src!==previewSource){previewSource=src;imageSize=null;const token=++imageToken;const im=new Image();im.onload=()=>{if(token===imageToken)imageSize={w:im.naturalWidth,h:im.naturalHeight}};im.src=src;}};
 const paint=()=>{const d=state.rows[selectedKey()]||{},fallback=state.rows[f.elements.area.value]||{};selectedImage=d.image??fallback.image??'';f.elements.position.value=d.position??fallback.position??70;f.elements.positionY14229.value=d.positionY14229??fallback.positionY14229??50;preview()};
 f.elements.area.onchange=()=>{fillTabs();paint()};f.elements.tab.onchange=paint;f.elements.position.oninput=preview;f.elements.positionY14229.oninput=preview;
 p.onpointerdown=e=>{if(!imageSize)return;e.preventDefault();const box=p.getBoundingClientRect(),scale=Math.max(box.width/imageSize.w,box.height/imageSize.h),overflow=scale*imageSize.h-box.height,start=e.clientY,startY=Number(f.elements.positionY14229.value);p.setPointerCapture(e.pointerId);p.style.cursor='grabbing';p.onpointermove=ev=>{if(overflow>1){f.elements.positionY14229.value=Math.max(0,Math.min(100,startY-(ev.clientY-start)/overflow*100));preview()}else status.textContent='The full image height is already visible. A taller image allows vertical movement.'};const stop=()=>{p.onpointermove=null;p.onpointerup=null;p.onpointercancel=null;p.style.cursor='grab'};p.onpointerup=stop;p.onpointercancel=stop;};
 f.querySelector('[data-center14229]').onclick=()=>{f.elements.position.value=50;f.elements.positionY14229.value=50;preview()};f.querySelector('[data-default113]').onclick=()=>{selectedImage='';f.elements.position.value=70;f.elements.positionY14229.value=50;preview()};
 f.onsubmit=async e=>{e.preventDefault();const b=f.querySelector('[type=submit]');b.disabled=true;try{window.status118?.pending('Saving banner…');const key=selectedKey(),data={...(state.rows[key]||{}),image:'',position:Number(f.elements.position.value),positionY14229:Number(f.elements.positionY14229.value)};await saveMany({[key]:data});status.textContent='Banner saved for the company.';showCenterStatus('Banner saved.')}catch(e){status.textContent=e.message;showCenterStatus(e.message,true)}finally{b.disabled=false}};fillTabs();paint();window.addEventListener('presentation-ready113',()=>{if(!f.contains(document.activeElement))paint()});if(!state.loaded)load().then(paint)}
async function resize(file){if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>10*1024*1024)throw Error('Choose a PNG, JPEG or WebP under 10 MB.');const img=await createImageBitmap(file),c=document.createElement('canvas'),scale=Math.min(1,1600/img.width,900/img.height);c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);img.close();return c.toDataURL('image/webp',.82)}
function logo(){const brand=$('.sidebar-brand'),image=$('#companyLogo101');if(!brand)return;let tile=$('.logo-tile113');if(!tile){tile=document.createElement('button');tile.type='button';tile.className='logo-tile113';tile.title='Click to change logo background';tile.setAttribute('aria-label','Choose company logo background');brand.prepend(tile);tile.onclick=()=>{if(!admin())return;ui108.modal('Logo background',`<p>Choose a background for your green company logo.</p><div class="logo-options113">${Object.entries(palettes).map(([name,color])=>`<button type="button" style="background:${color}" data-logo113="${name}">${name}</button>`).join('')}</div>`,[{label:'Close',value:false}]);const root=$('.ui-overlay108:last-child');root.querySelectorAll('[data-logo113]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.logo113===(state.rows.brand?.background||'Ivory')));b.onclick=async()=>{const previous=tile.style.backgroundColor;tile.style.backgroundColor=palettes[b.dataset.logo113];root.querySelectorAll('[data-logo113]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));b.disabled=true;try{await save('brand',{...(state.rows.brand||{}),background:b.dataset.logo113});root.resolve108(true)}catch(e){tile.style.backgroundColor=previous;let status=root.querySelector('[data-logo-error117]');if(!status){status=document.createElement('p');status.dataset.logoError117='';status.setAttribute('role','alert');root.querySelector('.ui-body108').append(status)}status.textContent='Could not save the logo background. '+e.message}finally{b.disabled=false}}})}}if(image&&image.parentElement!==tile)tile.append(image);if(!image||image.hidden){if(!tile.querySelector('span')){const text=document.createElement('span');text.textContent='OJ';tile.append(text)}}else tile.querySelector('span')?.remove();if(image&&state.rows.brand&&'image' in state.rows.brand){const src=state.rows.brand.image||'';if(image.getAttribute('src')!==src){image.src=src;image.hidden=!src}}const color=palettes[state.rows.brand?.background]||palettes.Ivory;if(tile.style.backgroundColor!==color)tile.style.backgroundColor=color;tile.disabled=!admin();brand.querySelector('.brand-monogram108')?.remove()}
function decorateBanner(node,key){let b=node.querySelector('.area-banner113');if(b&&b.parentElement!==node)node.prepend(b);node.querySelectorAll('.area-banner113').forEach(other=>{if(other!==b)other.remove()});if(!b){b=document.createElement('section');b.className='area-banner113';b.innerHTML='<div class="banner-copy113"><h1></h1><p></p></div><div class="banner-art113" aria-hidden="true"></div>';node.prepend(b)}const values=areas[key]||areas.transactions,tabId=currentTabId(node,key),override=state.rows[key+':'+tabId]||{},base=state.rows[key]||{},d={...base,...override},signature=JSON.stringify([key,tabId,d]);if(b.dataset.signature===signature)return;b.dataset.signature=signature;b.dataset.module=key;b.querySelector('h1').innerHTML=`<span class="banner-icon113">${svg(key)}</span><span>${esc(tabName(node,key))}</span>`;b.querySelector('p').textContent=values[2];b.querySelectorAll('blockquote').forEach(q=>q.remove());b.querySelector('.banner-art113').innerHTML=svg(key);b.style.backgroundImage=`linear-gradient(90deg,#fcf5e9f5 0%,#fcf5e9d9 38%,#fcf5e94a 75%,transparent 100%),url("${defaultPhoto(key,tabId)}")`;b.style.backgroundPosition=`center,${d.position??70}% ${d.positionY14229??50}%`;b.querySelector('.banner-art113').hidden=!!d.image;}
function sync(){const root=active();if(!root)return;const key=area(root);root.style.setProperty('padding',key==='dashboard'?'0':document.documentElement.dataset.device132==='desktop'?'14px 0 14px 16px':'14px 16px','important');if(key==='documents'){const sh=$('#categoryTabShell'),tabs=$('#categoryTabs');if(sh)sh.hidden=false;if(tabs&&!tabs.querySelector('[data-doc-nav113]'))tabs.innerHTML='<button type="button" class="category-tab active" data-doc-nav113>Document Editor</button>'}const tabShell=$('#categoryTabShell'),tabList=$('#categoryTabs');if(tabShell?.hidden&&!['dashboard','sub-users','pos'].includes(key)){tabShell.hidden=false;const nav=$('#nav-module-'+key+' .nav-links');if(nav&&tabList){tabList.replaceChildren();[...nav.querySelectorAll('button')].filter(b=>!b.hidden).forEach(b=>{const copy=b.cloneNode(true);copy.className='category-tab';copy.hidden=false;tabList.append(copy)})}}document.body.dataset.area113=key;root.dataset.module113=key;form();logo();const oldHeader=$('#transactionsHeading98');const notices=$('#headerNotices104');if(notices&&notices.parentElement===oldHeader)document.body.append(notices);root.querySelectorAll('.im-title104').forEach(main=>{main.classList.add('redundant113');const error=main.querySelector('.im-error104');if(error)main.after(error)});if(key==='documents'||key==='pos')root.querySelector('.area-banner113')?.remove();else if(key!=='dashboard')decorateBanner(root,key);else{const b=$('.dash-hero112'),dashboardTab=$('#dashboard [data-tab112][aria-selected=true]')?.dataset.tab112?.toLowerCase()||'home',d={...(state.rows.dashboard||{}),...(state.rows['dashboard:dashboard-'+dashboardTab]||{})};if(b){const sig=JSON.stringify([dashboardTab,d]);if(b.dataset.saved113!==sig){b.dataset.saved113=sig;b.style.backgroundImage=`url("${defaultPhoto()}")`;b.style.backgroundPosition=`${d.position??70}% ${d.positionY14229??50}%`;b.querySelectorAll('blockquote,.dash-quote113').forEach(q=>q.remove());}}}const profile=$('#topHeaderProfile104');if(profile&&profile.parentElement!==$('#appSidebar'))$('#appSidebar').append(profile);$('.sidebar-quote108')?.remove();if(profile&&profile.nextElementSibling)profile.parentElement.append(profile);
root.querySelectorAll(':scope>.settings-page-heading').forEach(h=>{const next=h.nextElementSibling;if(next?.matches('form.settings-section-card')){next.prepend(h);next.classList.add('settings-unified113')}else h.classList.add('panel113')});
root.querySelectorAll('.im-menu-collection113 details').forEach(d=>{if(d.dataset.toggle113)return;d.dataset.toggle113='1';d.addEventListener('toggle',()=>{if(d.open)d.parentElement.querySelectorAll('details').forEach(other=>{if(other!==d)other.open=false})})});
const sub=$('.sub-user-tabs-shell'),shell=$('#categoryTabShell');if(sub&&shell&&sub.parentElement!==shell.parentElement)shell.after(sub);if(sub)sub.hidden=key!=='sub-users';
const heading=root.querySelector('.v49-desktop-user-heading');if(heading&&typeof Work82!=='undefined'){const text=heading.querySelector('h2')?.dataset.iconTitle113||heading.querySelector('h2')?.textContent||'';const name=text.replace(/[’']s? Account$/,'').trim().toLowerCase();const matches=Work82.employees.filter(r=>(r.data?.name||'').trim().toLowerCase()===name);if(matches.length===1){const data=matches[0].data;if(/^data:image\/(png|jpeg|webp);base64,/.test(data.photoData||'')){let img=heading.querySelector('.user-photo113');if(!img){img=document.createElement('img');img.className='user-photo113';heading.append(img)}if(img.getAttribute('src')!==data.photoData)img.src=data.photoData;img.alt=data.name}}}
}
function ready(){document.addEventListener('change',async e=>{if(e.target.id!=='companyLogoUpload101'||!admin())return;const file=e.target.files[0];if(!file)return;try{const data=await resize(file);await save('brand',{...(state.rows.brand||{}),image:data});showCenterStatus('Company logo saved to the database.')}catch(error){showCenterStatus(error.message,true)}});document.addEventListener('click',async e=>{if(e.target.id==='removeLogo101'&&admin()){try{await save('brand',{...(state.rows.brand||{}),image:''})}catch(error){showCenterStatus(error.message,true)}}});addSettings('settings-appearance113','Banner');addSettings('settings-backup113','Accounting Archive');addSettings('settings-recovery113','Recovery Settings');document.body.classList.add('shell113');sync();load();let queued=false;new MutationObserver(rs=>{if(queued||!rs.some(r=>r.type==='childList'&&[...r.addedNodes].some(n=>n.nodeType===1)||r.type==='attributes'&&r.target.classList?.contains('tab-content')))return;queued=true;requestAnimationFrame(()=>{queued=false;sync()})}).observe($('.main-content-area')||document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['class']});const sw=window.switchTab;window.switchTab=function(id,...args){const result=sw.call(this,id,...args);const scroll=$('.workspace-scroll');if(scroll)scroll.scrollTop=0;sync();load();window.dispatchEvent(new CustomEvent('page113',{detail:id}));return result};const beforeAccount=window.scrollToAccountModule;if(typeof beforeAccount==='function')window.scrollToAccountModule=function(...args){const result=beforeAccount.apply(this,args);requestAnimationFrame(sync);return result};window.addEventListener('focus',()=>load());}
window.shell113={addSettings,areas,area,state,save,saveMany,load,svg,esc,resize,sync,admin};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
