/* Authenticated shell first; protected content stays unavailable until its data is ready. */
(()=>{'use strict';let currentJob=null;
const phone=()=>document.documentElement.dataset.device132==='phone';
function needs(view){if(phone())return view==='document-editor105'?['business']:['reference','profiles','business'];if(view==='document-editor105')return ['business'];if(view==='settings-users')return ['profiles'];const names=['reference','journal','business','profiles'];if(view==='settings-business')names.push('legal');if(['submissions','entry-submissions','user-entry-review'].includes(view))names.push('submissions');return names}
function pending(show,message='Loading your workspace…'){document.body.classList.toggle('startup-pending1443',show);let box=document.getElementById('startup1443');if(!box){box=document.createElement('section');box.id='startup1443';box.setAttribute('role','status');box.innerHTML=loading1444.markup()+'<p></p><button class="je-btn je-btn-secondary" hidden>Retry loading</button>';document.body.append(box)}box.hidden=!show;box.querySelector('p').textContent=message;const error=message.includes('could not load');box.classList.toggle('loading-error1444',error);box.querySelector('.loading-orbit1444').hidden=error;box.querySelector('p').classList.toggle('loading-status1444',!error);if(!error)box.querySelector('button').hidden=true;}
window.startupData1443=async function(checkSession){
 const actor=liveProfile.id;const target=Location69.view;pending(true);const job={actor};currentJob=job;
 const guard=fn=>async()=>{checkSession();if(liveProfile?.id!==actor)throw Error('Your account changed while loading.');return fn()};
 const tasks={reference:guard(loadReferenceDataFromSupabase),journal:guard(loadJournalFromSupabase),business:guard(loadBusinessSettingsFromSupabase),submissions:guard(loadSubmissionsFromSupabase),profiles:guard(loadProfilesFromSupabase),legal:guard(loadLegalDocumentsFromSupabase)};
 const ready=new Map();const run=name=>{if(!ready.has(name))ready.set(name,Promise.resolve().then(()=>name==='journal'?run('reference'):null).then(tasks[name]).then(value=>{(job.done??=new Set()).add(name);return value}));return ready.get(name)};
 const critical=needs(target);
 async function loadAll(){try{await Promise.all([...critical.map(run),window.workflowReady1443]);checkSession();if(currentJob!==job)return;pending(false);for(const name of (phone()?critical:Object.keys(tasks)))run(name).catch(error=>{if(currentJob===job&&liveProfile?.id===actor)showCenterStatus('Some background data could not load: '+error.message+'. Use Refresh to retry.',true)});return true}catch(e){if(currentJob===job&&liveProfile?.id===actor){pending(true,'Workspace data could not load: '+e.message);const b=document.querySelector('#startup1443 button');b.hidden=false;b.onclick=()=>{ready.clear();window.workflowReady1443=workflow136.reload({skipJournal:true});b.hidden=true;pending(true);loadAll()};}return false}}
 job.activate=async()=>{const view=Location69.view,required=needs(view);if(required.every(n=>job.done?.has(n))){pending(false);return}pending(true);try{await Promise.all([...required.map(run),window.workflowReady1443]);if(currentJob===job&&Location69.view===view)pending(false)}catch(e){if(currentJob===job&&Location69.view===view){pending(true,'This area could not load: '+e.message);const b=document.querySelector('#startup1443 button');b.hidden=false;b.onclick=()=>{ready.clear();window.workflowReady1443=workflow136.reload({skipJournal:true});b.hidden=true;job.activate()}}}};
 const slow=setTimeout(()=>{if(currentJob===job&&document.body.classList.contains('startup-pending1443'))pending(true,'The connection is taking longer than usual. Your data is still loading…')},12000);
 try{return await loadAll()}finally{clearTimeout(slow)}
};
function ready(){const change=window.switchTab;window.switchTab=function(...args){const result=change.apply(this,args);currentJob?.activate?.();return result}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
