/* Authenticated shell first; protected content stays unavailable until its data is ready. */
(()=>{'use strict';let currentJob=null;
function pending(show,message='Loading your workspace…'){document.body.classList.toggle('startup-pending1443',show);let box=document.getElementById('startup1443');if(!box){box=document.createElement('section');box.id='startup1443';box.setAttribute('role','status');box.innerHTML='<p></p><button class="je-btn je-btn-secondary" hidden>Retry loading</button>';document.body.append(box)}box.hidden=!show;box.querySelector('p').textContent=message;}
window.startupData1443=async function(checkSession){
 const actor=liveProfile.id;const target=Location69.view;pending(true);const job={actor};currentJob=job;
 const guard=fn=>async()=>{checkSession();if(liveProfile?.id!==actor)throw Error('Your account changed while loading.');return fn()};
 const tasks={reference:guard(loadReferenceDataFromSupabase),journal:guard(loadJournalFromSupabase),business:guard(loadBusinessSettingsFromSupabase),submissions:guard(loadSubmissionsFromSupabase),profiles:guard(loadProfilesFromSupabase),legal:guard(loadLegalDocumentsFromSupabase)};
 const ready=new Map();const run=name=>{if(!ready.has(name))ready.set(name,Promise.resolve().then(()=>name==='journal'?run('reference'):null).then(tasks[name]).then(value=>{(job.done??=new Set()).add(name);return value}));return ready.get(name)};
 const doc=target==='document-editor105',critical=doc?['business']:target==='settings-users'?['profiles']:target==='submissions'?['submissions','profiles']:['reference','journal','business','profiles'];
 async function loadAll(){try{await Promise.all([...critical.map(run),window.workflowReady1443]);checkSession();if(currentJob!==job)return;pending(false);for(const name of Object.keys(tasks))run(name).catch(error=>{if(currentJob===job&&liveProfile?.id===actor)showCenterStatus('Some background data could not load: '+error.message+'. Use Refresh to retry.',true)});return true}catch(e){if(currentJob===job&&liveProfile?.id===actor){pending(true,'Workspace data could not load: '+e.message);const b=document.querySelector('#startup1443 button');b.hidden=false;b.onclick=()=>{ready.clear();window.workflowReady1443=workflow136.reload({skipJournal:true});b.hidden=true;pending(true);loadAll()};}return false}}
 job.activate=async()=>{const needs=Location69.view==='document-editor105'?['business']:['reference','journal','business','profiles','submissions','legal'];if(needs.every(n=>job.done?.has(n)))return;pending(true);try{await Promise.all([...needs.map(run),window.workflowReady1443]);if(currentJob===job)pending(false)}catch(e){if(currentJob===job){pending(true,'This area could not load: '+e.message);const b=document.querySelector('#startup1443 button');b.hidden=false;b.onclick=()=>{ready.clear();window.workflowReady1443=workflow136.reload({skipJournal:true});b.hidden=true;job.activate()}}}};
 const slow=setTimeout(()=>{if(currentJob===job&&document.body.classList.contains('startup-pending1443'))pending(true,'The connection is taking longer than usual. Your data is still loading…')},12000);
 try{return await loadAll()}finally{clearTimeout(slow)}
};
function ready(){const change=window.switchTab;window.switchTab=function(...args){const result=change.apply(this,args);currentJob?.activate?.();return result}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready);else ready();
})();
