/* Private to-do workflows. Never creates, pays, posts or changes a transaction. */
(()=>{'use strict';
 const $=id=>document.getElementById(id),esc=v=>escapeHtml(String(v??'')),state=()=>workflow136.state;
 const templates=[
  {id:'closing',title:'Journal / period closing',steps:['Check the Active Journal dates, accounts, descriptions and supporting documents.','Review submitted sub-user reports and resolve returned entries.','Check debit and credit balances for every currency.','Reconcile cash and bank accounts with statements and cash counts.','Review payroll, PIT and SSO entries and outstanding payables.','Review the General Ledger and Trial Balance; investigate differences.','Complete the Period Closing checklist and resolve findings.','Save or print the period reports and supporting documents.','Close the period after review; lock it only after final authorization.','Save the period backup and confirm the next open period.']},
  {id:'payroll',title:'Payroll processing',steps:['Confirm the payroll period, employee list and salary settings.','Review attendance, leave, absence and late records.','Verify salary currencies, exchange rates and internal deductions.','Check the saved PIT brackets, contribution shares and SSO settings.','Calculate payroll and review gross salary, mandatory deductions and net pay for each employee.','Review the editable payroll journal, clearing accounts, bridges and payables.','Obtain payroll approval and resolve corrections.','Prepare vouchers and verify independent signatories and receivers.','Record authorized salary payments and reconcile the clearing accounts.','Save the approved payroll reports, vouchers and payment evidence.']},
  {id:'bank',title:'Bank / cash reconciliation',steps:['Choose the reconciliation period and bank or cash account.','Collect statements, receipts and cash count records.','Match recorded journal entries to the supporting records.','Identify outstanding payments, deposits and missing entries.','Investigate differences and record approved corrections.','Confirm the reconciled closing balance.','Obtain review and save the reconciliation report.']},
  {id:'tax',title:'PIT / SSO preparation',steps:['Choose the filing period and confirm current company settings and deadlines.','Review the approved payroll and employee information.','Reconcile PIT and SSO expense, bridge and payable accounts.','Verify employee and company shares against the approved payroll.','Prepare the required filing schedules and supporting documents.','Obtain approval for the filing and payment.','Submit the filing and record the authorized payment.','Reconcile the payable balances and save submission receipts.']}
 ];
 const config=t=>({type:t.sequential?'sequential':'regular',repeat:'monthly',intervalHours:2,reminderEvery:0,windowStart:'08:00',windowEnd:'18:00',...(t.todo_config1438||{})});
 const localDate=d=>[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');
 const localInput=value=>{if(!value)return '';const d=new Date(value);return Number.isNaN(+d)?'':localDate(d)+'T'+String(d.getHours()).padStart(2,'0')+':'+String(d.getMinutes()).padStart(2,'0')};
 const format=value=>value?new Date(value).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'';
 const progress=t=>{const total=(t.steps||[]).length,done=(t.steps||[]).filter(s=>s.done).length;return {total,done,percent:total?Math.round(done/total*100):0,next:(t.steps||[]).find(s=>!s.done)?.text||''}};
 function nextOccurrence(value,c,now=new Date()){
  const original=new Date(value);if(Number.isNaN(+original))throw Error('Choose the first due date and time.');
  let next=new Date(original);
  if(c.repeat==='hours'){const ms=Number(c.intervalHours)*3600000;if(!(ms>=3600000))throw Error('Choose a repeat interval of at least one hour.');next=new Date(+original+Math.max(1,Math.floor((+now-+original)/ms)+1)*ms);}
  else if(c.repeat==='monthly'){
   const day=Number(c.repeatDay)||original.getDate();let months=Math.max(1,(now.getFullYear()-original.getFullYear())*12+now.getMonth()-original.getMonth());
   const at=m=>{const d=new Date(original);d.setDate(1);d.setMonth(d.getMonth()+m);d.setDate(Math.min(day,new Date(d.getFullYear(),d.getMonth()+1,0).getDate()));return d};next=at(months);if(next<=now)next=at(++months);
  }else{const days=c.repeat==='weekly'?7:1;do{next.setDate(next.getDate()+days)}while(next<=now)}
  return next.toISOString();
 }
 // One due reminder per time slot, inside the daily window. Missed slots are consolidated.
 function reminderSlot(t,now=new Date()){
  if(t.is_template1438||!progress(t).next)return null;const c=config(t),start=new Date(c.reminderAt);if(!c.reminderAt||Number.isNaN(+start)||now<start)return null;
  const interval=Number(c.reminderEvery)||0;if(!interval)return start.toISOString();
  const minute=now.getHours()*60+now.getMinutes(),toMinute=s=>{const [h,m]=s.split(':').map(Number);return h*60+m};
  const lo=toMinute(c.windowStart||'08:00'),hi=toMinute(c.windowEnd||'18:00');if(minute<lo||minute>hi)return null;
  const day=new Date(now);day.setHours(0,lo,0,0);const base=Math.max(+day,+start),slot=base+Math.floor((+now-base)/(interval*60000))*interval*60000;
  return slot>=+start&&slot<=+now?new Date(slot).toISOString():null;
 }
 function details(t){const p=progress(t),c=config(t);return `${p.done}/${p.total} completed · ${p.percent}%${p.next?' · Next: '+p.next:''}${c.dueAt?' · Due '+format(c.dueAt):t.due_date?' · Due '+t.due_date:''}`;}
 function notices(){return state().todos.filter(t=>!t.is_template1438&&!config(t).archived1443&&progress(t).next&&!(config(t).completedCycles&&new Date(config(t).reminderAt||config(t).dueAt)>new Date())).map(t=>({type:reminderSlot(t)?'To-do reminder':'To-do list',title:t.title,detail:details(t),target:'transactions-recurring',todoId:t.id}));}
 const busy=new Set();
 async function change(t,data){
  if(busy.has(t.id))return false;busy.add(t.id);const owner=liveProfile?.id;
  try{let query=ojmDb.from('workspace_todos136').update({...data,updated_at:new Date().toISOString()}).eq('id',t.id).eq('owner_id',owner);if(t.updated_at)query=query.eq('updated_at',t.updated_at);const result=await query.select('id');
   if(result.error)throw Error(result.error.message);if(!result.data?.length)throw Error('This task changed in another window. Reload it before editing again.');
   if(liveProfile?.id===owner)await workflow136.loadTodos();return true;
  }catch(e){showCenterStatus('Could not confirm the to-do update. Reload before trying again: '+e.message,true);if(liveProfile?.id===owner)await workflow136.loadTodos();return false;}finally{busy.delete(t.id)}
 }
 async function complete(t,index,checked){
  if(!t||busy.has(t.id)||!checked||t.steps?.[index]?.done)return render();
  const steps=structuredClone(t.steps||[]);if(!steps[index]||t.sequential&&steps.slice(0,index).some(s=>!s.done))return render();
  if(!await ui117.confirm('Mark “'+steps[index].text+'” complete? This cannot be undone.')){render();window.refreshNotices1443?.();return;}
  steps[index].done=true;
  const c=config(t),data={steps};
  if(c.type==='recurring'&&steps.length&&steps.every(s=>s.done)){
   const next=nextOccurrence(c.dueAt,c),offset=c.reminderAt?new Date(c.dueAt)-new Date(c.reminderAt):0;
   data.todo_config1438={...c,dueAt:next,reminderAt:c.reminderAt?new Date(new Date(next)-offset).toISOString():null,completedCycles:(c.completedCycles||0)+1,lastCompletedAt:new Date().toISOString(),lastCompletedSteps:steps};
   data.due_date=localDate(new Date(next));data.steps=steps.map(s=>({...s,done:false}));
  }
  await change(t,data);render();window.refreshNotices1443?.();
 }
 async function remove(t){if(!t.is_template1438&&(t.steps.some(s=>s.done)||config(t).completedCycles)){if(await ui117.confirm('Archive this checklist? Completed steps remain recorded.'))await change(t,{todo_config1438:{...config(t),archived1443:true}});return;}if(!await ui117.confirm('Delete this '+(t.is_template1438?'saved template':'to-do list')+'?'))return;const owner=liveProfile?.id,r=await ojmDb.from('workspace_todos136').delete().eq('id',t.id).eq('owner_id',owner);if(r.error)return showCenterStatus(r.error.message,true);if(liveProfile?.id===owner)await workflow136.loadTodos();}
 function render(){
  const root=$('transactions-recurring');if(!root)return;let host=$('todos136');if(!host){host=document.createElement('section');host.id='todos136';host.className='je-card';root.append(host)}
  host.classList.add('todo-workflows1438');const opened=new Set([...host.querySelectorAll('details[open][id]')].map(n=>n.id));
  const own=state().todos.filter(t=>t.is_template1438),tasks=state().todos.filter(t=>!t.is_template1438&&!config(t).archived1443);
  host.innerHTML=`<div class="je-card-header"><h3>To-do Lists</h3><button type="button" class="je-btn je-btn-emerald" data-new-todo136>Add To-do</button></div><p class="todo-intro1438">Personal tasks, ordered checklists and reminders. Completing a step does not post or pay an upcoming transaction.</p><div class="todo-templates1438"><strong>Start from a template:</strong>${templates.map(t=>`<button class="je-btn je-btn-secondary" data-template1438="${t.id}">${esc(t.title)}</button>`).join('')}${own.map(t=>`<button class="je-btn je-btn-secondary" data-template1438="${esc(t.id)}">${esc(t.title)}</button>`).join('')}</div>${state().todoError?'<p class="todo-error1438">To-do lists could not load. Check your connection and install setup/INSTALL-TODO-v142.18.sql if needed.</p>':''}${tasks.map(t=>{const p=progress(t),c=config(t);return `<details class="todo136" id="todo1438-${esc(t.id)}" ${opened.has('todo1438-'+t.id)?'open':''}><summary><strong>${esc(t.title)}</strong><span>${esc(c.type==='recurring'?'Recurring':t.sequential?'Sequential checklist':'Regular task')} · ${p.done}/${p.total} · ${p.percent}%</span></summary><div class="todo-progress1438"><progress max="${p.total||1}" value="${p.done}" aria-label="Checklist progress"></progress><span>${p.percent}%</span></div><p class="todo-next1438">${p.next?'Next: '+esc(p.next):'Completed'}</p><p>${esc(c.dueAt?format(c.dueAt):t.due_date||'No due date')}${c.type==='recurring'?' · Repeats '+esc(c.repeat==='hours'?'every '+c.intervalHours+' hours':c.repeat):''}${c.reminderAt?' · Reminder '+esc(format(c.reminderAt)):''}</p>${c.completedCycles?`<small>${c.completedCycles} completed cycle(s) · Last completed ${esc(format(c.lastCompletedAt))}</small>`:''}<ol>${(t.steps||[]).map((s,i)=>`<li><label><input type="checkbox" data-task1438="${esc(t.id)}" data-step1438="${i}" ${s.done?'checked':''} ${s.done||t.sequential&&t.steps.slice(0,i).some(x=>!x.done)?'disabled':''}>${esc(s.text)}</label></li>`).join('')}</ol><div class="todo-buttons1438"><button class="je-btn je-btn-secondary" data-edit1438="${esc(t.id)}">Edit</button><button class="je-btn je-btn-secondary" data-copy1438="${esc(t.id)}">Save as template</button><button class="je-btn je-btn-danger" data-delete1438="${esc(t.id)}">${p.done||c.completedCycles?'Archive':'Delete'}</button></div></details>`}).join('')||'<p class="todo-intro1438">No to-do lists yet. Choose a template or add your own.</p>'}${own.length?`<details class="todo136"><summary>My saved templates</summary>${own.map(t=>`<p>${esc(t.title)} <button class="je-btn je-btn-secondary" data-edit1438="${esc(t.id)}">Edit template</button> <button class="je-btn je-btn-danger" data-delete1438="${esc(t.id)}">Delete template</button></p>`).join('')}</details>`:''}`;
  host.querySelector('[data-new-todo136]').onclick=()=>edit();
  host.querySelectorAll('[data-template1438]').forEach(b=>b.onclick=()=>{const t=templates.find(t=>t.id===b.dataset.template1438)||own.find(t=>t.id===b.dataset.template1438);edit(null,{...t,steps:t.steps.map(s=>({text:typeof s==='string'?s:s.text,done:false})),sequential:t.sequential??true,todo_config1438:{...config(t),type:t.todo_config1438?.type||'sequential',dueAt:null,reminderAt:null,completedCycles:0,lastCompletedAt:null,lastCompletedSteps:[]},is_template1438:false})});
  host.querySelectorAll('[data-edit1438]').forEach(b=>b.onclick=()=>edit(b.dataset.edit1438));
  host.querySelectorAll('[data-delete1438]').forEach(b=>b.onclick=()=>remove(state().todos.find(t=>t.id===b.dataset.delete1438)));
  host.querySelectorAll('[data-copy1438]').forEach(b=>b.onclick=()=>{const t=state().todos.find(t=>t.id===b.dataset.copy1438);edit(null,{...t,id:null,is_template1438:true,steps:t.steps.map(s=>({...s,done:false})),todo_config1438:{...config(t),dueAt:null,reminderAt:null,completedCycles:0,lastCompletedAt:null,lastCompletedSteps:[]}})});
  host.querySelectorAll('[data-task1438]').forEach(n=>n.onchange=()=>complete(state().todos.find(t=>t.id===n.dataset.task1438),Number(n.dataset.step1438),n.checked));
 }
 function edit(id,seed){
  const owner=liveProfile?.id;if(!owner)return;const t=id?state().todos.find(t=>t.id===id):seed||{},c=config(t),overlay=document.createElement('div');overlay.className='submission-compare-overlay';overlay.id='todoEditor1438';
  overlay.innerHTML=`<form class="source-dialog69 todo-form1438"><h2>${id?'Edit':'Add'} ${t.is_template1438?'To-do Template':'To-do'}</h2><label>Title<input name="title" required maxlength="160" value="${esc(t.title||'')}"></label><label>Type<select name="kind"><option value="regular">Regular task</option><option value="sequential">Sequential checklist</option><option value="recurring">Recurring task / checklist</option></select></label><label data-recurring1438><span><input type="checkbox" name="ordered" ${t.sequential?'checked':''}> Complete recurring steps in order</span></label><fieldset><legend>Checklist steps</legend><div class="todo-step-editor1443"></div><button type="button" class="je-btn je-btn-secondary" data-add-step1443>Add step</button><small>Each row is one step. Completed steps are locked.</small></fieldset><div data-schedule1438><div class="todo-grid1438"><label>Due date and time<input name="due" type="datetime-local" value="${esc(localInput(c.dueAt)||(t.due_date?t.due_date+'T09:00':''))}"></label><label>Reminder date and time<input name="reminder" type="datetime-local" value="${esc(localInput(c.reminderAt))}"></label></div><div class="todo-grid1438" data-recurring1438><label>Repeat task<select name="repeat"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option><option value="hours">Every N hours</option></select></label><label>Hours between tasks<input name="hours" type="number" min="1" max="8760" value="${esc(c.intervalHours)}"></label></div><label>Repeat reminder<select name="reminderEvery"><option value="0">Once</option><option value="60">Every hour</option><option value="120">Every two hours</option><option value="custom">Custom interval</option></select></label><label data-custom-reminder1438>Minutes between reminders<input type="number" name="customMinutes" min="1" max="10080" value="${esc(c.reminderEvery||60)}"></label><div class="todo-grid1438" data-window1438><label>Daily reminders start<input name="windowStart" type="time" value="${esc(c.windowStart)}"></label><label>Daily reminders end<input name="windowEnd" type="time" value="${esc(c.windowEnd)}"></label></div><small>Times use this device’s timezone (${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)}). Reminders appear while the app is open; overdue tasks remain in notifications.</small></div><label><span><input name="template" type="checkbox" ${t.is_template1438?'checked':''}> Save as a reusable template</span></label><p class="todo-error1438" role="alert"></p><footer><button type="button" class="je-btn je-btn-secondary" data-cancel1438>Cancel</button><button type="submit" class="je-btn je-btn-emerald">Save</button></footer></form>`;
  document.body.append(overlay);const form=overlay.querySelector('form'),f=form.elements;f.kind.value=c.type;f.repeat.value=c.repeat;f.reminderEvery.value=[0,60,120].includes(Number(c.reminderEvery))?String(c.reminderEvery):'custom';
  const rows=structuredClone(t.steps||[]);if(!rows.length)rows.push({text:'',done:false});
  const drawSteps=()=>{const host=form.querySelector('.todo-step-editor1443');host.innerHTML=rows.map((step,i)=>`<div class="todo-step-row1443"><input type="checkbox" disabled ${step.done?'checked':''} aria-label="${step.done?'Completed':'Pending'}"><input name="step1443-${i}" type="text" maxlength="2000" value="${esc(step.text)}" ${step.done?'readonly':''} aria-label="Step ${i+1}"><button type="button" data-move1443="${i}" ${i===0||step.done||rows[i-1]?.done?'disabled':''} aria-label="Move step up">↑</button><button type="button" data-remove1443="${i}" ${step.done?'disabled':''} aria-label="Remove step">×</button></div>`).join('');host.querySelectorAll('input[type=text]').forEach((n,i)=>n.oninput=()=>rows[i].text=n.value);host.querySelectorAll('[data-move1443]').forEach(n=>n.onclick=()=>{const i=Number(n.dataset.move1443);[rows[i-1],rows[i]]=[rows[i],rows[i-1]];drawSteps()});host.querySelectorAll('[data-remove1443]').forEach(n=>n.onclick=()=>{rows.splice(Number(n.dataset.remove1443),1);drawSteps()});};drawSteps();form.querySelector('[data-add-step1443]').onclick=()=>{rows.push({text:'',done:false});drawSteps();form.querySelector('.todo-step-row1443:last-child input[type=text]').focus()};
  if(id&&t.steps?.some(s=>s.done)){f.template.disabled=true;f.kind.disabled=true;f.ordered.disabled=true;}
  const visibility=()=>{form.querySelectorAll('[data-recurring1438]').forEach(n=>n.hidden=f.kind.value!=='recurring');form.querySelector('[data-schedule1438]').hidden=f.template.checked;form.querySelector('[data-window1438]').hidden=f.reminderEvery.value==='0';form.querySelector('[data-custom-reminder1438]').hidden=f.reminderEvery.value!=='custom';f.due.required=f.kind.value==='recurring'&&!f.template.checked;f.hours.disabled=f.repeat.value!=='hours';};form.addEventListener('change',visibility);visibility();
  const original1440=()=>JSON.stringify([...form.elements].filter(n=>n.name).map(n=>[n.name,n.type==='checkbox'?n.checked:n.value]));const baseline1440=original1440();window.dialogs1440?.attach(overlay,{close:()=>overlay.remove(),dirty:()=>original1440()!==baseline1440,focus:()=>f.title.focus()});form.querySelector('[data-cancel1438]').onclick=()=>window.dialogs1440.requestClose(overlay);
  form.onsubmit=async e=>{e.preventDefault();if(liveProfile?.id!==owner){overlay.remove();return}const button=form.querySelector('[type=submit]');if(button.disabled)return;const error=form.querySelector('[role=alert]');error.textContent='';
   try{const title=f.title.value.trim(),steps=rows.filter(s=>s.text.trim()).map(s=>({...s,text:s.text.trim()}));if(!title||!steps.length)throw Error('Enter a title and at least one step.');if(steps.length>100)throw Error('Use at most 100 steps per checklist.');
    const sequential=f.kind.value==='sequential'||f.kind.value==='recurring'&&f.ordered.checked;
    const isTemplate=f.template.checked,dueAt=!isTemplate&&f.due.value?new Date(f.due.value).toISOString():null,reminderAt=!isTemplate&&f.reminder.value?new Date(f.reminder.value).toISOString():null,reminderEvery=Number(f.reminderEvery.value==='custom'?f.customMinutes.value:f.reminderEvery.value);
    if(!isTemplate&&f.kind.value==='recurring'&&!dueAt)throw Error('Set the first due date and time for this recurring task.');
    if(reminderEvery&&(!Number.isInteger(reminderEvery)||reminderEvery<1||reminderEvery>10080))throw Error('Use a reminder interval between 1 and 10,080 minutes.');
    if(!isTemplate&&reminderEvery&&!reminderAt)throw Error('Choose when reminders should start.');if(reminderEvery&&f.windowStart.value>=f.windowEnd.value)throw Error('The daily reminder end must be after its start.');
    const intervalHours=Number(f.hours.value);if(f.kind.value==='recurring'&&f.repeat.value==='hours'&&!(intervalHours>=1&&intervalHours<=8760))throw Error('Use a task interval between 1 and 8,760 hours.');
    const data={owner_id:owner,title,steps:isTemplate?steps.map(s=>({...s,done:false})):steps,sequential,due_date:dueAt?localDate(new Date(dueAt)):null,is_template1438:isTemplate,todo_config1438:{...c,type:f.kind.value,repeatDay:dueAt?(dueAt===c.dueAt?c.repeatDay||new Date(dueAt).getDate():new Date(dueAt).getDate()):c.repeatDay,dueAt,reminderAt,reminderEvery,repeat:f.repeat.value,intervalHours,windowStart:f.windowStart.value,windowEnd:f.windowEnd.value}};
    button.disabled=true;if(id){if(await change(t,data))overlay.remove();}else{const result=await ojmDb.from('workspace_todos136').insert({...data,updated_at:new Date().toISOString()});if(result.error)throw Error(result.error.message);overlay.remove();if(liveProfile?.id===owner)await workflow136.loadTodos();}
   }catch(err){error.textContent=err.message+( /todo_config1438|is_template1438|schema cache/.test(err.message)?' Run setup/INSTALL-TODO-v142.18.sql once.':'');}finally{button.disabled=false;}
  };
 }
 function tick(){if(!liveProfile||!document.getElementById('loginGate')?.classList.contains('is-authenticated'))return;for(const t of state().todos){const slot=reminderSlot(t);if(!slot)continue;const key='ojm-todo-reminder1438:'+liveProfile.id+':'+t.id;try{if(localStorage.getItem(key)===slot)continue;localStorage.setItem(key,slot)}catch{continue}showAppNotification('To-do reminder: '+t.title,details(t),false);break}}
 function noticeHTML(n){const t=state().todos.find(t=>t.id===n.todoId);if(!t)return '';return `<details class="todo-notice1443" data-notice1443="${esc(t.id)}"><summary><strong>${esc(t.title)}</strong><small>${esc(details(t))}</small></summary>${(t.steps||[]).map((s,i)=>`<label><input type="checkbox" data-notice-step1443="${i}" data-task="${esc(t.id)}" ${s.done?'checked disabled':t.sequential&&t.steps.slice(0,i).some(x=>!x.done)?'disabled':''}><span>${esc(s.text)}</span></label>`).join('')}</details>`;}
 function bindNotices(root){root.querySelectorAll('[data-notice-step1443]').forEach(n=>n.onchange=async()=>{const t=state().todos.find(t=>t.id===n.dataset.task);n.checked=false;n.disabled=true;try{await complete(t,Number(n.dataset.noticeStep1443),true)}finally{window.refreshNotices1443?.()}});}
 window.todos1438={noticeHTML,bindNotices,render,edit,templates,progress,nextOccurrence,reminderSlot,notices,complete};window.getTodoNotices136=notices;
 function ready(){render();setInterval(tick,30000);window.addEventListener('focus',tick);document.addEventListener('click',e=>{const b=e.target.closest('[data-todo-target1438]');if(!b)return;setTimeout(()=>{const n=$('todo1438-'+b.dataset.todoTarget1438);if(n){n.open=true;n.scrollIntoView({behavior:'smooth',block:'center'})}},100)});}
 if(document.readyState==='loading')window.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
