/* Detailed review -> summarized journal, shared report types and user lifecycle. */
(()=>{'use strict';
const $=id=>document.getElementById(id),esc=s=>escapeHtml(String(s??''));
const setupMessage='This action needs the v142.53 database update. Ask the administrator to install setup/INSTALL-WORKFLOW-v142.53.sql.';
async function call(name,args){const r=await ojmDb.rpc(name,args);if(r.error){if(['PGRST202','PGRST205','42883','42P01','42703'].includes(r.error.code))throw Error(setupMessage);throw Error(r.error.message);}return r.data;}
async function installed(){const c=await call('workflow_capabilities14253');if(c?.version!==14253)throw Error(setupMessage);}
const period=j=>new Date(String(j.period_start).slice(0,7)+'-01T12:00:00Z').toLocaleDateString('en-GB',{month:'long',year:'numeric',timeZone:'UTC'});
const names=j=>(j.report_types14253||[]).map(t=>t.name).filter(Boolean);
const description=j=>(names(j).join(' / ')||'Submitted report')+' — '+period(j);
async function types(){const r=await ojmDb.from('report_types14253').select('*').order('name');if(r.error)throw Error(['PGRST205','42P01'].includes(r.error.code)?setupMessage:r.error.message);return r.data||[];}
async function manage(){try{await installed();const rows=await types();const pending=ui108.modal('Report Types','<p>Shared names for all users. The reporting month and year are added automatically.</p><div id="reportManager14253" class="report-manager14253">'+rows.map(r=>'<div class="row14253" data-type="'+esc(r.id)+'"><input aria-label="Report type name" maxlength="80" value="'+esc(r.name)+'"><button type="button" data-save>Save</button><button type="button" data-active="'+!r.active+'">'+(r.active?'Deactivate':'Reactivate')+'</button></div>').join('')+'<div class="row14253"><input id="newReportType14253" maxlength="80" placeholder="New report type" aria-label="New report type"><button type="button" data-add>Add</button></div><p role="status"></p></div>',[{label:'Close',value:false}]);const host=$('reportManager14253');host.onclick=async e=>{const b=e.target.closest('button');if(!b)return;const row=b.closest('.row14253'),id=row.dataset.type||null,original=rows.find(x=>x.id===id),name=row.querySelector('input').value.trim();if(!name){host.querySelector('[role=status]').textContent='Enter a report type name.';return;}b.disabled=true;const end=window.actionFeedback14296?.begin(b);try{const saved=await call('save_report_type14253',{p_id:id,p_name:name,p_active:b.hasAttribute('data-active')?b.dataset.active==='true':original?.active??true});if(!id){row.dataset.type=saved.id;b.removeAttribute('data-add');b.setAttribute('data-save','');b.textContent='Save';rows.push(saved);const next=document.createElement('div');next.className='row14253';next.innerHTML='<input maxlength="80" placeholder="New report type" aria-label="New report type"><button type="button" data-add>Add</button>';row.after(next);}else Object.assign(original,saved);const toggle=row.querySelector('[data-active]');if(toggle){toggle.dataset.active=String(!saved.active);toggle.textContent=saved.active?'Deactivate':'Reactivate';}host.querySelector('[role=status]').textContent='Report type saved.';}catch(e){host.querySelector('[role=status]').textContent=e.message;}finally{end?.();b.disabled=false;}};await pending;}catch(e){showCenterStatus(e.message,true);}}
async function submit(batches){await installed();const available=(await types()).filter(t=>t.active);if(!available.length)throw Error('Ask the administrator to add an active Report Type in Users & Permissions.');if(!batches.length)throw Error('No saved entries are ready to submit.');const actor=liveProfile.id;let selected=batches[0].id,chosen=[];const form='<label>Reporting period<select id="reportPeriod14253">'+batches.map(j=>'<option value="'+esc(j.id)+'">'+esc(period(j))+' · '+j.lines.length+' entries</option>').join('')+'</select></label><fieldset class="report-types14253" id="reportSelect14253"><legend>Report types — select one or more</legend>'+available.map(t=>'<label><input type="checkbox" value="'+esc(t.id)+'">'+esc(t.name)+'</label>').join('')+'</fieldset><p id="reportPreview14253"></p><p>The reviewer receives every original entry. Approval prepares an account summary for the journal.</p>';
const answer=ui108.modal('Submit for Review',form,[{label:'Cancel',value:false},{label:'Submit',value:true,primary:true}]);const update=()=>{selected=$('reportPeriod14253').value;chosen=[...$('reportSelect14253').querySelectorAll('input:checked')].map(n=>n.value);$('reportPreview14253').textContent=available.filter(t=>chosen.includes(t.id)).map(t=>t.name).join(' / ')+(chosen.length?' — '+period(batches.find(j=>j.id===selected)):'');};$('reportPeriod14253').onchange=update;$('reportSelect14253').onchange=update;update();if(!await answer)return false;if(!chosen.length)throw Error('Select at least one report type before submitting.');if(liveProfile?.id!==actor)throw Error('Your signed-in account changed.');await call('submit_report14253',{p_journal:selected,p_types:chosen});return true;}
// Integer cents avoid client-side floating-point accumulation when grouping rows.
function summarize(j){const groups=new Map();for(const l of j.lines||[]){if(wsIsCollection(l)||l.journal_entry_id)continue;const amount=Math.round(Number(l.amount)*100);if(!Number.isSafeInteger(amount)||amount<=0)throw Error('Invalid source amount.');for(const side of ['debit','credit']){const incoming=l.direction==='in',account=side==='debit'?(incoming?l.fund_account_id:l.account_id):(incoming?l.account_id:l.fund_account_id),key=[account,l.currency_code,side].join('|');let g=groups.get(key);if(!g){g={key,account_id:account,currency_code:l.currency_code,side,cents:0,source_ids:[]};groups.set(key,g);}g.cents+=amount;if(!Number.isSafeInteger(g.cents))throw Error('Summary amount exceeds safe precision.');g.source_ids.push(l.id);}}
return [...groups.values()].map(g=>({...g,debit:g.side==='debit'?g.cents/100:0,credit:g.side==='credit'?g.cents/100:0,source_ids:g.source_ids.sort()}));}
let prepared=null,posting=false;
function prepare(j){const rows=summarize(j);if(!rows.length){showCenterStatus('This report has no unposted journal transactions.');return;}switchTab('journal');clearJournalEntry();setJournalDateMode(false);$('jeLinesBody').innerHTML='';const month=String(j.period_start).slice(0,7),date=new Date(Date.UTC(Number(month.slice(0,4)),Number(month.slice(5,7)),0)).toISOString().slice(0,10);$('jeTransDate').value=date;$('jeGeneralMemo').value=description(j);for(const r of rows){const a=AccountingStore.accounts.find(a=>a.id===r.account_id);if(!a)throw Error('An approved report account is unavailable. Refresh accounts.');r.description=a.name+' — '+(j.owner_name||getLiveUserName(j.owner_id))+' · Report '+j.id;addJournalLineRow(a.code+' — '+a.name,r.description,r.debit?String(r.debit):'',r.credit?{[r.currency_code]:String(r.credit)}:{});const tr=$('jeLinesBody').lastElementChild;tr.dataset.sourceIds14253=JSON.stringify(r.source_ids);}
pendingWorkspacePostOwnerId=j.owner_id;pendingWorkspacePostJournalId=j.id;pendingWorkspacePostIsLocal=false;prepared={id:j.id,owner:liveProfile.id,rows};let notice=$('summaryNotice14253');if(!notice){notice=document.createElement('div');notice.id='summaryNotice14253';$('jeLinesBody').closest('.table-container')?.before(notice);}notice.innerHTML='Summary by account, currency and debit/credit side. Original details remain in the approved report. <button type="button" class="je-btn je-btn-secondary" id="summarySource14253">View detailed report</button>';notice.hidden=false;$('summarySource14253').onclick=()=>openSubmissionComparison(j.id);calculateJournalBalance();}
const UserAdmin={inactive:false,visible:rows=>rows.filter(u=>!u.deleted_at14253&&(UserAdmin.inactive?u.status!=='active':u.status==='active')),toggle(){UserAdmin.inactive=!UserAdmin.inactive;renderDemoUsers();},async change(id,action){try{await installed();const u=liveProfiles.find(u=>u.id===id);if(!u||id===liveProfile.id)throw Error('You cannot remove your own access.');const text=action==='delete'?'Permanently delete this login? Historical reports, IDs and submitter identity will remain. Users with activity must have been inactive for five years.':action==='deactivate'?'Deactivate this user and block sign-in? Historical records will remain.':'Reactivate this user’s sign-in access?';if(!await ui117.confirm(text))return;await call('user_lifecycle14253',{p_user:id,p_action:action});await loadProfilesWithPermissions();window.Organization14229?.invalidate();await window.permissions1441?.verify();$('connectedPhone132')?.contentWindow?.phoneRefresh132?.();showCenterStatus(action==='delete'?'Login deleted. Historical identity retained.':'User access updated.');}catch(e){showCenterStatus(e.message,true);}}};
function lifecycleButtons(u){return '<div class="user-actions14253"><button type="button" class="je-btn je-btn-secondary" data-user-edit="'+esc(u.id)+'" aria-label="Edit '+esc(u.full_name)+'">✎ Edit</button>'+(liveProfile?.role==='admin'?'<button type="button" class="je-btn je-btn-secondary" data-user-action="'+(u.status==='active'?'deactivate':'reactivate')+'" data-user-id="'+esc(u.id)+'" '+(u.id===liveProfile.id?'disabled':'')+'>'+(u.status==='active'?'Deactivate':'↻ Reactivate')+'</button><button type="button" class="je-btn je-btn-danger" data-user-action="delete" data-user-id="'+esc(u.id)+'" '+(u.id===liveProfile.id||u.status==='active'?'disabled':'')+'>Delete</button>':'')+'</div>';}
function renderUsers(){const host=$('demoUsersList');if(!host)return;const header=host.closest('.settings-section-card')?.querySelector('.settings-section-header');let actions=header?.querySelector('.current-users-actions14305');if(header&&!actions){actions=document.createElement('div');actions.className='current-users-actions14305';actions.innerHTML='<button type="button" class="je-btn je-btn-secondary" data-report-types>Report Types</button><button type="button" class="je-btn je-btn-secondary" data-user-toggle></button>';header.append(actions);}const toggle=actions?.querySelector('[data-user-toggle]');if(toggle){toggle.textContent=UserAdmin.inactive?'Show Active Users':'Show Inactive Users';toggle.setAttribute('aria-pressed',String(UserAdmin.inactive));}host.innerHTML=UserAdmin.visible(liveProfiles||[]).map(u=>'<div class="demo-user-row"><div class="demo-user-details"><strong>'+esc(u.full_name||'Unnamed user')+'</strong><span>'+esc(u.email||'')+'</span><span>'+esc(u.user_permissions?.job_title||'')+'</span></div><span class="user-role-badge">'+(u.role==='admin'?'Administrator':u.user_permissions?.user_type==='manager'?'Manager':'Sub-user')+'</span><span class="user-status-badge">'+esc(u.status)+'</span>'+lifecycleButtons(u)+'<button type="button" class="je-btn je-btn-secondary" data-user-reset="'+esc(u.id)+'">Reset Password</button></div>').join('');}
function ready(){
 // Route only this specific connection interruption to the existing logo details.
 const status=window.showCenterStatus;window.showCenterStatus=function(message,...args){if(String(message).includes('Connection required. Your draft is retained; reconnect before approval, final posting or changing saved records.')){window.offline14239?.connectionIssue(message);}return status.call(this,message,...args);};
 const available=window.availableSubUsers;window.availableSubUsers=(...args)=>available(...args).filter(u=>u.status==='active'&&!u.deleted_at14253);
 renderDemoUsers=renderUsers;renderUsers();document.addEventListener('click',e=>{const b=e.target.closest?.('[data-user-action],[data-user-edit],[data-user-toggle],[data-report-types],[data-user-reset]');if(!b)return;if(b.hasAttribute('data-user-action'))UserAdmin.change(b.dataset.userId,b.dataset.userAction);else if(b.hasAttribute('data-user-edit'))openUserAccessEditor(b.dataset.userEdit);else if(b.hasAttribute('data-user-toggle'))UserAdmin.toggle();else if(b.hasAttribute('data-user-reset'))sendSubUserPasswordReset(b.dataset.userReset);else manage();});
 // Retain the existing desktop unsaved-draft checks and confirmation. Intercept its RPC
 // only at the call sites in the source/bundle, not all database traffic.
 window.submitTypedReport14253=async id=>{const j=allReviewJournals().find(j=>j.id===id)||currentWorkspaceJournal(liveProfile.id);if(!j||j.id!==id)throw Error('Reload this report before submitting.');return submit([j]);};
 if(window.PhoneApp132){const A=PhoneApp132;A.submit=async(id,month='')=>{if(offline14239?.pendingOwner(id))throw Error('Sync pending entries before submitting.');if(!A.canWriteStaff(id))throw Error('Submitting is not enabled for this workspace.');const batches=A.reports(id).filter(j=>['draft','returned'].includes(j.status)&&j.lines?.length&&(!month||String(j.period_start).startsWith(month)));if(await submit(batches))await A.loadWorkspace(id,true);};}
 const clear=window.clearJournalEntry;window.clearJournalEntry=function(...args){const r=clear.apply(this,args);prepared=null;$('summaryNotice14253')?.remove();return r;};
 window.prepareComparedForm69=prepare;
 const post=window.submitJournalEntry;window.submitJournalEntry=async function(...args){if(!pendingWorkspacePostJournalId)return post.apply(this,args);if(posting)return;posting=true;try{await installed();if(!prepared||prepared.id!==pendingWorkspacePostJournalId||prepared.owner!==liveProfile.id)throw Error('Open the approved report again to prepare its summary.');const state=collectLiveJournalGroups();if(state.errors.length||state.differences.length)throw Error(state.errors[0]||'Debit and credit must balance for every currency.');const groups=Object.entries(state.grouped).filter(([,g])=>g.lines.length);if(groups.length!==1)throw Error('Use one posting date for the report summary.');const [date,g]=groups[0];const lines=g.lines.map(l=>{const side=Number(l.debit)>0?'debit':'credit',key=[l.account?.id,l.currency,side].join('|'),original=prepared.rows.find(r=>r.key===key);if(!original)throw Error('An account or currency changed. Prepare the summary again.');return {account_id:l.account.id,currency_code:l.currency,debit:Number(l.debit||0),credit:Number(l.credit||0),description:l.memo,source_ids:original.source_ids};});const result=await call('post_summary14253',{p_journal:prepared.id,p_date:date,p_memo:$('jeGeneralMemo').value.trim(),p_lines:lines,p_prefix:ApplicationSettings.accounting?.journalPrefix||businessInitials()||'OJM',p_digits:Number(ApplicationSettings.accounting?.journalDigits||6)});if(!result?.entry_id)throw Error('Posting was not confirmed.');pendingWorkspacePostJournalId='';pendingWorkspacePostOwnerId='';prepared=null;$('summaryNotice14253')?.remove();finalizePostSuccess();await Promise.all([loadJournalFromSupabase(),loadStaffJournalsForReview()]);showCenterStatus('Summary posted as '+result.entry_no+'. Original report and entry references retained.');}catch(e){showCenterStatus(e.message,true);}finally{posting=false;}};
 const compare=window.openSubmissionComparison;window.openSubmissionComparison=async function(id,...args){const result=await compare.call(this,id,...args),j=allReviewJournals().find(x=>x.id===id),box=$('submissionComparisonOverlay');if(j&&box&&!box.querySelector('[data-report-label14253]')){const p=document.createElement('p');p.dataset.reportLabel14253='';p.textContent=description(j)+' · Report '+j.id;box.querySelector('header')?.append(p);}return result;};
 installAssignmentFilters();
 installSystem();
}
function installAssignmentFilters(){let category='';const filter=window.filterAccessPicker;window.filterAccessPicker=function(query=''){filter(query);if(!$('userAccountAssignmentPanel')?.closest('#accessPickerContent'))return;for(const label of document.querySelectorAll('#accessPickerContent .permission-option')){const id=label.querySelector('input')?.value;if(category&&AccountGroups14253.type(AccountGroups14253.find(id))!==category)label.hidden=true;}};const open=window.openAccessPicker;window.openAccessPicker=function(title,panelId,...args){const r=open.call(this,title,panelId,...args);$('assignmentTypes14253')?.remove();category='';if(panelId!=='userAccountAssignmentPanel'){const oldSearch=$('assignmentSearch14253');if(oldSearch)oldSearch.hidden=true;return r;}let search=$('accessPickerSearch')||$('assignmentSearch14253');if(!search){search=document.createElement('input');search.id='assignmentSearch14253';search.type='search';search.className='je-input';search.placeholder='Search accounts';search.setAttribute('aria-label','Search assigned accounts');$('accessPickerContent')?.before(search);search.oninput=()=>filterAccessPicker(search.value);}search.hidden=false;search.value='';const tabs=document.createElement('div');tabs.id='assignmentTypes14253';tabs.className='account-types14253';tabs.setAttribute('aria-label','Account categories');for(const [key,label,symbol]of [['','All',''],...AccountGroups14253.groups]){const b=document.createElement('button');b.type='button';b.textContent=(symbol?symbol+' ':'')+label;b.setAttribute('aria-pressed',String(!key));b.onclick=()=>{category=key;for(const n of tabs.children)n.setAttribute('aria-pressed',String(n===b));filterAccessPicker(search.value||'');};tabs.append(b);}search.after(tabs);return r;};}
function installSystem(){const select=$('accType');if(!select)return;select.add(new Option('System','SYSTEM'));const field=document.createElement('div');field.className='settings-field';field.id='systemBaseField14253';field.hidden=true;field.innerHTML='<label for="systemBase14253">Underlying accounting classification *</label><select id="systemBase14253" class="je-select">'+['ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE'].map(v=>'<option>'+v+'</option>').join('')+'</select>';select.closest('.settings-field').after(field);const sync=()=>{field.hidden=select.value!=='SYSTEM';if(select.value==='SYSTEM'&&$('accPurpose71').value==='regular')$('accPurpose71').value='clearing';};select.addEventListener('change',sync);
const add=window.openAddAccountModal;window.openAddAccountModal=function(system=false){const r=add.apply(this,arguments);if(system)select.value='SYSTEM';sync();return r;};const edit=window.openEditAccountModal;window.openEditAccountModal=function(code){const r=edit.apply(this,arguments),a=AccountingStore.accounts.find(a=>a.code===code);if(AccountGroups14253.type(a)==='SYSTEM'){select.value='SYSTEM';$('systemBase14253').value=a.baseType||'EQUITY';}sync();return r;};const save=window.handleAccountFormSubmit;window.handleAccountFormSubmit=async function(event){if(select.value!=='SYSTEM')return save.apply(this,arguments);event.preventDefault();if($('accPurpose71').value==='regular'||!$('accPurpose71').value){showCenterStatus('Select a system account purpose.',true);return;}select.value=$('systemBase14253').value;try{return await save.apply(this,arguments);}finally{if($('modalAccount').classList.contains('active'))select.value='SYSTEM';sync();}};}
window.Reports14253={manage,submit,summarize,description,prepare};window.UserAdmin14253=UserAdmin;
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ready,{once:true});else ready();
})();
