const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict');
const results=[];async function check(name,fn){try{await fn();results.push({name,passed:true});console.log('PASS',name)}catch(e){results.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message)}}
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const binary={args:['--no-sandbox','--disable-dev-shm-usage'],executablePath:async()=>'/tmp/chromium'};
const root=process.argv[2]||path.resolve(__dirname,'..');fs.mkdirSync(path.join(root,'validation/screenshots'),{recursive:true});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.svg':'image/svg+xml','.png':'image/png'};
const server=http.createServer((req,res)=>{const p=path.join(root,decodeURIComponent(req.url.split('?')[0]));try{res.setHeader('Content-Type',mime[path.extname(p)]||'application/octet-stream');res.end(fs.readFileSync(p));}catch{res.statusCode=404;res.end();}});
(async()=>{if(fs.existsSync('/tmp/chromium')&&!fs.statSync('/tmp/chromium').size)fs.unlinkSync('/tmp/chromium');await new Promise(r=>server.listen(0,'127.0.0.1',r));
const base='http://127.0.0.1:'+server.address().port;const browser=await chromium.launch({headless:true,executablePath:process.env.CHROMIUM_PATH||await binary.executablePath(),args:binary.args.filter(a=>!a.includes("disable-web-security"))});
const context=await browser.newContext({viewport:{width:1280,height:900},isMobile:false,hasTouch:false});const page=await context.newPage();const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.log('PAGEERROR',e.stack||e.message)});
await page.addInitScript(()=>{
 const ActualDate=Date;window.Date=class extends ActualDate{constructor(...args){super(...(args.length?args:['2026-10-09T08:00:00Z']))}static now(){return new ActualDate('2026-10-09T08:00:00Z').getTime()}};
 const uid=n=>'00000000-0000-4000-8000-'+String(n).padStart(12,'0');
 const profiles=[{id:uid(1),email:'admin@example.invalid',full_name:'Santos Cabbigat',role:'admin',status:'active',user_permissions:{modules:[]}},...['Ryan Santos','Jade Plata','Gee Ann'].map((name,i)=>({id:uid(i+2),email:'staff'+i+'@example.invalid',full_name:name,role:'submitter',status:'active',user_permissions:{manager_id:uid(1),job_title:'Employee',department14229:'Operations',assigned_fund_account_ids:[uid(101+i)],destination_account_ids:[uid(110)],allowed_directions:['out'],module_actions113:{'sub-users-workspace':['view','edit'],'user-entry-review':['view','approve']}}}))];
 const accounts=['LAK','USD','THB'].map((c,i)=>({id:uid(101+i),code:String(101+i),name:'Cash on Hand',currency_code:c,currency:c,type:'ASSET',account_type:'ASSET',is_posting:true,isPosting:true,active:true}));accounts.push({id:uid(110),code:'5100',name:'Supplies',currency_code:'LAK',currency:'LAK',type:'EXPENSE',account_type:'EXPENSE',is_posting:true,isPosting:true,active:true});
 const balances=Object.fromEntries(profiles.slice(1).map((u,i)=>[u.id,[{id:accounts[i].id,account_id:accounts[i].id,name:accounts[i].name,currency:accounts[i].currency,opening:1000,received:100,used:20,handover:0,closing:1080}]]));
 const permissions=profiles.map(u=>({user_id:u.id,...u.user_permissions}));accounts.forEach(a=>a.is_active=true);const tables={report_types14253:[{id:uid(700),name:'Cashier report',active:true},{id:uid(701),name:'Expense report',active:true}],business_settings:[{id:true,legal_name:"Fixture Business",display_name:"Fixture Business"}],profiles,accounts,user_permissions:permissions,session_policy1443:[{id:true,timeout_minutes:60,warning_minutes:1}],currencies:[{code:'LAK',symbol:'₭',is_active:true,is_base:true},{code:'USD',symbol:'$',is_active:true},{code:'THB',symbol:'฿',is_active:true}]};
 function query(table){let filters=[];let single=false;let update=null;const q=new Proxy({}, {get(_,k){if(k==='then')return (resolve,reject)=>{const rows=(tables[table]||[]).filter(r=>filters.every(([k,v])=>(k.includes('->>')?r[k.split('->>')[0]]?.[k.split('->>')[1]]:r[k])===v));if(update){window.__writes.push({table,filters,update});rows.forEach(r=>{Object.assign(r,update);if(table==='user_permissions')Object.assign(profiles.find(u=>u.id===r.user_id).user_permissions,update)})}return Promise.resolve({data:single?rows[0]||null:rows,error:null}).then(resolve,reject)};return (...args)=>{if(k==='eq')filters.push(args);if(k==='single'||k==='maybeSingle')single=true;if(k==='update')update=args[0];if(k==='insert'){const row={id:crypto.randomUUID(),version:1,updated_at:new Date().toISOString(),...args[0]};(tables[table]||= []).push(row);filters.push(['id',row.id]);window.__writes.push({table,insert:row});}return q;}}});return q;}
 window.__pack14232={format:'oonjai-data-113',from:'2026-01-01',to:'2026-12-31',tables:{accounts,sub_accounts:[],currencies:tables.currencies,profiles,user_permissions:permissions,journal_entries:[{id:uid(201),entry_no:'TEST-1',transaction_date:'2026-01-05',memo:'Audit source',status:'posted'}],journal_lines:[{id:uid(301),journal_entry_id:uid(201),account_id:uid(110),currency_code:'LAK',debit:100,credit:0},{id:uid(302),journal_entry_id:uid(201),account_id:uid(101),currency_code:'LAK',debit:0,credit:100}],payroll_runs:[{id:uid(401),period_start:'2026-01-01',data:{results:[{employeeId:uid(501),name:'Audit Employee',net:1000}]}}],payroll_employees:[{id:uid(501),data:{name:'Audit Employee',salary:1000}}]},auditTrail:{audit_log:[]},storage:[]};const rpc=async(name,p={})=>{window.__calls.push(name);let data=[];if(name==='admin_save_access1441')data={saved:true,user_id:p.p_user};if(name==='workflow_capabilities14253')data={version:14253};if(name==='submit_report14253'){window.__submitted14253=structuredClone(p);data=null;}if(name==='audit_snapshot14232')data=window.__pack14232;if(name==='backup_export113')data=window.__pack14232;if(name==='accounting_archive_preview127')data={rows:{},categories:{},total:0};if(name==='accounting_archive_audit126')data={audit_log:[]};if(name==='scoped_reset_backup14232')data={format:'oonjai-reset-14232',scopes:p.p_scopes,tables:{audit_log:[{id:1}]}};if(name==='scoped_reset14232')data={counts:{audit_log:1},total:1,requiredTables:[],preserved:'All unselected areas'};if(name==='branch_home14229')data={users:profiles.map(u=>({id:u.id,full_name:u.full_name,email:u.email,can_open:true,user_permissions:{assigned_fund_account_ids:u.user_permissions.assigned_fund_account_ids||[]}})),balances,reports:[]};if(name==='review_directory14229')data=profiles;if(name==='current_access14228')data={profile:profiles[0],permissions:profiles[0].user_permissions};if(name==='fund_balances136')data=balances[p.p_owner]||[];if(name==='reminder_load14229')data={revision:0,items:[]};if(name==='employee_photo113')data=null;if(name==='get_session_policy1443')data={timeout_minutes:60,warning_minutes:1};return {data:JSON.parse(JSON.stringify(data)),error:null};};
 window.__writes=[];window.__calls=[];window.__fixture={profiles,accounts,balances,tables};window.__db14231={rpc,from:query,auth:{getSession:async()=>({data:{session:null},error:null}),onAuthStateChange:()=>{},signInWithPassword:async()=>{await new Promise(r=>window.__releaseLoginFixture14232=r);return {data:{},error:{message:'Test sign-in rejected'}};},signOut:async()=>({error:null})},storage:{from:()=>({})},functions:{invoke:async()=>({data:{},error:null})}};
});
await page.route('**/*',route=>{const url=route.request().url();if(url.includes('assets/vendor/supabase.js')||url.includes('supabase-js'))return route.fulfill({contentType:'text/javascript',body:'window.supabase={createClient:()=>window.__db14231};'});if(url.startsWith(base))return route.continue();return route.abort();});
await page.goto(base+'/index.html',{waitUntil:'load'});await page.waitForTimeout(500);

await page.evaluate(()=>{liveProfile=__fixture.profiles[0];livePermission=__fixture.profiles[0].user_permissions;liveProfiles=__fixture.profiles;ojmDb=__db14231;window.ojmDb=ojmDb;DemoAccess.currentUser={...liveProfile,name:liveProfile.full_name,active:true};AccountingStore.accounts=__fixture.accounts;CurrencyStore.currencies=[{code:'LAK',symbol:'₭'},{code:'USD',symbol:'$'},{code:'THB',symbol:'฿'}];document.getElementById('loginGate').classList.add('is-authenticated');document.documentElement.classList.remove('session-checking1444');window.permissions1441.verified=true;});




page.setDefaultTimeout(10000);

await page.evaluate(async()=>{
 const e={id:'10000000-0000-4000-8000-000000000001',version:1,data:{code:'OJ-01',name:'HR Test Employee',salary:3500000,currency:'LAK',active:true,position:'Staff',renewal:'2026-01-01',vacation:15,sick:5,personal:3,bereavement:3,sso:false,pit:false,pitShare:50,contracts99:[{id:'contract-1',title:'Initial agreement',start:'2026-01-01',end:'2026-10-15',status:'active',reminderMonths:2,reminderDays:0}]}};
 __fixture.tables.payroll_employees=[e];__fixture.tables.payroll_leave_records=[];__fixture.tables.payroll_runs=[];__fixture.tables.operational_reports=[];__fixture.tables.hr_calendar_events14306=[];__fixture.tables.hr_calendar_settings14306=[{id:true,version:1,data:HRCalendarModel14306.scheduleDefaults({nonWorkDays99:[0,6]})}];Work82.loaded=false;await loadWork82(true);hrCalendar14306.state.month='2026-10';
 window.__uploads=[];window.__storedFiles={};ojmDb.storage={from:()=>({upload:async(path,file)=>{__uploads.push(path);__storedFiles[path]=file;return {data:{path},error:null}},download:async path=>({data:__storedFiles[path],error:null}),remove:async paths=>{paths.forEach(p=>delete __storedFiles[p]);return {error:null}}})};
});
await check('HR tabs follow the requested order and Employee has no leave clutter',async()=>{
 await page.evaluate(()=>switchTab('payroll-employees'));await page.waitForTimeout(250);const labels=await page.locator('#nav-module-hr .nav-links button').allTextContents();assert.deepEqual(labels.map(x=>x.trim()),['Employee','Attendance','Leave','Assessment','Contract Documents','Calendar']);const text=await page.locator('#payroll-employees').innerText();assert(!text.includes('Reload Records'));assert(!text.includes('Leave Balances'));assert(!text.includes('Print Leave Report'));assert.equal(await page.locator('#payroll-employees>[data-print14282]').count(),0);
});
await check('Employee edit is a compact modal without the sample checkbox',async()=>{
 await page.locator('#payroll-employees .row-menu99 summary').first().click();await page.locator('[data-edit-employee]:visible').first().click();const box=page.locator('#hrEmployeeDialog14306');assert(await box.isVisible());assert.equal(await box.locator('[name=isSample]').count(),0);assert((await box.boundingBox()).width<=840);await box.locator('[name=renewal]').locator('..').locator('.oj-date-button104').click();assert(await box.locator('.oj-date-popup104').isVisible());await box.locator('.oj-date-popup104 button[data-value="2026-01-02"]').click();assert.equal(await box.locator('[name=renewal]').inputValue(),'2026-01-02');await box.locator('[name=payrollAccountId]').evaluate(n=>dropdown1434.open(n));assert(await box.locator('.account-list1428').isVisible());await page.evaluate(()=>dropdown1434.close());await page.screenshot({path:'/tmp/hr-employee14306.png'});await box.locator('header button').click();
});
await check('Calendar matches Design B, circles today and centers the next agenda event',async()=>{
 await page.evaluate(()=>switchTab('hr-calendar'));await page.waitForTimeout(250);assert.equal(await page.locator('.hr-weekdays14306 strong').count(),7);assert.equal(await page.locator('.hr-date14306 button[aria-current=date]').count(),1);const centered=await page.locator('#hrAgenda14306').evaluate(n=>{const r=n.getBoundingClientRect(),i=n.querySelector('[data-next14306]').getBoundingClientRect();return Math.abs(i.top+i.height/2-r.top-r.height/2)});assert(centered<5,'Center deviation '+centered);const agenda=await page.locator('.hr-calendar-layout14306>aside').boundingBox(),month=await page.locator('.hr-month14306').boundingBox();assert(agenda.x<month.x);await page.screenshot({path:'/tmp/hr-calendar14306.png'});
});
await check('A saved company holiday updates attendance rules and Upcoming Events',async()=>{
 await page.locator('[data-cal-add]').click();const f=page.locator('.hr-dialog14306').last();await f.locator('[name=title]').fill('Company closure');await f.locator('[name=start]').fill('2026-10-15');await f.locator('[name=end]').fill('2026-10-15');await f.locator('[name=type]').selectOption('holiday');await f.locator('[name=effect]').selectOption('off');await f.locator('[name=reminderMonths]').fill('2');await f.getByRole('button',{name:'Save',exact:true}).click();await f.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>hrCalendar14306.day('2026-10-15',Work82.employees[0].id).fraction),0);await page.evaluate(()=>switchTab('transactions-recurring'));assert((await page.locator('#upcomingEvents14306').innerText()).includes('Company closure'));assert((await page.evaluate(()=>hrCalendar14306.notices())).some(n=>n.title==='Company closure'));
});
await check('Leave tab calculates working days and projects pending and approved leave',async()=>{
 await page.evaluate(()=>switchTab('hr-leave'));await page.locator('#hr-leave [data-hr-action=add]').click();const f=page.locator('#leaveForm82');await f.locator('[name=from]').evaluate(n=>{n.value='2026-10-12';n.dispatchEvent(new Event('change',{bubbles:true}))});await f.locator('[name=to]').evaluate(n=>{n.value='2026-10-16';n.dispatchEvent(new Event('change',{bubbles:true}))});await f.locator('[name=to]').dispatchEvent('change');assert.equal(await f.locator('[name=days]').inputValue(),'4');await f.locator('[name=reference]').fill('LEAVE-1');await f.locator('[name=notes]').fill('Planned leave for testing');await f.locator('button[type=submit]').click();await page.waitForFunction(()=>Work82.leaves.length===1);assert((await page.evaluate(()=>hrCalendar14306.allEvents())).some(e=>e.type==='leave'&&e.status==='pending'));await page.locator('#hr-leave .row-menu99 summary').last().click();await page.locator('[data-leave-id]').click();await page.locator('.hr-dialog14306').last().getByRole('button',{name:'Approve',exact:true}).click();await page.waitForFunction(()=>Work82.leaves[0].data.status==='approved');
});
await check('Attendance defaults green, preserves exceptions and uses uniform centered squares',async()=>{
 await page.evaluate(()=>{payroll95.selectMonth('2026-10');syncPayrollRoster99();switchTab('hr-attendance')});await page.waitForTimeout(200);assert((await page.locator('.attendance-grid99 button[onclick*="2026-10-09"]').getAttribute('title')).includes('Present'));assert((await page.locator('.attendance-grid99 button[onclick*="2026-10-15"]').getAttribute('title')).includes('Holiday'));assert((await page.locator('.attendance-grid99 button[onclick*="2026-10-12"]').getAttribute('title')).toLowerCase().includes('paid leave'));const sizes=await page.locator('.attendance-cell101').evaluateAll(ns=>ns.map(n=>({w:n.getBoundingClientRect().width,h:n.getBoundingClientRect().height})));assert(sizes.every(x=>Math.abs(x.w-32)<.5&&Math.abs(x.h-32)<.5));const alignment=await page.locator('.attendance-grid99').evaluate(t=>{const h=t.tHead.rows[0].cells[9].getBoundingClientRect(),c=t.tBodies[0].rows[0].cells[9].getBoundingClientRect();return Math.abs(h.x+h.width/2-c.x-c.width/2)});assert(alignment<.5);await page.locator('.attendance-grid99 button[onclick*="2026-10-09"]').click();assert((await page.locator('#payDay95 .pay-dialog95').boundingBox()).width<=520);await page.screenshot({path:'/tmp/hr-attendance14306.png'});await page.locator('#payDay95 select').first().selectOption('late');await page.locator('#payDay95 input[step="1"]').fill('15');await page.locator('#payDay95 button[type=submit]').click();await page.locator('#hr-attendance').getByRole('button',{name:'Save Attendance',exact:true}).click();await page.waitForFunction(()=>Work82.runs.length===1);assert.equal(await page.evaluate(()=>Work82.runs[0].data.rows[0].input.attendance.find(d=>d.date==='2026-10-09').mark95),'15');
});
await check('Finalized attendance does not change when calendar settings change',async()=>{
 const result=await page.evaluate(()=>{const run=structuredClone(Work82.run);run.calendarSnapshot14306=hrCalendar14306.snapshot();run.status='finalized';run.legendSnapshot95=payroll95.legends();run.leaveSnapshot=Work82.leaves.map(r=>r.data);const before=renderAttendance99(run,true);const saved=hrCalendar14306.state.settings;hrCalendar14306.state.settings={data:{schedules:[{from:'1900-01-01',days:Array.from({length:7},(_,day)=>({day,work:false,fraction:0}))}],holidayOverrides:{}}};const after=renderAttendance99(run,true);hrCalendar14306.state.settings=saved;return before===after});assert(result);
});
await check('Contract outcome requires a reason and termination archives the employee',async()=>{
 await page.evaluate(()=>hrWorkspace14306.openContract(Work82.employees[0].id,'contract-1'));await page.locator('.hr-dialog14306').last().getByRole('button',{name:'Contract Outcome'}).click();const f=page.locator('.hr-dialog14306').last();await f.locator('[name=status]').selectOption('terminated');assert.equal(await f.locator('[name=reason]').getAttribute('required'),'');await f.locator('[name=reason]').fill('Contract terminated with documented reason');await f.getByRole('button',{name:'Save',exact:true}).click();await f.waitFor({state:'detached'});assert.equal(await page.evaluate(()=>Work82.employees[0].data.active),false);assert.equal(await page.evaluate(()=>Work82.employees[0].data.contracts99[0].status),'terminated');assert.equal(await page.evaluate(()=>Work82.employees[0].data.employmentHistory14306.length),1);
});
await check('Private signed contract upload is linked to the employee',async()=>{
 await page.evaluate(()=>hrWorkspace14306.documents(Work82.employees[0].id));await page.locator('.hr-dialog14306').last().getByRole('button',{name:'Upload Document'}).click();const f=page.locator('.hr-dialog14306').last();await f.locator('[name=title]').fill('Signed test agreement');await f.locator('[name=contractId]').selectOption('contract-1');await f.locator('[name=file]').setInputFiles({name:'signed.pdf',mimeType:'application/pdf',buffer:Buffer.from('%PDF-1.4\nfixture')});await f.getByRole('button',{name:'Save',exact:true}).click();await f.waitFor({state:'detached'});const doc=await page.evaluate(()=>Work82.employees[0].data.documents14306[0]);assert.equal(doc.category,'signed');assert.equal(doc.contractId,'contract-1');assert.equal(doc.path.split('/')[0],await page.evaluate(()=>Work82.employees[0].id));
});
await check('HR records and signed files are included in complete archives',async()=>{const result=await page.evaluate(async()=>{__pack14232.tables.payroll_employees=Work82.employees;const pack=await dataTools14232.snapshot({p_from:null,p_to:null},()=>{},true);return {events:pack.tables.hr_calendar_events14306.length,files:pack.storage.filter(f=>f.bucket==='hr-documents14306').map(f=>({data:!!f.data,hash:!!f.hash}))}});assert.equal(result.events,1);assert.deepEqual(result.files,[{data:true,hash:true}]);});
await check('Stale calendar edits are rejected without replacing the saved event',async()=>{const result=await page.evaluate(async()=>{const record=hrCalendar14306.state.rows[0],before=JSON.stringify(record.data);try{await hrCalendar14306.saveEvent({...record.data,title:'Stale overwrite'},{...record,version:record.version-1});return false}catch(e){return /changed elsewhere/.test(e.message)&&JSON.stringify(hrCalendar14306.state.rows[0].data)===before}});assert(result);});
await check('Calendar fits desktop and tablet without page overflow',async()=>{
 for(const width of [1280,1024,768]){await page.setViewportSize({width,height:900});await page.evaluate(()=>switchTab('hr-calendar'));await page.waitForTimeout(150);assert(await page.locator('#hr-calendar').evaluate(n=>n.scrollWidth<=n.clientWidth+1),'Calendar overflow at '+width);await page.screenshot({path:'/tmp/hr-calendar14306-'+width+'.png'});}
});
await check('No uncaught errors',async()=>assert.deepEqual(errors,[]));
fs.writeFileSync(path.join(root,'validation/hr14306.json'),JSON.stringify(results,null,2));await browser.close();server.close();if(results.some(x=>!x.passed))process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
